-- 186 - tab Object FIRE (tiket 35): T_LOCATIONLIST, T_PROPERTY (sebagian), T_RISKLOCATION, T_BUILDINGCONSTRUCTION.
--
-- Tabel RANCANGAN (`loader/skema_gen.go`): jalur `LocationList` (induk T_GENERAL_POLIS) -> `LocationList/Property`
-- -> `.../RiskLocation` dan `.../BuildingConstruction`. Nama/tipe = rancangan; ID/PARENT_ID angka NUMBER(19)
-- (identitas dari sequence, pola A92); T_LOCATIONLIST.PARENT_ID VARCHAR2(32) = T_GENERAL_POLIS.ID (butir 76.1).
-- SEBAGIAN (pola butir 78.4): kolom uang tanpa presisi (T_LOCATIONLIST LOSS_RATIO*_AMOUNT, T_PROPERTY TOTAL_TSI) dan
-- kolom yang tidak dipakai layar ditambah tiket 23 lewat ALTER. T_PROPERTY.CURRENCY_CODE ikut (K-069, DEFAULT).
-- T_RISKLOCATION dan T_BUILDINGCONSTRUCTION UTUH, plus tiga kolom BARU (bukan di rancangan) -
-- PARTITION_TYPE / SUPPORT_WALL_TYPE / OTHERS_TYPE <- `.Property.BuildingConstruction.PartitionType` /
-- `SupportWallType` / `OthersType` (`Section\ObjectDetails.xml` sel 56-58), tipe = kolom saudaranya (A110).
-- Satu halaman per induk (Property, RiskLocation, BuildingConstruction): UNIQUE (PARENT_ID) (pola A87).
-- Nol COMMIT (ADR-U-0029).
CREATE TABLE {skema}.T_LOCATIONLIST (
  ID        NUMBER(19) NOT NULL,
  IDPEGA    VARCHAR2(50),
  COB_GROUP VARCHAR2(20),
  PARENT_ID VARCHAR2(32) NOT NULL,
  SEQ_NO    NUMBER(5) NOT NULL,
  ROW_UID   VARCHAR2(36) NOT NULL,
  CONSTRAINT PK_T_LOCATIONLIST PRIMARY KEY (ID),
  CONSTRAINT FK_LOCATIONLIST_GENERAL FOREIGN KEY (PARENT_ID) REFERENCES {skema}.T_GENERAL_POLIS (ID)
)
/
CREATE INDEX {skema}.IX_LOCATIONLIST_PARENT ON {skema}.T_LOCATIONLIST (PARENT_ID, SEQ_NO)
/
CREATE TABLE {skema}.T_PROPERTY (
  ID                 NUMBER(19) NOT NULL,
  IDPEGA             VARCHAR2(50),
  COB_GROUP          VARCHAR2(20),
  PARENT_ID          NUMBER(19) NOT NULL,
  ALM_RISK_ID        VARCHAR2(50),
  BUILDING_NO        VARCHAR2(50),
  COUNTRY            VARCHAR2(50),
  IS_MATERIAL_DAMAGE VARCHAR2(10),
  IS_TOP_RISK        VARCHAR2(10),
  OBJECT_NAME        VARCHAR2(500),
  OBJECT_NO          VARCHAR2(50),
  OBJECT_TYPE        VARCHAR2(50),
  PROVINCE           VARCHAR2(50),
  ROAD_NAME          VARCHAR2(500),
  ROAD_TYPE          VARCHAR2(50),
  CURRENCY_CODE      VARCHAR2(10) DEFAULT 'UNKNOWN' NOT NULL,
  CONSTRAINT PK_T_PROPERTY PRIMARY KEY (ID),
  CONSTRAINT UQ_T_PROPERTY_PARENT UNIQUE (PARENT_ID),
  CONSTRAINT FK_PROPERTY_LOCATIONLIST FOREIGN KEY (PARENT_ID) REFERENCES {skema}.T_LOCATIONLIST (ID)
)
/
CREATE TABLE {skema}.T_RISKLOCATION (
  ID           NUMBER(19) NOT NULL,
  IDPEGA       VARCHAR2(50),
  COB_GROUP    VARCHAR2(20),
  PARENT_ID    NUMBER(19) NOT NULL,
  ASM_ADDRESS  VARCHAR2(50),
  ASM_CITY     VARCHAR2(50),
  ASM_DISTRICT VARCHAR2(50),
  ASMRW        VARCHAR2(50),
  ASM_ZIP_CODE VARCHAR2(50),
  CONSTRAINT PK_T_RISKLOCATION PRIMARY KEY (ID),
  CONSTRAINT UQ_T_RISKLOCATION_PARENT UNIQUE (PARENT_ID),
  CONSTRAINT FK_RISKLOCATION_PROPERTY FOREIGN KEY (PARENT_ID) REFERENCES {skema}.T_PROPERTY (ID)
)
/
CREATE TABLE {skema}.T_BUILDINGCONSTRUCTION (
  ID                NUMBER(19) NOT NULL,
  IDPEGA            VARCHAR2(50),
  COB_GROUP         VARCHAR2(20),
  PARENT_ID         NUMBER(19) NOT NULL,
  FLOOR_TYPE        VARCHAR2(50),
  NUMBER_OF_FLOOR   VARCHAR2(50),
  ROOF_TYPE         VARCHAR2(50),
  WALL_TYPE         VARCHAR2(50),
  PARTITION_TYPE    VARCHAR2(50),
  SUPPORT_WALL_TYPE VARCHAR2(50),
  OTHERS_TYPE       VARCHAR2(50),
  CONSTRAINT PK_T_BUILDINGCONSTRUCTION PRIMARY KEY (ID),
  CONSTRAINT UQ_T_BUILDINGCONSTR_PARENT UNIQUE (PARENT_ID),
  CONSTRAINT FK_BUILDINGCONSTR_PROPERTY FOREIGN KEY (PARENT_ID) REFERENCES {skema}.T_PROPERTY (ID)
)
/
CREATE SEQUENCE {skema}.SEQ_T_LOCATIONLIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_T_PROPERTY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_T_RISKLOCATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_T_BUILDINGCONSTRUCTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
