-- Jalur mundur 186 - tab Object FIRE (anak sebelum induk).
DROP SEQUENCE {skema}.SEQ_T_BUILDINGCONSTRUCTION
/
DROP SEQUENCE {skema}.SEQ_T_RISKLOCATION
/
DROP SEQUENCE {skema}.SEQ_T_PROPERTY
/
DROP SEQUENCE {skema}.SEQ_T_LOCATIONLIST
/
DROP TABLE {skema}.T_BUILDINGCONSTRUCTION CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_RISKLOCATION CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_PROPERTY CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_LOCATIONLIST CASCADE CONSTRAINTS
/
