-- Jalur mundur 187 - sub-tab Surrounding Risk.
DROP SEQUENCE {skema}.SEQ_T_SURROUNDINGRISK
/
DROP TABLE {skema}.T_SURROUNDINGRISK CASCADE CONSTRAINTS
/
ALTER TABLE {skema}.T_PROPERTY DROP (OWNERSHIP, IS_FLAMMABLE_ITEM_FLAG, IS_HOT_WORK_PROCESS_FLAG, IS_PRODUCTION_PROCESS_FLAG)
/
