-- 187 - sub-tab Surrounding Risk (tiket 38): T_PROPERTY + empat kolom rancangan, T_SURROUNDINGRISK utuh + 18 kolom baru.
--
-- T_PROPERTY (186 sebagian, A109): OWNERSHIP, IS_FLAMMABLE_ITEM_FLAG, IS_HOT_WORK_PROCESS_FLAG, IS_PRODUCTION_PROCESS_FLAG =
-- kolom RANCANGAN (`loader/skema_gen.go`), tipe rancangan; boolean teks "true"/"false" (A115).
-- T_SURROUNDINGRISK = tabel RANCANGAN (jalur `LocationList/Property/SurroundingRisk`, induk T_PROPERTY), dibuat utuh
-- (FLOOD_AREA_STATUS, HOUSEKEEPING_STATUS) + 18 kolom BARU (bukan di rancangan; A130, amandemen loader
-- `amandemenSekitar`) dari `Section\RiskAround.xml`: {FRONT|LEFT|BACK|RIGHT}_{OCCUPATION|CONSTRUCTION|DISTANCE|NOTE}
-- (sel 9-14 / 23-28 / 37-42 / 51-56), FLOOD_AREA (sel 68), HOUSEKEEPING_REMARK (sel 69). Kode VARCHAR2(50), teks
-- VARCHAR2(500) (pola V-6 rancangan); *_OCCUPATION / *_NOTE VARCHAR2(1000) = lebar sumbernya OCCUPATION.OLDID / NAME
-- (DDL OCCUPATION.txt; pola butir 80 "Widen joined columns"); *_CONSTRUCTION VARCHAR2(500): nilai standar terpanjang 215 bita
-- (`DDL\FrontConstruction.xml`, 3 nilai, A130); *_DISTANCE teks angka VARCHAR2(50) (A129, pola NUMBER_OF_FLOOR; bukan uang).
-- ID/PARENT_ID NUMBER(19) (A92); satu baris per Property (UNIQUE PARENT_ID, pola A113). Nol COMMIT (ADR-U-0029).
ALTER TABLE {skema}.T_PROPERTY ADD (
  OWNERSHIP                  VARCHAR2(50),
  IS_FLAMMABLE_ITEM_FLAG     VARCHAR2(10),
  IS_HOT_WORK_PROCESS_FLAG   VARCHAR2(10),
  IS_PRODUCTION_PROCESS_FLAG VARCHAR2(10)
)
/
CREATE TABLE {skema}.T_SURROUNDINGRISK (
  ID                  NUMBER(19) NOT NULL,
  IDPEGA              VARCHAR2(50),
  COB_GROUP           VARCHAR2(20),
  PARENT_ID           NUMBER(19) NOT NULL,
  FLOOD_AREA_STATUS   VARCHAR2(50),
  HOUSEKEEPING_STATUS VARCHAR2(50),
  FRONT_OCCUPATION    VARCHAR2(1000),
  FRONT_CONSTRUCTION  VARCHAR2(500),
  FRONT_DISTANCE      VARCHAR2(50),
  FRONT_NOTE          VARCHAR2(1000),
  LEFT_OCCUPATION     VARCHAR2(1000),
  LEFT_CONSTRUCTION   VARCHAR2(500),
  LEFT_DISTANCE       VARCHAR2(50),
  LEFT_NOTE           VARCHAR2(1000),
  BACK_OCCUPATION     VARCHAR2(1000),
  BACK_CONSTRUCTION   VARCHAR2(500),
  BACK_DISTANCE       VARCHAR2(50),
  BACK_NOTE           VARCHAR2(1000),
  RIGHT_OCCUPATION    VARCHAR2(1000),
  RIGHT_CONSTRUCTION  VARCHAR2(500),
  RIGHT_DISTANCE      VARCHAR2(50),
  RIGHT_NOTE          VARCHAR2(1000),
  FLOOD_AREA          VARCHAR2(50),
  HOUSEKEEPING_REMARK VARCHAR2(500),
  CONSTRAINT PK_T_SURROUNDINGRISK PRIMARY KEY (ID),
  CONSTRAINT UQ_T_SURROUNDINGRISK_PARENT UNIQUE (PARENT_ID),
  CONSTRAINT FK_SURROUNDINGRISK_PROPERTY FOREIGN KEY (PARENT_ID) REFERENCES {skema}.T_PROPERTY (ID)
)
/
CREATE SEQUENCE {skema}.SEQ_T_SURROUNDINGRISK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
