-- Jalur mundur 191 - sub-tab Loss Record.
DROP SEQUENCE {skema}.SEQ_T_COINSDATA
/
DROP TABLE {skema}.T_COINSDATA CASCADE CONSTRAINTS
/
DROP SEQUENCE {skema}.SEQ_T_LISTCAUSEOFLOSS
/
DROP TABLE {skema}.T_LISTCAUSEOFLOSS CASCADE CONSTRAINTS
/
ALTER TABLE {skema}.T_LOCATIONLIST DROP (LOSS_RATIO1_YEAR_AMOUNT, LOSS_RATIO1_YEAR_PERCENT, LOSS_RATIO35_YEAR_AMOUNT, LOSS_RATIO35_YEAR_PERCENT)
/
