-- Jalur mundur 192 - lebar kolom alamat risiko kembali ke lebar 186.
-- ⚠️ MODIFY kembali ke VARCHAR2(50) / VARCHAR2(500) GAGAL (ORA-01441) bila ada nilai tersimpan lebih panjang (Risk
-- Location rangkaian alamat hampir pasti > 50); kosongkan/potong nilai itu lebih dulu (keputusan manusia - data).
ALTER TABLE {skema}.T_PROPERTY MODIFY (ALM_RISK_ID VARCHAR2(50))
/
ALTER TABLE {skema}.T_PROPERTY MODIFY (COUNTRY VARCHAR2(50))
/
ALTER TABLE {skema}.T_PROPERTY MODIFY (PROVINCE VARCHAR2(50))
/
ALTER TABLE {skema}.T_PROPERTY MODIFY (ROAD_TYPE VARCHAR2(50))
/
ALTER TABLE {skema}.T_PROPERTY MODIFY (ROAD_NAME VARCHAR2(500))
/
ALTER TABLE {skema}.T_RISKLOCATION MODIFY (ASM_ZIP_CODE VARCHAR2(50))
/
ALTER TABLE {skema}.T_RISKLOCATION MODIFY (ASMRW VARCHAR2(50))
/
ALTER TABLE {skema}.T_RISKLOCATION MODIFY (ASM_DISTRICT VARCHAR2(50))
/
ALTER TABLE {skema}.T_RISKLOCATION MODIFY (ASM_CITY VARCHAR2(50))
/
ALTER TABLE {skema}.T_RISKLOCATION MODIFY (ASM_ADDRESS VARCHAR2(50))
/
