-- Jalur mundur 193 - tab Coverage FIRE tahap C1.
DROP SEQUENCE {skema}.SEQ_T_COVERAGELIST
/
DROP TABLE {skema}.T_COVERAGELIST CASCADE CONSTRAINTS
/
ALTER TABLE {skema}.T_PROPERTYITEMLIST DROP (TOTAL_GROSS_PREMI, TOTAL_NET_RATE)
/
