-- Jalur mundur 059 - kolom isian layar Input Offer.
ALTER TABLE {skema}.T_PREMIUM_LIST DROP (
  BATAS_USIA_PESERTA, PERIODE_PERTANGGUNGAN, TANGGAL_PENAWARAN, TANGGAL_RESPON,
  TANGGAL_KONFIRMASI, TBC, TANGGAL_TBC, KETERANGAN_MARKETING
)
/
