-- LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md (d) - BACA-SAJA, SESUDAH 931-934. Angka harus sama dengan satu_tabel_acuan.txt;
-- lalu dua CSV sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL satu_tabel_verifikasi.txt
PROMPT 1. M_RICOMM_LIFE_SUMMARY tepat 4 kolom (ID, USEDBY, MODIFIEDDATE, OPERATORID); M_RICOMM_LIFE tepat 6 kolom (ID, IDUSEDBY, USEDBY, CONTRACT, YEAR, COMM); nol JSONDATA
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RICOMM_LIFE_SUMMARY', 'M_RICOMM_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RICOMM_LIFE_SUMMARY', 'M_RICOMM_LIFE');
PROMPT 2. Cacah: ringkasan = N_RINGKASAN acuan; rincian = N_FLAT acuan (+ N_JSON_RINCIAN bila tidak nol)
SELECT COUNT(*) AS N_RINGKASAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RICOMM_LIFE_SUMMARY;
SELECT COUNT(*) AS N_RINCIAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RICOMM_LIFE;
SELECT COUNT(*) AS YATIM FROM POOLDATA.M_RICOMM_LIFE f
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RICOMM_LIFE_SUMMARY s WHERE s.ID = f.IDUSEDBY);
PROMPT 3. Sidik isi (= acuan (a)2 kueri 2 dan 3)
SELECT COUNT(USEDBY) N_USEDBY, COUNT(MODIFIEDDATE) N_MODIFIEDDATE, COUNT(OPERATORID) N_OPERATORID,
       SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(MODIFIEDDATE)) H_MODIFIEDDATE, SUM(ORA_HASH(OPERATORID)) H_OPERATORID,
       SUM(ORA_HASH(ID || '|' || USEDBY || '|' || MODIFIEDDATE || '|' || OPERATORID)) H_BARIS
  FROM POOLDATA.M_RICOMM_LIFE_SUMMARY;
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(CONTRACT) N_CONTRACT, COUNT(YEAR) N_YEAR, COUNT(COMM) N_COMM,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || TO_CHAR(CONTRACT, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''')
           || '|' || TO_CHAR(YEAR, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') || '|'
           || TO_CHAR(COMM, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''))) H_BARIS
  FROM POOLDATA.M_RICOMM_LIFE;
PROMPT 4. RICOMM_LIFE dan view RICOMM_LIFE_SUMMARY tidak ada; constraint IS JSON hilang (nol baris); dua indeks ada
SELECT OBJECT_NAME, OBJECT_TYPE FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('RICOMM_LIFE', 'RICOMM_LIFE_SUMMARY');
SELECT CONSTRAINT_NAME FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND CONSTRAINT_NAME IN ('ENSURE_M_RICOMM_LIFE_SUMMARY_JSON', 'ENSURE_M_RICOMM_LIFE_JSON');
SELECT INDEX_NAME, TABLE_NAME FROM SYS.ALL_INDEXES
 WHERE OWNER = 'POOLDATA' AND INDEX_NAME IN ('IX_M_RICOMM_LIFE_SUMMARY_NAMA', 'IX_M_RICOMM_LIFE_IDUSEDBY');
PROMPT 5. T_MIGRASI (empat baris)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI WHERE NAMA IN ('931_m_ricomm_life_summary_kolom',
  '932_m_ricomm_life_summary_satu_tabel', '933_m_ricomm_life_kolom', '934_m_ricomm_life_satu_tabel') ORDER BY NAMA;
PROMPT 6. Status prosedur Pega (INVALID diharapkan, diterima WO; jangan dikompilasi ulang)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PEGA_M_RICOMM_LIFE', 'PEGA_M_RICOMM_LIFE_SUMMARY');
SPOOL OFF
PROMPT 7. CSV sesudah (bentuk sama dengan CSV SEBELUM)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL M_RICOMM_LIFE_SESUDAH.csv
SELECT ID, IDUSEDBY, USEDBY, TO_CHAR(CONTRACT, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS CONTRACT,
       TO_CHAR(YEAR, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS YEAR, TO_CHAR(COMM, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS COMM
  FROM POOLDATA.M_RICOMM_LIFE ORDER BY ID;
SPOOL OFF
SPOOL M_RICOMM_LIFE_SUMMARY_SESUDAH.csv
SELECT ID, USEDBY, MODIFIEDDATE, OPERATORID FROM POOLDATA.M_RICOMM_LIFE_SUMMARY ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: satu_tabel_verifikasi.txt, M_RICOMM_LIFE_SESUDAH.csv, M_RICOMM_LIFE_SUMMARY_SESUDAH.csv
