-- LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md bab Pemulihan - BACA-SAJA. Penentu keadaan sesudah 931-934 gagal di tengah;
-- bandingkan dengan tabel keputusan di dokumen. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 250 PAGESIZE 100
PROMPT 1. Ringkasan (931/932)
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY'
      AND COLUMN_NAME IN ('USEDBY', 'MODIFIEDDATE', 'OPERATORID'))                                          AS KOLOM_BARU,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY'
      AND COLUMN_NAME = 'JSONDATA')                                                                         AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY') AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'RICOMM_LIFE_SUMMARY')  AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_INDEXES WHERE OWNER = 'POOLDATA' AND INDEX_NAME = 'IX_M_RICOMM_LIFE_SUMMARY_NAMA') AS ADA_INDEKS,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '931_m_ricomm_life_summary_kolom')               AS T931,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '932_m_ricomm_life_summary_satu_tabel')          AS T932
FROM DUAL;
PROMPT 2. Rincian (933/934)
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE'
      AND COLUMN_NAME IN ('IDUSEDBY', 'USEDBY', 'CONTRACT', 'YEAR', 'COMM'))                                AS KOLOM_BARU,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE'
      AND COLUMN_NAME = 'JSONDATA')                                                                         AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RICOMM_LIFE') AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'RICOMM_LIFE')          AS ADA_FLAT,
  (SELECT COUNT(*) FROM SYS.ALL_INDEXES WHERE OWNER = 'POOLDATA' AND INDEX_NAME = 'IX_M_RICOMM_LIFE_IDUSEDBY') AS ADA_INDEKS,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '933_m_ricomm_life_kolom')                       AS T933,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '934_m_ricomm_life_satu_tabel')                  AS T934
FROM DUAL;
PROMPT 3. Isi kolom baru (ORA-00904 = kolom belum ada, wajar; ORA-00942 pada RICOMM_LIFE = sudah dibuang, wajar)
SELECT COUNT(*) AS N, COUNT(USEDBY) AS N_USEDBY FROM POOLDATA.M_RICOMM_LIFE_SUMMARY;
SELECT COUNT(*) AS N, COUNT(IDUSEDBY) AS N_IDUSEDBY FROM POOLDATA.M_RICOMM_LIFE;
SELECT COUNT(*) AS N_FLAT_BELUM_PINDAH FROM POOLDATA.RICOMM_LIFE f
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RICOMM_LIFE m WHERE m.ID = f.ID);
