-- LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md (a)2 dan (c)0 - BACA-SAJA. Angka acuan ketiga tabel SEBELUM 931-934. Dijalankan
-- DUA kali: sesaat SEBELUM cadangan (b) dan TEPAT SEBELUM -migrate (c); kedua keluaran harus SAMA (beda = ada penulis
-- yang masih hidup - ulangi (a)0-(b)). Keluaran ditambahkan ke satu_tabel_acuan.txt. Nilai OPERATORID TIDAK dicetak
-- (nama orang) - hanya sidiknya.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL satu_tabel_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah dan ID tertinggi (pembanding WO 08-10-2026: ringkasan 3, M_RICOMM_LIFE 0, RICOMM_LIFE 2)
SELECT COUNT(*) AS N_RINGKASAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RICOMM_LIFE_SUMMARY;
SELECT COUNT(*) AS N_JSON_RINCIAN FROM POOLDATA.M_RICOMM_LIFE;
SELECT COUNT(*) AS N_FLAT, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.RICOMM_LIFE;
SELECT SEQUENCE_NAME, LAST_NUMBER FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME IN ('M_RICOMM_LIFE_SUMMARY_SEQ', 'M_RICOMM_LIFE_SEQ');
PROMPT 2. Sidik isi ringkasan lewat view (cacah tidak-NULL + jumlah ORA_HASH per kolom dan per baris)
SELECT COUNT(USEDBY) N_USEDBY, COUNT(MODIFIEDDATE) N_MODIFIEDDATE, COUNT(OPERATORID) N_OPERATORID,
       SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(MODIFIEDDATE)) H_MODIFIEDDATE, SUM(ORA_HASH(OPERATORID)) H_OPERATORID,
       SUM(ORA_HASH(ID || '|' || USEDBY || '|' || MODIFIEDDATE || '|' || OPERATORID)) H_BARIS
  FROM POOLDATA.RICOMM_LIFE_SUMMARY;
PROMPT 3. Sidik isi rincian flat RICOMM_LIFE (angka sebagai teks TM9 bertitik desimal)
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(CONTRACT) N_CONTRACT, COUNT(YEAR) N_YEAR, COUNT(COMM) N_COMM,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || TO_CHAR(CONTRACT, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''')
           || '|' || TO_CHAR(YEAR, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') || '|'
           || TO_CHAR(COMM, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''))) H_BARIS
  FROM POOLDATA.RICOMM_LIFE;
PROMPT 4. Rincian yatim (IDUSEDBY tanpa ringkasan) dan status prosedur Pega
SELECT COUNT(*) AS YATIM FROM POOLDATA.RICOMM_LIFE f
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RICOMM_LIFE_SUMMARY s WHERE s.ID = f.IDUSEDBY);
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PEGA_M_RICOMM_LIFE', 'PEGA_M_RICOMM_LIFE_SUMMARY');
PROMPT 5. Nilai ringkasan yang melewati lebar 931 (harus NOL baris; bila ada: BERHENTI)
SELECT ID FROM POOLDATA.RICOMM_LIFE_SUMMARY
 WHERE LENGTHB(USEDBY) > 200 OR LENGTHB(MODIFIEDDATE) > 50 OR LENGTHB(OPERATORID) > 200;
PROMPT 6. Definisi asli JSONDATA (NULLABLE N = NOT NULL; dipakai jalur mundur) dan constraint RICOMM_LIFE
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RICOMM_LIFE_SUMMARY', 'M_RICOMM_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'RICOMM_LIFE' ORDER BY CONSTRAINT_NAME;
SPOOL OFF
