-- LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md (b) - BACA-SAJA. Cadangan CSV SEBELUM 931-934, di folder kerja SQL*Plus:
--   M_RICOMM_LIFE_SUMMARY_JSONDATA.csv - ID + JSONDATA ringkasan (satu-satunya salinan pxObjClass dan bentuk JSON asli)
--   M_RICOMM_LIFE_JSONDATA.csv         - ID + JSONDATA rincian JSON (DEV 0 baris; tetap dibuat)
--   RICOMM_LIFE_SEBELUM.csv            - 6 kolom tabel flat (sumber 934; acuan perbandingan (d))
--   M_RICOMM_LIFE_SUMMARY_SEBELUM.csv  - 4 kolom view ringkasan (acuan perbandingan (d))
-- Dijalankan sebagai BERKAS (@...) supaya TERMOUT OFF berlaku. SQL*Plus 12.2+ atau SQLcl (MARKUP CSV). Berkas CSV
-- memuat OPERATORID (nama orang): simpan di tempat cadangan DBA, jangan dibagikan.
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LONG 2000000 LONGCHUNKSIZE 32767 LINESIZE 32767 TRIMSPOOL ON
SPOOL M_RICOMM_LIFE_SUMMARY_JSONDATA.csv
SELECT ID, JSONDATA FROM POOLDATA.M_RICOMM_LIFE_SUMMARY ORDER BY ID;
SPOOL OFF
SPOOL M_RICOMM_LIFE_JSONDATA.csv
SELECT ID, JSONDATA FROM POOLDATA.M_RICOMM_LIFE ORDER BY ID;
SPOOL OFF
SPOOL RICOMM_LIFE_SEBELUM.csv
SELECT ID, IDUSEDBY, USEDBY, TO_CHAR(CONTRACT, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS CONTRACT,
       TO_CHAR(YEAR, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS YEAR, TO_CHAR(COMM, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS COMM
  FROM POOLDATA.RICOMM_LIFE ORDER BY ID;
SPOOL OFF
SPOOL M_RICOMM_LIFE_SUMMARY_SEBELUM.csv
SELECT ID, USEDBY, MODIFIEDDATE, OPERATORID FROM POOLDATA.RICOMM_LIFE_SUMMARY ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT cadangan selesai: 4 berkas CSV
