package main

// Uji pembangkit daftar modul - struktur tim satu folder per modul (30-09-2026).
//
// Yang dijaga: daftar modul Go TIDAK ditulis tangan. Satu berkas bangkitan per
// folder `modul/<nama>/backend/modul.go`, dan uji "hasil bangkit = isi folder"
// merah - dengan menyebut perintahnya - bila seseorang lupa `go generate`.

import (
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// pohon menulis berkas-berkas `isi` (jalur relatif -> teks) di folder sementara.
func pohon(t *testing.T, isi map[string]string) string {
	t.Helper()
	akar := t.TempDir()
	for j, teks := range isi {
		p := filepath.Join(akar, filepath.FromSlash(j))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(teks), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return akar
}

const modulAlfa = `package backend

import inti "nusantarare/inti/backend"

// Nama pengenal modul ini.
const Nama = "alfa"

// Pendaftaran menyerahkan modul ini kepada perakit.
func Pendaftaran() inti.Pendaftaran { return inti.Pendaftaran{Nama: Nama} }
`

func TestSatuBerkasPerModulBerbackend(t *testing.T) {
	akar := pohon(t, map[string]string{
		"modul/alfa/backend/modul.go": modulAlfa,
		"modul/alfa/MODUL.md":         "# alfa\n",
		// Kerangka: MODUL.md dan docs/ saja - belum dimigrasi, tidak terdaftar.
		"modul/kerangka/MODUL.md":     "# kerangka\n",
		"modul/kerangka/docs/spec.md": "spec\n",
	})
	berkas, err := bangkit(akar)
	if err != nil {
		t.Fatal(err)
	}
	var nama []string
	for n := range berkas {
		nama = append(nama, n)
	}
	sort.Strings(nama)
	if mau := []string{"modul_alfa_gen.go"}; !reflect.DeepEqual(nama, mau) {
		t.Fatalf("berkas bangkitan %v, mau %v", nama, mau)
	}
	isi := string(berkas["modul_alfa_gen.go"])
	for _, mau := range []string{
		"// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.",
		"package daftar",
		`import alfa "nusantarare/modul/alfa/backend"`,
		"func init() { daftarkan(alfa.Pendaftaran()) }",
	} {
		if !strings.Contains(isi, mau) {
			t.Errorf("berkas bangkitan tanpa %q:\n%s", mau, isi)
		}
	}
	if strings.Contains(isi, "\r") {
		t.Error("berkas bangkitan memuat CR; repo ini ber-LF untuk *.go")
	}
}

// ⛔ `modul.go` yang tidak memenuhi bentuk pendaftaran ditolak dengan kalimat
// yang menyebut foldernya - bukan berkas bangkitan yang gagal dikompilasi
// dengan galat yang menunjuk ke tempat lain.
func TestModulGoBerbentukSalahDitolak(t *testing.T) {
	kasus := []struct {
		nama, isi string
		mau       []string
	}{
		{"Nama berbeda dari folder", strings.Replace(modulAlfa, `"alfa"`, `"beta"`, 1),
			[]string{"modul/alfa", `"beta"`}},
		{"tanpa const Nama", strings.Replace(modulAlfa, "const Nama = \"alfa\"\n", "", 1),
			[]string{"modul/alfa", "const Nama"}},
		{"tanpa func Pendaftaran", strings.Replace(modulAlfa, "func Pendaftaran()", "func Lain()", 1),
			[]string{"modul/alfa", "Pendaftaran"}},
		{"Pendaftaran berparameter", strings.Replace(modulAlfa, "func Pendaftaran()", "func Pendaftaran(x int)", 1),
			[]string{"modul/alfa", "Pendaftaran"}},
		{"paket bukan backend", strings.Replace(modulAlfa, "package backend", "package alfa", 1),
			[]string{"modul/alfa", "package backend"}},
	}
	for _, k := range kasus {
		t.Run(k.nama, func(t *testing.T) {
			if k.isi == modulAlfa {
				t.Fatal("prasyarat: pengganti tidak cocok, cacat tidak terpasang")
			}
			akar := pohon(t, map[string]string{"modul/alfa/backend/modul.go": k.isi})
			_, err := bangkit(akar)
			if err == nil {
				t.Fatal("modul.go berbentuk salah diterima")
			}
			for _, m := range k.mau {
				if !strings.Contains(err.Error(), m) {
					t.Errorf("galat %q tidak menyebut %q", err, m)
				}
			}
		})
	}
}

// ⛔ "Hasil bangkit = isi folder": berkas bangkitan yang hilang, berlebih, atau
// berbeda isinya MERAH dengan menyebut perintah yang memperbaikinya.
func TestDaftarBasiMenyebutPerintahnya(t *testing.T) {
	akar := pohon(t, map[string]string{"modul/alfa/backend/modul.go": modulAlfa})
	benar, err := bangkit(akar)
	if err != nil {
		t.Fatal(err)
	}
	kasus := []struct {
		nama  string
		isi   map[string]string
		galat string
	}{
		{"hilang", map[string]string{}, "modul_alfa_gen.go"},
		{"berlebih", map[string]string{"modul_alfa_gen.go": string(benar["modul_alfa_gen.go"]),
			"modul_beta_gen.go": "package daftar\n"}, "modul_beta_gen.go"},
		{"berbeda isi", map[string]string{"modul_alfa_gen.go": "package daftar\n"}, "modul_alfa_gen.go"},
		{"sama", map[string]string{"modul_alfa_gen.go": string(benar["modul_alfa_gen.go"]),
			"daftar.go": "package daftar\n"}, ""},
	}
	for _, k := range kasus {
		t.Run(k.nama, func(t *testing.T) {
			dir := pohon(t, k.isi)
			err := periksa(akar, dir)
			if k.galat == "" {
				if err != nil {
					t.Fatalf("daftar yang sama dinyatakan basi: %v", err)
				}
				return
			}
			if err == nil {
				t.Fatal("daftar basi lolos")
			}
			for _, mau := range []string{k.galat, "go generate ./inti/backend/daftar"} {
				if !strings.Contains(err.Error(), mau) {
					t.Errorf("galat %q tidak menyebut %q", err, mau)
				}
			}
		})
	}
}

// Penjaga di pohon SUNGGUHAN: berkas bangkitan yang di-commit sama dengan isi
// folder `modul/` - dijalankan setiap `go test ./...`.
func TestDaftarBangkitanSamaDenganFolder(t *testing.T) {
	akar := filepath.Join("..", "..", "..", "..") // APP_RNM, dari inti/backend/daftar/bangkit
	if err := periksa(akar, ".."); err != nil {
		t.Fatal(err)
	}
	// Prasyarat POSITIF: penjaga yang membandingkan dua himpunan kosong lulus
	// atas apa pun.
	berkas, err := bangkit(akar)
	if err != nil {
		t.Fatal(err)
	}
	if len(berkas) < 4 {
		t.Fatalf("hanya %d modul terdaftar; pembacanya yang rusak", len(berkas))
	}
	// Direktif go:generate di berkas yang berurut SESUDAH setiap berkas
	// bangkitan: `go generate` membaca berkas menurut abjad, dan pembangkit
	// membuang berkas modul yang sudah tidak ada (`pembangkit.go`).
	berkasGo, err := filepath.Glob(filepath.Join("..", "*.go"))
	if err != nil {
		t.Fatal(err)
	}
	var arahan []string
	for _, b := range berkasGo {
		isi, err := os.ReadFile(b)
		if err != nil {
			t.Fatal(err)
		}
		if strings.Contains(string(isi), "\n//go:generate go run ./bangkit") {
			arahan = append(arahan, filepath.Base(b))
		}
	}
	if len(arahan) != 1 || arahan[0] <= awalanBerkas+"zzz" {
		t.Errorf("direktif go:generate di %v; mau tepat satu berkas bernama sesudah %s*%s", arahan, awalanBerkas, akhiranBerkas)
	}
}
