-- LANGKAH-WO-DISEASELIFE.md (a) P2 acuan dan (c)0 - BACA-SAJA. Angka acuan SEBELUM 080-081 / 951. Dijalankan TIGA kali:
-- (1) sebelum cadangan P3, (2) sesudah P3 dan SEBELUM D2 - keduanya harus SAMA (beda = ada penulis yang masih hidup -
-- ulangi P1-P3), (3) SESUDAH D2 tepat sebelum -migrate: cacah turun tepat 1 (97.585), ID kembar nol. Keluaran
-- ditambahkan ke dis_acuan.txt. Kunci px* TIDAK pernah dicetak.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL dis_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah (pembanding WO 08-10-2026: 97.586; sesudah D2 97.585), ID unik, ID NULL, ID angka tertinggi (197585)
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, COUNT(*) - COUNT(ID) AS N_ID_NULL,
       MAX(TO_NUMBER(REGEXP_SUBSTR(ID, '^[0-9]+$'))) AS ID_ANGKA_TERTINGGI,
       COUNT(DISTINCT UPPER(TRIM(ICD_CODE))) AS N_ICD_UNIK
  FROM POOLDATA.DISEASE_LIFE;
PROMPT 2. Sidik isi: jumlah ORA_HASH per baris (bandingkan dengan (c) sesudah migrasi; sesudah D2 berubah - pakai acuan ketiga)
SELECT COUNT(*) AS N, SUM(ORA_HASH(ID || '|' || ICD_CODE || '|' || DISEASE)) AS H_BARIS FROM POOLDATA.DISEASE_LIFE;
PROMPT 3. ID kembar (sebelum D2: satu baris 102051 x2; sesudah D2: NOL baris) dan ID bukan angka
SELECT ID, COUNT(*) AS N FROM POOLDATA.DISEASE_LIFE GROUP BY ID HAVING COUNT(*) > 1 ORDER BY ID;
SELECT COUNT(*) AS N_ID_BUKAN_ANGKA FROM POOLDATA.DISEASE_LIFE WHERE ID IS NOT NULL AND REGEXP_SUBSTR(ID, '^[0-9]+$') IS NULL;
PROMPT 4. Definisi: kolom (ID NULLABLE = Y sebelum 081), constraint (NOL), indeks (NOL)
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE' ORDER BY COLUMN_ID;
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE';
SELECT INDEX_NAME, UNIQUENESS FROM SYS.ALL_INDEXES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE';
PROMPT 5. Objek, sequence, dependensi, grant (pembanding: TABLE + PROCEDURE PEGA_DISEASE_LIFE VALID; M_DISEASE_LIFE_SEQ 2052; nol grant)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('DISEASE_LIFE', 'M_DISEASE_LIFE', 'M_DISEASE_LIFE_SEQ', 'SEQ_DISEASE_LIFE',
       'PEGA_DISEASE_LIFE', 'PEGA_M_DISEASE_LIFE', 'PK_DISEASE_LIFE') ORDER BY OBJECT_NAME;
SELECT SEQUENCE_NAME, LAST_NUMBER FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME IN ('M_DISEASE_LIFE_SEQ', 'SEQ_DISEASE_LIFE');
SELECT OWNER, NAME, TYPE FROM SYS.ALL_DEPENDENCIES
 WHERE REFERENCED_OWNER = 'POOLDATA' AND REFERENCED_NAME = 'DISEASE_LIFE' ORDER BY OWNER, NAME;
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE';
PROMPT 6. Nomor 080-084 / 951 belum dipakai di T_MIGRASI (K0; harus NOL baris)
SELECT NAMA FROM POOLDATA.T_MIGRASI WHERE SUBSTR(NAMA, 1, 3) BETWEEN '080' AND '084' OR SUBSTR(NAMA, 1, 3) = '951';
SPOOL OFF
