-- LANGKAH-WO-DISEASELIFE.md (c) - BACA-SAJA, SESUDAH 080-081 dan 951. Angka harus sama dengan acuan KETIGA dis_acuan.txt
-- (sesudah D2); lalu CSV sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
-- ⛔ SEQ_DISEASE_LIFE diperiksa lewat LAST_NUMBER (NOCACHE: = nomor berikutnya). JANGAN memanggil NEXTVAL.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL dis_verifikasi.txt
PROMPT 1. Kolom DISEASE_LIFE TIDAK berubah (ID VARCHAR2(100) kini NOT NULL karena PK, ICD_CODE 100, DISEASE 1000)
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE' ORDER BY COLUMN_ID;
PROMPT 2. PK_DISEASE_LIFE (P, ENABLED, VALIDATED) + indeks unik bernama sama
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS, VALIDATED FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE';
SELECT INDEX_NAME, UNIQUENESS, STATUS FROM SYS.ALL_INDEXES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'DISEASE_LIFE';
PROMPT 3. SEQ_DISEASE_LIFE: LAST_NUMBER (= NEXTVAL berikutnya, NOCACHE) > ID angka tertinggi; M_DISEASE_LIFE_SEQ tetap
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE, CYCLE_FLAG FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME IN ('SEQ_DISEASE_LIFE', 'M_DISEASE_LIFE_SEQ') ORDER BY SEQUENCE_NAME;
SELECT CASE WHEN s.LAST_NUMBER > d.ID_TERTINGGI THEN 'OK' ELSE 'SALAH' END AS SEQ_DI_ATAS_ID, s.LAST_NUMBER, d.ID_TERTINGGI
  FROM SYS.ALL_SEQUENCES s,
       (SELECT MAX(TO_NUMBER(REGEXP_SUBSTR(ID, '^[0-9]+$'))) AS ID_TERTINGGI FROM POOLDATA.DISEASE_LIFE) d
 WHERE s.SEQUENCE_OWNER = 'POOLDATA' AND s.SEQUENCE_NAME = 'SEQ_DISEASE_LIFE';
PROMPT 4. Cacah (pembanding 97.585 sesudah D2), ID kembar NOL, sidik = acuan ketiga (a) P2 kueri 2
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, COUNT(*) - COUNT(ID) AS N_ID_NULL FROM POOLDATA.DISEASE_LIFE;
SELECT COUNT(*) AS N, SUM(ORA_HASH(ID || '|' || ICD_CODE || '|' || DISEASE)) AS H_BARIS FROM POOLDATA.DISEASE_LIFE;
PROMPT 5. Objek: PEGA_DISEASE_LIFE tetap VALID (tidak diubah); M_DISEASE_LIFE / PEGA_M_DISEASE_LIFE tidak disentuh
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('DISEASE_LIFE', 'M_DISEASE_LIFE', 'M_DISEASE_LIFE_SEQ', 'SEQ_DISEASE_LIFE',
       'PEGA_DISEASE_LIFE', 'PEGA_M_DISEASE_LIFE', 'PK_DISEASE_LIFE') ORDER BY OBJECT_NAME;
SELECT COUNT(*) AS N_M_DISEASE_LIFE FROM POOLDATA.M_DISEASE_LIFE;
PROMPT 6. T_MIGRASI (tiga baris 080, 081, 951) dan baris menu (diseaselife, Disease Life, MASTER TREATY, 15, 1; STATUS_AKTIF = causeoflosslife)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI
 WHERE NAMA IN ('080_seq_disease_life', '081_disease_life_pk', '951_menu_diseaselife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI, STATUS_AKTIF FROM POOLDATA.M_NAV_MENU
 WHERE KODE IN ('causeoflosslife', 'diseaselife') ORDER BY URUTAN;
PROMPT 7. Pencarian diagnosa claimlife TETAP jalan (kueri claimlife repository/penyakit.go apa adanya, ICD 'A00', batas 500)
SELECT ID, DISEASE, ICD_CODE FROM POOLDATA.DISEASE_LIFE WHERE UPPER(ICD_CODE) LIKE '%'||'A00'||'%' ORDER BY ID FETCH FIRST 500 ROWS ONLY;
SPOOL OFF
PROMPT 8. CSV sesudah (bentuk sama dengan DISEASE_LIFE_LENGKAP.csv) untuk MINUS dua arah
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL DISEASE_LIFE_SESUDAH.csv
SELECT ID, ICD_CODE, DISEASE FROM POOLDATA.DISEASE_LIFE ORDER BY ID, ICD_CODE;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: dis_verifikasi.txt, DISEASE_LIFE_SESUDAH.csv
