package skemauji

// Tiruan tabel warisan Aggregate - `AGGREGATE` (kolom katalog DEV 04-10-2026, PK `ID`). Dibuat SEBELUM migrasi:
// migrasi modul `aggregate` 880 membaca nomor AGG terbesarnya untuk nilai awal SEQ_AGGREGATE (keputusan work owner
// 04-10-2026). Dibongkar bersama tiruan lain sebelum migrasi mundur - jalur mundur 880 hanya DROP SEQUENCE.
//
// ⛔ Nol nama orang, nol data produksi - hanya bentuk tabel.

import "fmt"

// namaTabelTiruanAggregate adalah tabel yang ditiru dan dibongkar bersama skema uji.
var namaTabelTiruanAggregate = []string{"AGGREGATE"}

// ddlTiruanAggregate - DDL tiruan, urut dibuat.
func ddlTiruanAggregate(skema string) []string {
	return []string{
		fmt.Sprintf(`CREATE TABLE %s.AGGREGATE (ID VARCHAR2(100) NOT NULL, TANGGAL_INPUT DATE, USER_INPUT VARCHAR2(100),
  ASSESMENT_ZONE VARCHAR2(100), TREATY_TYPE VARCHAR2(100), COVERAGE VARCHAR2(100), AS_AT DATE, UW_YEAR VARCHAR2(10),
  CEDING_CODE VARCHAR2(20), CEDING_NAME VARCHAR2(100), CURRENCY VARCHAR2(10), TO_USD NUMBER, NOR_BUILDINGS NUMBER,
  BUILDINGS NUMBER, NOR_STOCKS NUMBER, STOCKS NUMBER, NOR_MACHINERY NUMBER, MACHINERY NUMBER, NOR_OTHER_CONTENTS NUMBER,
  OTHER_CONTENTS NUMBER, NOR_CONSEQUENTIAL_LOSS NUMBER, CONSEQUENTIAL_LOSS NUMBER, TOTAL_NO_OF_RISK NUMBER,
  TOTAL_IN_AMOUNT NUMBER, RNM_SHARE NUMBER, RNM_VALUE NUMBER, REMARK VARCHAR2(4000), NOR_RESIDENTIAL NUMBER,
  RESIDENTIAL NUMBER, NOR_COMMERCIAL NUMBER, COMMERCIAL NUMBER, NOR_INDUSTRIAL NUMBER, INDUSTRIAL NUMBER,
  NOR_AGRICULTURE NUMBER, AGRICULTURE NUMBER, NOR_MISCELLANEOUS NUMBER, MISCELLANEOUS NUMBER, NOR_UTILITIES NUMBER,
  UTILITIES NUMBER, TOTAL_IN_AMOUNT_IN_USD NUMBER, RNM_VALUE_IN_USD NUMBER, COMMENCEMENT DATE, TREATYYEAR VARCHAR2(10),
  M_TREATY_ID VARCHAR2(15), CONSTRAINT AGGREGATE_PK PRIMARY KEY (ID))`, skema),
	}
}
