-- Jalur mundur 762 - kolom jejak ubah dibuang. ID_BARIS T_MASTER_STATUS kembali VARCHAR2(100) (gagal ORA-01441 bila
-- sudah ada ID OBJECTITEMTYPE lebih dari 100 byte).
ALTER TABLE {skema}.T_MASTER_STATUS MODIFY (
  ID_BARIS VARCHAR2(100)
)
/
ALTER TABLE {skema}.T_MASTER_STATUS DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.ACCUMULATION DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.CZONE DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.ACCUMULATEDTYPE DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.DISTRICTINPUT DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.CITYINPUT DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
ALTER TABLE {skema}.PROVINCE DROP (CREATE_OP, TGL_CREATE, UPDATE_OP, TGL_UPDATE)
/
