// DIBANGKITKAN `bangkit_kolom_edm.py` (scratchpad sesi) dari korpus `D:\XML\RNM_BRD\Endorsement Life\` - jangan
// diketik ulang. Setiap kolom: label VERBATIM, kolom basis data, jenis (`t` teks, `d` tanggal, `n` angka), dan
// bukti baris (berkas, baris, tag) yang diperiksa `labels.test.ts` terhadap korpus.

/** Satu kolom/medan layar berbukti korpus. */
export interface KolomKorpus {
  label: string
  kolom: string
  jenis: 't' | 'd' | 'n'
  berkas: string
  baris: number
  tag: 'pyValue' | 'pyLabelFieldValue'
}

/** Jenis transaksi `.Type`. */
export type TipeEDM = 'QR' | 'QP' | 'TP' | 'TR'

/** Popup `View Old Policy` - grid peserta versi lama (`WorkLife.PremiumListSummary.PremiumListDetail`). */
export const POLIS_LAMA_PESERTA: Readonly<Record<TipeEDM, readonly KolomKorpus[]>> = {
  QR: [
    { label: 'NAME_OF_INSURED', kolom: 'NAME_OF_INSURED', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 1536, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 1681, tag: 'pyValue' },
    { label: 'SUM_INSURED', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 1826, tag: 'pyValue' },
    { label: 'CEDING_RETENTION', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 1971, tag: 'pyValue' },
    { label: 'SUM_REASURED', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2116, tag: 'pyValue' },
    { label: 'SHARE_NUSANTARA_RE_GROSS', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2261, tag: 'pyValue' },
    { label: 'SUM_AT_RISK_GROSS', kolom: 'SUM_AT_RISK_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2406, tag: 'pyValue' },
    { label: 'GROSS_PREMIUM', kolom: 'GROSS_PREMIUM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2551, tag: 'pyValue' },
    { label: 'DEDUCTION', kolom: 'DEDUCTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2696, tag: 'pyValue' },
    { label: 'NET_PREMIUM', kolom: 'NET_PREMIUM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2841, tag: 'pyValue' },
    { label: 'FACTOR', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 2986, tag: 'pyValue' },
    { label: 'CLAIM_AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 3131, tag: 'pyValue' },
  ],
  QP: [
    { label: 'NAME_OF_INSURED', kolom: 'NAME_OF_INSURED', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 1575, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 1720, tag: 'pyValue' },
    { label: 'SUM_INSURED', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 1865, tag: 'pyValue' },
    { label: 'CEDING_RETENTION', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2010, tag: 'pyValue' },
    { label: 'SUM_REASURED', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2155, tag: 'pyValue' },
    { label: 'SHARE_NUSANTARA_RE_GROSS', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2300, tag: 'pyValue' },
    { label: 'SUM_AT_RISK_GROSS', kolom: 'SUM_AT_RISK_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2445, tag: 'pyValue' },
    { label: 'GROSS_PREMIUM_REFUND', kolom: 'GROSS_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2590, tag: 'pyValue' },
    { label: 'DEDUCTION_REFUND', kolom: 'DEDUCTION_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2735, tag: 'pyValue' },
    { label: 'NET_PREMIUM_REFUND', kolom: 'NET_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 2880, tag: 'pyValue' },
    { label: 'CLAIM_AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 3025, tag: 'pyValue' },
  ],
  TP: [
    { label: 'NAME_OF_INSURED', kolom: 'NAME_OF_INSURED', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 1605, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 1750, tag: 'pyValue' },
    { label: 'SUM_INSURED', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 1895, tag: 'pyValue' },
    { label: 'CEDING_RETENTION', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2040, tag: 'pyValue' },
    { label: 'SUM_REASURED', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2185, tag: 'pyValue' },
    { label: 'SHARE_NUSANTARA_RE_GROSS', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2330, tag: 'pyValue' },
    { label: 'SUM_AT_RISK_RETRO', kolom: 'SUM_AT_RISK_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2475, tag: 'pyValue' },
    { label: 'RETROCEDED_SHARE', kolom: 'RETROCEDED_SHARE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2620, tag: 'pyValue' },
    { label: 'SHARE_RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2765, tag: 'pyValue' },
    { label: 'RATE', kolom: 'RATE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 2910, tag: 'pyValue' },
    { label: 'GROSS_PREMIUM_RETRO', kolom: 'GROSS_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 3055, tag: 'pyValue' },
    { label: 'DISCOUNT_PREMIUM_RETRO', kolom: 'DISCOUNT_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 3200, tag: 'pyValue' },
    { label: 'RI_ADMIN_FEE_RETRO', kolom: 'RI_ADMIN_FEE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 3345, tag: 'pyValue' },
    { label: 'BROKERAGE_FEE_RETRO', kolom: 'BROKERAGE_FEE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 3490, tag: 'pyValue' },
    { label: 'NET_PREMIUM_RETRO', kolom: 'NET_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 3635, tag: 'pyValue' },
  ],
  TR: [
    { label: 'NAME_OF_INSURED', kolom: 'NAME_OF_INSURED', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 1590, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 1735, tag: 'pyValue' },
    { label: 'SUM_INSURED', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 1880, tag: 'pyValue' },
    { label: 'CEDING_RETENTION', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2025, tag: 'pyValue' },
    { label: 'SUM_REASURED', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2170, tag: 'pyValue' },
    { label: 'SHARE_NUSANTARA_RE', kolom: 'SHARE_NUSANTARA_RE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2315, tag: 'pyValue' },
    { label: 'SHARE_NUSANTARA_RE_GROSS', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2460, tag: 'pyValue' },
    { label: 'SUM_AT_RISK_RETRO', kolom: 'SUM_AT_RISK_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2605, tag: 'pyValue' },
    { label: 'RETROCEDED_SHARE', kolom: 'RETROCEDED_SHARE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2750, tag: 'pyValue' },
    { label: 'SHARE_RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 2895, tag: 'pyValue' },
    { label: 'RATE', kolom: 'RATE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3040, tag: 'pyValue' },
    { label: 'FACTOR', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3185, tag: 'pyValue' },
    { label: 'GROSS_PREMIUM_REFUND_RETRO', kolom: 'GROSS_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3330, tag: 'pyValue' },
    { label: 'DISCOUNT_PREMIUM_RETRO', kolom: 'DISCOUNT_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3475, tag: 'pyValue' },
    { label: 'DISCOUNT_PREMIUM_REFUND_RETRO', kolom: 'DISCOUNT_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3620, tag: 'pyValue' },
    { label: 'RI_ADMIN_FEE_REFUND_RETRO', kolom: 'RI_ADMIN_FEE_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3765, tag: 'pyValue' },
    { label: 'BROKERAGE_FEE_RETRO', kolom: 'BROKERAGE_FEE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 3910, tag: 'pyValue' },
    { label: 'NET_PREMIUM_REFUND_RETRO', kolom: 'NET_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 4055, tag: 'pyValue' },
    { label: 'CLAIM_AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 4200, tag: 'pyValue' },
  ],
}

/** Popup `View Old Policy` - rekap RD `BrowsePremiumList_RD`. */
export const POLIS_LAMA_REKAP: Readonly<Record<TipeEDM, readonly KolomKorpus[]>> = {
  QR: [
    { label: 'COB', kolom: 'COB', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7144, tag: 'pyValue' },
    { label: 'PL NUMBER', kolom: 'PL_NUMBER', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7282, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7409, tag: 'pyValue' },
    { label: 'PREMIUM', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7510, tag: 'pyValue' },
    { label: 'DEDUCTION', kolom: 'DEDUCTION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7620, tag: 'pyValue' },
    { label: 'BROKERAGE FEE', kolom: 'BROKERAGE_FEE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7747, tag: 'pyValue' },
    { label: 'RI ADMIN FEE', kolom: 'RI_ADMIN_FEE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7857, tag: 'pyValue' },
    { label: 'TAX', kolom: 'TAX', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 7993, tag: 'pyValue' },
    { label: 'PROF COMM', kolom: 'PROF_COMM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 8129, tag: 'pyValue' },
    { label: 'CLAIM', kolom: 'CLAIM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 8256, tag: 'pyValue' },
    { label: 'BALANCE', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM.xml', baris: 8357, tag: 'pyValue' },
  ],
  QP: [
    { label: 'COB', kolom: 'COB', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 6834, tag: 'pyValue' },
    { label: 'PL NUMBER', kolom: 'PL_NUMBER', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 6972, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7099, tag: 'pyValue' },
    { label: 'PREMIUM', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7200, tag: 'pyValue' },
    { label: 'PREMIUM DEDUCTION', kolom: 'COMMISSION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7310, tag: 'pyValue' },
    { label: 'BROKERAGE FEE', kolom: 'BROKERAGE_FEE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7437, tag: 'pyValue' },
    { label: 'OVR COMM', kolom: 'OVR_COMM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7547, tag: 'pyValue' },
    { label: 'TAX', kolom: 'TAX', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7683, tag: 'pyValue' },
    { label: 'GROSS_PREMIUM_REFUND', kolom: 'GROSS_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7819, tag: 'pyValue' },
    { label: 'DEDUCTION REFUND', kolom: 'DEDUCTION_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 7955, tag: 'pyValue' },
    { label: 'RI ADMIN FEE REFUND', kolom: 'RI_ADMIN_FEE_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8091, tag: 'pyValue' },
    { label: 'BROKERAGE FEE REFUND', kolom: 'BROKERAGE_FEE_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8227, tag: 'pyValue' },
    { label: 'TAX REFUND', kolom: 'TAX_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8363, tag: 'pyValue' },
    { label: 'CLAIM_AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8499, tag: 'pyValue' },
    { label: 'NET_PREMIUM_REFUND', kolom: 'NET_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8635, tag: 'pyValue' },
    { label: 'BALANCE', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_QP.xml', baris: 8762, tag: 'pyValue' },
  ],
  TP: [
    { label: 'COB', kolom: 'COB', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8260, tag: 'pyValue' },
    { label: 'PL NUMBER', kolom: 'PL_NUMBER', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8398, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8525, tag: 'pyValue' },
    { label: 'SHARE RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8635, tag: 'pyValue' },
    { label: 'GROSS PREMIUM RETRO', kolom: 'GROSS_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8771, tag: 'pyValue' },
    { label: 'PREMIUM DEDUCTION', kolom: 'COMMISSION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 8907, tag: 'pyValue' },
    { label: 'BROKERAGE FEE RETRO', kolom: 'BROKERAGE_FEE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9043, tag: 'pyValue' },
    { label: 'DISCOUNT PREMIUM RETRO', kolom: 'DISCOUNT_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9179, tag: 'pyValue' },
    { label: 'RI ADMIN FEE RETRO', kolom: 'RI_ADMIN_FEE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9315, tag: 'pyValue' },
    { label: 'TAX', kolom: 'TAX', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9451, tag: 'pyValue' },
    { label: 'PROF COMM', kolom: 'PROF_COMM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9587, tag: 'pyValue' },
    { label: 'CLAIM', kolom: 'CLAIM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9714, tag: 'pyValue' },
    { label: 'BALANCE', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TP.xml', baris: 9815, tag: 'pyValue' },
  ],
  TR: [
    { label: 'COB', kolom: 'COB', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 9641, tag: 'pyValue' },
    { label: 'PL NUMBER', kolom: 'PL_NUMBER', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 9779, tag: 'pyValue' },
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 9906, tag: 'pyValue' },
    { label: 'SHARE RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10016, tag: 'pyValue' },
    { label: 'GROSS PREMIUM REFUND RETRO', kolom: 'GROSS_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10152, tag: 'pyValue' },
    { label: 'PREMIUM DEDUCTION', kolom: 'COMMISSION', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10288, tag: 'pyValue' },
    { label: 'BROKERAGE FEE REFUND RETRO', kolom: 'BROKERAGE_FEE_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10424, tag: 'pyValue' },
    { label: 'DISCOUNT PREMIUM REFUND RETRO', kolom: 'DISCOUNT_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10560, tag: 'pyValue' },
    { label: 'RI ADMIN FEE REFUND RETRO', kolom: 'RI_ADMIN_FEE_REFUND_RETRO', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10696, tag: 'pyValue' },
    { label: 'TAX', kolom: 'TAX', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10832, tag: 'pyValue' },
    { label: 'PROF COMM', kolom: 'PROF_COMM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 10968, tag: 'pyValue' },
    { label: 'CLAIM', kolom: 'CLAIM', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 11095, tag: 'pyValue' },
    { label: 'BALANCE', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\ViewOldPolicy_EDM_TR.xml', baris: 11196, tag: 'pyValue' },
  ],
}

/** Rekap mata uang `InputEDMLife` (`.PremiumListSummary.CurrencyList`, wadah per `.Type`). */
export const MATA_UANG: Readonly<Record<TipeEDM, readonly KolomKorpus[]>> = {
  QR: [
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 23197, tag: 'pyValue' },
    { label: 'GROSS PREMIUM', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 23311, tag: 'pyValue' },
    { label: 'DEDUCTION', kolom: 'DEDUCTION', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 23447, tag: 'pyValue' },
    { label: 'BROKERAGE FEE', kolom: 'BROKERAGE_FEE', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 23583, tag: 'pyValue' },
    { label: 'NET PREMIUM', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 23719, tag: 'pyValue' },
  ],
  QP: [
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 26210, tag: 'pyValue' },
    { label: 'GROSS PREMIUM REFUND', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 26324, tag: 'pyValue' },
    { label: 'DEDUCTION REFUND', kolom: 'DEDUCTION_REFUND', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 26460, tag: 'pyValue' },
    { label: 'BROKERAGE FEE REFUND', kolom: 'BROKERAGE_FEE_REFUND', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 26596, tag: 'pyValue' },
    { label: 'NET PREMIUM REFUND', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 26732, tag: 'pyValue' },
  ],
  TP: [
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 29209, tag: 'pyValue' },
    { label: 'GROSS PREMIUM RETRO', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 29323, tag: 'pyValue' },
    { label: 'DISCOUNT PREMIUM RETRO', kolom: 'DISCOUNT_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 29459, tag: 'pyValue' },
    { label: 'SHARE RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 29595, tag: 'pyValue' },
    { label: 'NET PREMIUM RETRO', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 29731, tag: 'pyValue' },
  ],
  TR: [
    { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 32208, tag: 'pyValue' },
    { label: 'GROSS PREMIUM REFUND RETRO', kolom: 'PREMIUM', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 32322, tag: 'pyValue' },
    { label: 'DISCOUNT PREMIUM REFUND RETRO', kolom: 'DISCOUNT_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 32458, tag: 'pyValue' },
    { label: 'SHARE RETRO', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 32594, tag: 'pyValue' },
    { label: 'NET PREMIUM REFUND RETRO', kolom: 'BALANCE', jenis: 'n', berkas: 'Section\\InputEDMLife.xml', baris: 32730, tag: 'pyValue' },
  ],
}

/** Rincian peserta `PL_Detail_Sec` (`pyEditAction` `PL_DetailAction`), medan per wadah `pyWorkPage.Type`. */
export const RINCI_PESERTA: Readonly<Record<TipeEDM, readonly KolomKorpus[]>> = {
  QR: [
    { label: 'Begin Date', kolom: 'BEGIN_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 1145, tag: 'pyLabelFieldValue' },
    { label: 'Entry Age', kolom: 'ENTRY_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 1325, tag: 'pyLabelFieldValue' },
    { label: 'PLAN', kolom: 'PLAN', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 13010, tag: 'pyValue' },
    { label: 'STNC', kolom: 'STNC', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2740, tag: 'pyValue' },
    { label: 'Expired Date', kolom: 'EXPIRED_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 2365, tag: 'pyLabelFieldValue' },
    { label: 'Current Age', kolom: 'CURRENT_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 2544, tag: 'pyLabelFieldValue' },
    { label: 'Period MM', kolom: 'PERIOD_MM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 2705, tag: 'pyLabelFieldValue' },
    { label: 'Policy Holder', kolom: 'POLICY_HOLDER', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 2880, tag: 'pyLabelFieldValue' },
    { label: 'Effective Date', kolom: 'EFFECTIVE_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 3585, tag: 'pyLabelFieldValue' },
    { label: 'WPC', kolom: 'WPC', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 3764, tag: 'pyLabelFieldValue' },
    { label: 'Certificate No', kolom: 'CERTIFICATE_NO', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 3952, tag: 'pyLabelFieldValue' },
    { label: 'Currency', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 5215, tag: 'pyLabelFieldValue' },
    { label: 'Sum Reasured', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 5383, tag: 'pyLabelFieldValue' },
    { label: 'Deduction', kolom: 'DEDUCTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 5541, tag: 'pyLabelFieldValue' },
    { label: 'Brokerage Fee', kolom: 'BROKERAGE_FEE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 5699, tag: 'pyLabelFieldValue' },
    { label: 'Sum at Risk Retro', kolom: 'SUM_AT_RISK_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 5857, tag: 'pyLabelFieldValue' },
    { label: 'Retroceded Share', kolom: 'RETROCEDED_SHARE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 6015, tag: 'pyLabelFieldValue' },
    { label: 'Sum Insured', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 6704, tag: 'pyLabelFieldValue' },
    { label: 'RNM Share', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 6864, tag: 'pyLabelFieldValue' },
    { label: 'EM Percent (%)', kolom: 'EM_PERCENT', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 7046, tag: 'pyLabelFieldValue' },
    { label: 'Sum at Risk', kolom: 'SUM_AT_RISK_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 7202, tag: 'pyLabelFieldValue' },
    { label: 'Gross Premium', kolom: 'GROSS_PREMIUM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 7349, tag: 'pyLabelFieldValue' },
    { label: 'Ceding Retention', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 8037, tag: 'pyLabelFieldValue' },
    { label: 'Rate (%)', kolom: 'RATE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 8194, tag: 'pyLabelFieldValue' },
    { label: 'Factor (%)', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 8353, tag: 'pyLabelFieldValue' },
    { label: 'Risk', kolom: 'RISK', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 8512, tag: 'pyLabelFieldValue' },
    { label: 'Net Premium', kolom: 'NET_PREMIUM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 8692, tag: 'pyLabelFieldValue' },
  ],
  QP: [
    { label: 'Begin Date', kolom: 'BEGIN_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 13644, tag: 'pyLabelFieldValue' },
    { label: 'Entry Age', kolom: 'ENTRY_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 13824, tag: 'pyLabelFieldValue' },
    { label: 'PLAN', kolom: 'PLAN', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 13010, tag: 'pyValue' },
    { label: 'STNC', kolom: 'STNC', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2740, tag: 'pyValue' },
    { label: 'Expired Date', kolom: 'EXPIRED_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 14864, tag: 'pyLabelFieldValue' },
    { label: 'Current Age', kolom: 'CURRENT_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 15043, tag: 'pyLabelFieldValue' },
    { label: 'Period MM', kolom: 'PERIOD_MM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 15203, tag: 'pyLabelFieldValue' },
    { label: 'Policy Holder', kolom: 'POLICY_HOLDER', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 15378, tag: 'pyLabelFieldValue' },
    { label: 'Effective Date', kolom: 'EFFECTIVE_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 16083, tag: 'pyLabelFieldValue' },
    { label: 'WPC', kolom: 'WPC', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 16262, tag: 'pyLabelFieldValue' },
    { label: 'Certificate No', kolom: 'CERTIFICATE_NO', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 16450, tag: 'pyLabelFieldValue' },
    { label: 'Currency', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 17713, tag: 'pyLabelFieldValue' },
    { label: 'Sum Reasured', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 17881, tag: 'pyLabelFieldValue' },
    { label: 'Deduction Refund', kolom: 'DEDUCTION_REFUND', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 18040, tag: 'pyLabelFieldValue' },
    { label: 'Brokerage Fee Refund', kolom: 'BROKERAGE_FEE_REFUND', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 18199, tag: 'pyLabelFieldValue' },
    { label: 'Sum at Risk', kolom: 'SUM_AT_RISK_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 18355, tag: 'pyLabelFieldValue' },
    { label: 'Sum Insured', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 19043, tag: 'pyLabelFieldValue' },
    { label: 'RNM Share', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 19204, tag: 'pyLabelFieldValue' },
    { label: 'EM Percent (%)', kolom: 'EM_PERCENT', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 19385, tag: 'pyLabelFieldValue' },
    { label: 'Gross Premium Refund', kolom: 'GROSS_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 19534, tag: 'pyLabelFieldValue' },
    { label: 'Ceding Retention', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 20231, tag: 'pyLabelFieldValue' },
    { label: 'Rate (%)', kolom: 'RATE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 20389, tag: 'pyLabelFieldValue' },
    { label: 'Factor (%)', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 20537, tag: 'pyLabelFieldValue' },
    { label: 'Net Premium Refund', kolom: 'NET_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 20686, tag: 'pyLabelFieldValue' },
  ],
  TP: [
    { label: 'Begin Date', kolom: 'BEGIN_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 34597, tag: 'pyLabelFieldValue' },
    { label: 'Entry Age', kolom: 'ENTRY_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 34777, tag: 'pyLabelFieldValue' },
    { label: 'PLAN', kolom: 'PLAN', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 13010, tag: 'pyValue' },
    { label: 'STNC', kolom: 'STNC', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2740, tag: 'pyValue' },
    { label: 'Expired Date', kolom: 'EXPIRED_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 35818, tag: 'pyLabelFieldValue' },
    { label: 'Current Age', kolom: 'CURRENT_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 35997, tag: 'pyLabelFieldValue' },
    { label: 'Period MM', kolom: 'PERIOD_MM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 36157, tag: 'pyLabelFieldValue' },
    { label: 'Policy Holder', kolom: 'POLICY_HOLDER', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 36332, tag: 'pyLabelFieldValue' },
    { label: 'Effective Date', kolom: 'EFFECTIVE_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 37037, tag: 'pyLabelFieldValue' },
    { label: 'WPC', kolom: 'WPC', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 37217, tag: 'pyLabelFieldValue' },
    { label: 'Certificate No', kolom: 'CERTIFICATE_NO', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 37405, tag: 'pyLabelFieldValue' },
    { label: 'Currency', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 38668, tag: 'pyLabelFieldValue' },
    { label: 'Sum Reasured', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 38837, tag: 'pyLabelFieldValue' },
    { label: 'Deduction', kolom: 'DEDUCTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 38997, tag: 'pyLabelFieldValue' },
    { label: 'RI Admin Fee Retro', kolom: 'RI_ADMIN_FEE_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 39157, tag: 'pyLabelFieldValue' },
    { label: 'Sum At Risk Retro', kolom: 'SUM_AT_RISK_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 39314, tag: 'pyLabelFieldValue' },
    { label: 'Sum Insured', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 40003, tag: 'pyLabelFieldValue' },
    { label: 'RNM Share', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 40165, tag: 'pyLabelFieldValue' },
    { label: 'EM Percent (%)', kolom: 'EM_PERCENT', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 40347, tag: 'pyLabelFieldValue' },
    { label: 'Share Retro', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 40497, tag: 'pyLabelFieldValue' },
    { label: 'Gross Premium Retro', kolom: 'GROSS_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 40654, tag: 'pyLabelFieldValue' },
    { label: 'Ceding Retention', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 41343, tag: 'pyLabelFieldValue' },
    { label: 'Rate (%)', kolom: 'RATE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 41502, tag: 'pyLabelFieldValue' },
    { label: 'Factor (%)', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 41651, tag: 'pyLabelFieldValue' },
    { label: 'Retroceded Share', kolom: 'RETROCEDED_SHARE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 41801, tag: 'pyLabelFieldValue' },
    { label: 'Net Premium Retro', kolom: 'NET_PREMIUM_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 41958, tag: 'pyLabelFieldValue' },
  ],
  TR: [
    { label: 'Begin Date', kolom: 'BEGIN_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 22320, tag: 'pyLabelFieldValue' },
    { label: 'Entry Age', kolom: 'ENTRY_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 22500, tag: 'pyLabelFieldValue' },
    { label: 'PLAN', kolom: 'PLAN', jenis: 't', berkas: 'Section\\InputEDMLife.xml', baris: 13010, tag: 'pyValue' },
    { label: 'STNC', kolom: 'STNC', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2740, tag: 'pyValue' },
    { label: 'Expired Date', kolom: 'EXPIRED_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 23540, tag: 'pyLabelFieldValue' },
    { label: 'Current Age', kolom: 'CURRENT_AGE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 23719, tag: 'pyLabelFieldValue' },
    { label: 'Period MM', kolom: 'PERIOD_MM', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 23879, tag: 'pyLabelFieldValue' },
    { label: 'Policy Holder', kolom: 'POLICY_HOLDER', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 24054, tag: 'pyLabelFieldValue' },
    { label: 'Effective Date', kolom: 'EFFECTIVE_DATE', jenis: 'd', berkas: 'Section\\PL_Detail_Sec.xml', baris: 24759, tag: 'pyLabelFieldValue' },
    { label: 'WPC', kolom: 'WPC', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 24938, tag: 'pyLabelFieldValue' },
    { label: 'Certificate No', kolom: 'CERTIFICATE_NO', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 25126, tag: 'pyLabelFieldValue' },
    { label: 'Currency', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 26389, tag: 'pyLabelFieldValue' },
    { label: 'Sum Reasured', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 26557, tag: 'pyLabelFieldValue' },
    { label: 'Deduction Refund', kolom: 'DEDUCTION_REFUND', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 26716, tag: 'pyLabelFieldValue' },
    { label: 'RI Admin Fee Refund Retro', kolom: 'RI_ADMIN_FEE_REFUND_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 26875, tag: 'pyLabelFieldValue' },
    { label: 'Sum At Risk Retro', kolom: 'SUM_AT_RISK_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 27031, tag: 'pyLabelFieldValue' },
    { label: 'Sum Insured', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 27720, tag: 'pyLabelFieldValue' },
    { label: 'RNM Share', kolom: 'SHARE_NUSANTARA_RE_GROSS', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 27881, tag: 'pyLabelFieldValue' },
    { label: 'EM Percent (%)', kolom: 'EM_PERCENT', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 28062, tag: 'pyLabelFieldValue' },
    { label: 'Share Retro', kolom: 'SHARE_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 28209, tag: 'pyLabelFieldValue' },
    { label: 'Gross Premium Refund Retro', kolom: 'GROSS_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 28357, tag: 'pyLabelFieldValue' },
    { label: 'Ceding Retention', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 29046, tag: 'pyLabelFieldValue' },
    { label: 'Rate (%)', kolom: 'RATE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 29205, tag: 'pyLabelFieldValue' },
    { label: 'Factor (%)', kolom: 'FACTOR', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 29354, tag: 'pyLabelFieldValue' },
    { label: 'Retroceded Share', kolom: 'RETROCEDED_SHARE', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 29502, tag: 'pyLabelFieldValue' },
    { label: 'Net Premium Refund Retro', kolom: 'NET_PREMIUM_REFUND_RETRO', jenis: 'n', berkas: 'Section\\PL_Detail_Sec.xml', baris: 29651, tag: 'pyLabelFieldValue' },
  ],
}

/** Grid spreading `PL_Detail_Sec` (`pyEditAction` `RetroLife`). Kolom = medan `models.Spreading`. */
export const RINCI_SPREADING: readonly KolomKorpus[] = [
  { label: 'Treaty Type', kolom: 'treatyTypeName', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 11001, tag: 'pyValue' },
  { label: 'Retroceded Share', kolom: 'retrocadedShare', jenis: 't', berkas: 'Section\\PL_Detail_Sec.xml', baris: 11147, tag: 'pyValue' },
]

/** `RetroDetailLife` grid b1205. Kolom = medan `models.SpreadingRetro`. */
export const RINCI_RETRO: readonly KolomKorpus[] = [
  { label: 'Reinsurer Name', kolom: 'reinsurerName', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 1333, tag: 'pyValue' },
  { label: 'Percent Share (%)', kolom: 'percentShare', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 1484, tag: 'pyValue' },
  { label: 'Total Share', kolom: 'amount', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 1637, tag: 'pyValue' },
  { label: 'Rate', kolom: 'rate', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 1790, tag: 'pyValue' },
  { label: 'Gross Premium', kolom: 'premiumSpreadedGross', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 1943, tag: 'pyValue' },
  { label: '1st Year Discount (%)', kolom: 'commision', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 2096, tag: 'pyValue' },
  { label: 'RI Admin Fee (%)', kolom: 'ovrComm', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 2249, tag: 'pyValue' },
  { label: 'Net Premium', kolom: 'premiumSpreadedNet', jenis: 't', berkas: 'Section\\RetroDetailLife.xml', baris: 2402, tag: 'pyValue' },
]

/** Popup `View Upload` - `ViewCSVResult_LifeEDM` grid b1082 (`TempWorkPage.ListLifePremiumDetailUpload`). */
export const HASIL_CSV: readonly KolomKorpus[] = [
  { label: 'POLICY NO', kolom: 'POLICY_NO', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1218, tag: 'pyValue' },
  { label: 'POLICY HOLDER', kolom: 'POLICY_HOLDER', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1364, tag: 'pyValue' },
  { label: 'CERTIFICATE NO', kolom: 'CERTIFICATE_NO', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1508, tag: 'pyValue' },
  { label: 'NAME OF INSURED', kolom: 'NAME_OF_INSURED', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1646, tag: 'pyValue' },
  { label: 'SEX', kolom: 'SEX', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1782, tag: 'pyValue' },
  { label: 'DATE OF BIRTH', kolom: 'DOB', jenis: 'd', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 1918, tag: 'pyValue' },
  { label: 'AGE', kolom: 'AGE', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2054, tag: 'pyValue' },
  { label: 'PLAN', kolom: 'PLAN', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2190, tag: 'pyValue' },
  { label: 'BEGIN DATE', kolom: 'BEGIN_DATE', jenis: 'd', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2326, tag: 'pyValue' },
  { label: 'EFFECTIVE DATE', kolom: 'EFFECTIVE_DATE', jenis: 'd', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2465, tag: 'pyValue' },
  { label: 'EXPIRED DATE', kolom: 'EXPIRED_DATE', jenis: 'd', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2601, tag: 'pyValue' },
  { label: 'STNC', kolom: 'STNC', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2740, tag: 'pyValue' },
  { label: 'PERIOD (YY)', kolom: 'PERIOD_YY', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 2878, tag: 'pyValue' },
  { label: 'PERIOD (MM)', kolom: 'PERIOD_MM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3014, tag: 'pyValue' },
  { label: 'PASSED PERIOD', kolom: 'PASSED_PERIOD', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3157, tag: 'pyValue' },
  { label: 'MEDICAL STATUS', kolom: 'MEDICAL_STATUS', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3295, tag: 'pyValue' },
  { label: 'EM%', kolom: 'EM_PERCENT', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3431, tag: 'pyValue' },
  { label: 'SUM INSURED', kolom: 'SUM_INSURED', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3567, tag: 'pyValue' },
  { label: 'CEDING RETENTION', kolom: 'CEDING_RETENTION', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3703, tag: 'pyValue' },
  { label: 'SUM REASURED', kolom: 'SUM_REASURED', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3839, tag: 'pyValue' },
  { label: 'SHARE NUSANTARA RE', kolom: 'SHARE_NUSANTARA_RE', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 3978, tag: 'pyValue' },
  { label: 'RATE', kolom: 'RATE2', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4117, tag: 'pyValue' },
  { label: 'GROSS PREMIUM', kolom: 'GROSS_PREMIUM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4253, tag: 'pyValue' },
  { label: 'GROSS PREMIUM REFUND', kolom: 'GROSS_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4392, tag: 'pyValue' },
  { label: 'FLEET DISCOUNT', kolom: 'FLEET_DISCOUNT', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4531, tag: 'pyValue' },
  { label: 'COMM (%)', kolom: 'COMM_PCT', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4667, tag: 'pyValue' },
  { label: 'COMM', kolom: 'COMM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4806, tag: 'pyValue' },
  { label: 'OVRR COMM', kolom: 'OVR_COMM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 4942, tag: 'pyValue' },
  { label: 'CLAIM AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5081, tag: 'pyValue' },
  { label: 'NET PREMIUM', kolom: 'NET_PREMIUM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5217, tag: 'pyValue' },
  { label: 'NET PREMIUM REFUND', kolom: 'NET_PREMIUM_REFUND', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5356, tag: 'pyValue' },
  { label: 'DESCRIPTION', kolom: 'DESCRIPTION', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5492, tag: 'pyValue' },
  { label: 'CLAIM', kolom: 'CLAIM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5628, tag: 'pyValue' },
  { label: 'BROKERAGE FEE', kolom: 'BROKERAGE_FEE', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5764, tag: 'pyValue' },
  { label: 'TAX', kolom: 'TAX', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 5900, tag: 'pyValue' },
  { label: 'CURRENCY', kolom: 'CURRENCY', jenis: 't', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 6036, tag: 'pyValue' },
  { label: 'PROF COMM', kolom: 'PROF_COMM', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 6172, tag: 'pyValue' },
  { label: 'CLAIM AMOUNT', kolom: 'CLAIM_AMOUNT', jenis: 'n', berkas: 'Section\\ViewCSVResult_LifeEDM.xml', baris: 6311, tag: 'pyValue' },
]
