-- 901 mundur - mengembalikan PARENT_ID, kunci tamunya, indeksnya, dan LIMA
-- butir menu PERSIS isi 900 (label VERBATIM).
--
-- ⛔ Dilindungi pemeriksaan katalog seperti langkah majunya: pelari jalur mundur
-- hanya menoleransi ORA-00942/ORA-02289, jadi ADD yang diulang (ORA-01430,
-- ORA-02275) harus ditanya ke katalog lebih dulu. Kelima INSERT idempoten lewat
-- `WHERE NOT EXISTS` atas KODE - salinan harfiah INSERT butir 900. Nol COMMIT.

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_NAV_MENU' AND COLUMN_NAME = 'PARENT_ID';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_NAV_MENU ADD (PARENT_ID NUMBER(10))';
  END IF;
END;
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_NAV_MENU' AND CONSTRAINT_NAME = 'FK_M_NAV_MENU_INDUK';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_NAV_MENU ADD CONSTRAINT FK_M_NAV_MENU_INDUK FOREIGN KEY (PARENT_ID) REFERENCES {skema}.M_NAV_MENU (ID)';
  END IF;
END;
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_NAV_MENU' AND INDEX_NAME = 'IX_M_NAV_MENU_PARENT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_M_NAV_MENU_PARENT ON {skema}.M_NAV_MENU (PARENT_ID)';
  END IF;
END;
/

INSERT INTO {skema}.M_NAV_MENU (ID, PARENT_ID, KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI)
SELECT {skema}.SEQ_M_NAV_MENU.NEXTVAL, k.ID, 'inbox', 'Inbox Claim Life', k.GROUPMENU, k.MODUL, 1, k.DIMIGRASI
FROM {skema}.M_NAV_MENU k
WHERE k.KODE = 'claimlife' AND k.PARENT_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM {skema}.M_NAV_MENU b WHERE b.KODE = 'inbox')
/
INSERT INTO {skema}.M_NAV_MENU (ID, PARENT_ID, KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI)
SELECT {skema}.SEQ_M_NAV_MENU.NEXTVAL, k.ID, 'register', 'Register', k.GROUPMENU, k.MODUL, 2, k.DIMIGRASI
FROM {skema}.M_NAV_MENU k
WHERE k.KODE = 'claimlife' AND k.PARENT_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM {skema}.M_NAV_MENU b WHERE b.KODE = 'register')
/
INSERT INTO {skema}.M_NAV_MENU (ID, PARENT_ID, KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI)
SELECT {skema}.SEQ_M_NAV_MENU.NEXTVAL, k.ID, 'premiumlist', 'PremiumList', k.GROUPMENU, k.MODUL, 1, k.DIMIGRASI
FROM {skema}.M_NAV_MENU k
WHERE k.KODE = 'premiumlistlife' AND k.PARENT_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM {skema}.M_NAV_MENU b WHERE b.KODE = 'premiumlist')
/
INSERT INTO {skema}.M_NAV_MENU (ID, PARENT_ID, KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI)
SELECT {skema}.SEQ_M_NAV_MENU.NEXTVAL, k.ID, 'komite', 'Inbox Komite', k.GROUPMENU, k.MODUL, 1, k.DIMIGRASI
FROM {skema}.M_NAV_MENU k
WHERE k.KODE = 'komiteclaimlife' AND k.PARENT_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM {skema}.M_NAV_MENU b WHERE b.KODE = 'komite')
/
INSERT INTO {skema}.M_NAV_MENU (ID, PARENT_ID, KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI)
SELECT {skema}.SEQ_M_NAV_MENU.NEXTVAL, k.ID, 'tco-tahun', 'Treaty Contract Out', k.GROUPMENU, k.MODUL, 1, k.DIMIGRASI
FROM {skema}.M_NAV_MENU k
WHERE k.KODE = 'treatycontractout' AND k.PARENT_ID IS NULL
AND NOT EXISTS (SELECT 1 FROM {skema}.M_NAV_MENU b WHERE b.KODE = 'tco-tahun')
/
