-- Mundur 909: urutan TREATY dan MASTER kembali seperti sebelum 909.
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'TREATY', URUTAN = 5, TGL_UBAH = SYSDATE
WHERE KODE = 'premiumlistlife'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'TREATY', URUTAN = 6, TGL_UBAH = SYSDATE
WHERE KODE = 'endorsementlife'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 4, TGL_UBAH = SYSDATE
WHERE KODE = 'marketingofficer'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 5, TGL_UBAH = SYSDATE
WHERE KODE = 'companydetail'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 6, TGL_UBAH = SYSDATE
WHERE KODE = 'accounts'
/
-- Mundur 909: ketiga menu kembali ke golongan dan urutan sebelumnya, lalu CHECK GROUPMENU kembali ke empat nilai 900.
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'TREATY', URUTAN = 3, TGL_UBAH = SYSDATE
WHERE KODE = 'treatyin'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'TREATY', URUTAN = 4, TGL_UBAH = SYSDATE
WHERE KODE = 'treatyinadjustment'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 3, TGL_UBAH = SYSDATE
WHERE KODE = 'treatycontractout'
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_NAV_MENU' AND CONSTRAINT_NAME = 'CK_M_NAV_MENU_GROUPMENU';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_NAV_MENU DROP CONSTRAINT CK_M_NAV_MENU_GROUPMENU';
  END IF;
END;
/
ALTER TABLE {skema}.M_NAV_MENU ADD CONSTRAINT CK_M_NAV_MENU_GROUPMENU CHECK (GROUPMENU IN ('TREATY', 'FACULTATIVE', 'KLAIM', 'MASTER'))
/
