-- Jalur mundur 922 - URUTAN kembali ke nilai di berkas pembuat barisnya (912-919 lokal, 915-918 GitHub).
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 6, TGL_UBAH = SYSDATE
WHERE KODE = 'masternation'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 7, TGL_UBAH = SYSDATE
WHERE KODE = 'masterprovince'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 8, TGL_UBAH = SYSDATE
WHERE KODE = 'mastercity'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 6, TGL_UBAH = SYSDATE
WHERE KODE = 'adjusterconsultant'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 9, TGL_UBAH = SYSDATE
WHERE KODE = 'masterdistrict'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 10, TGL_UBAH = SYSDATE
WHERE KODE = 'masterczone'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 7, TGL_UBAH = SYSDATE
WHERE KODE = 'treatygroupojk'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 11, TGL_UBAH = SYSDATE
WHERE KODE = 'masteraccumulatedtype'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 8, TGL_UBAH = SYSDATE
WHERE KODE = 'treatygroup'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 9, TGL_UBAH = SYSDATE
WHERE KODE = 'businessgroup'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 12, TGL_UBAH = SYSDATE
WHERE KODE = 'masteraccumulation'
/
UPDATE {skema}.M_NAV_MENU SET GROUPMENU = 'MASTER', URUTAN = 13, TGL_UBAH = SYSDATE
WHERE KODE = 'masterobjectitemtype'
/
