-- Mundur 932: kembalikan JSONDATA ringkasan dari kolom (JSON_OBJECT, kunci view: USEDBY, MODIFIEDDATE, OPERATORID;
-- ABSENT ON NULL), constraint IS JSON bernama warisan, dan view RICOMM_LIFE_SUMMARY PERSIS definisi DEV (ber-{skema});
-- buang indeks nama. Sesudahnya 931_down membuang ketiga kolom.
-- HANYA bila 932 TERCATAT di T_MIGRASI. Bila JSONDATA sudah dibuang tetapi 932 tidak tercatat: selesaikan langkah MAJU
-- dulu (LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md, Pemulihan).
-- Kunci pxObjClass dan bentuk JSON asli hanya dari cadangan CSV ID + JSONDATA (LANGKAH-WO (b)).
-- JSONDATA dikembalikan NULLABLE: fakta WO 08-10-2026 hanya "ID VARCHAR2(10) PK + JSONDATA CLOB (IS JSON)" - tanpa
-- bukti NOT NULL; LANGKAH-WO (a) mencatat NULLABLE aslinya, bila N DBA menambah NOT NULL sesudah mundur.
-- ENSURE_M_RICOMM_LIFE_SUMMARY_JSON = 33 byte: nama asli DEV (butuh Oracle 12.2+, yang sudah memuatnya).
--
-- Aman DIULANG sesudah gagal di tengah: indeks, JSONDATA, constraint lewat blok berpelindung katalog; UPDATE menulis
-- nilai yang sama; CREATE VIEW terakhir.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY' AND INDEX_NAME = 'IX_M_RICOMM_LIFE_SUMMARY_NAMA';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_M_RICOMM_LIFE_SUMMARY_NAMA';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY' AND COLUMN_NAME = 'JSONDATA';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_RICOMM_LIFE_SUMMARY ADD (JSONDATA CLOB)';
  END IF;
END;
/
UPDATE {skema}.M_RICOMM_LIFE_SUMMARY m
   SET JSONDATA = JSON_OBJECT('USEDBY' VALUE m.USEDBY, 'MODIFIEDDATE' VALUE m.MODIFIEDDATE,
                              'OPERATORID' VALUE m.OPERATORID ABSENT ON NULL RETURNING CLOB)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE_SUMMARY' AND CONSTRAINT_NAME = 'ENSURE_M_RICOMM_LIFE_SUMMARY_JSON';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_RICOMM_LIFE_SUMMARY ADD CONSTRAINT ENSURE_M_RICOMM_LIFE_SUMMARY_JSON CHECK (JSONDATA IS JSON)';
  END IF;
END;
/
CREATE VIEW {skema}.RICOMM_LIFE_SUMMARY AS
SELECT a.ID, a.JSONDATA.USEDBY, a.JSONDATA.MODIFIEDDATE, a.JSONDATA.OPERATORID
FROM {skema}.M_RICOMM_LIFE_SUMMARY a
/
