-- Mundur 934: bangun ulang tabel RICOMM_LIFE PERSIS bentuk 924 (kolom, PK_RICOMM_LIFE, IX_RICOMM_LIFE_IDUSEDBY) berisi
-- data dari kolom M_RICOMM_LIFE; kembalikan JSONDATA rincian (JSON_OBJECT, kunci Pega IDUSEDBY, USEDBY, CONTRACT, YEAR,
-- COMM; ABSENT ON NULL) + constraint ENSURE_M_RICOMM_LIFE_JSON; buang indeks IX_M_RICOMM_LIFE_IDUSEDBY. Sesudahnya
-- 933_down membuang kelima kolom. Baris tetap ada di M_RICOMM_LIFE (JSON) DAN di RICOMM_LIFE (sebelum 934 JSON 0 baris).
-- HANYA bila 934 TERCATAT di T_MIGRASI (LANGKAH-WO-RICOMMLIFE-SATU-TABEL.md, Pemulihan).
-- JSONDATA dikembalikan NULLABLE (tanpa bukti NOT NULL di repo; LANGKAH-WO (a) mencatat aslinya). Angka ditulis
-- sebagai angka JSON; bentuk JSON Pega asli tidak diketahui (DEV 0 baris).
--
-- Aman DIULANG: tabel, indeks, kolom, constraint lewat blok berpelindung katalog; INSERT NOT EXISTS; UPDATE menulis
-- nilai yang sama.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RICOMM_LIFE' AND COLUMN_NAME = 'ID';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE {skema}.RICOMM_LIFE (ID VARCHAR2(10) NOT NULL, IDUSEDBY VARCHAR2(10), USEDBY VARCHAR2(200), CONTRACT NUMBER(5), YEAR NUMBER(5), COMM NUMBER(38,8), CONSTRAINT PK_RICOMM_LIFE PRIMARY KEY (ID))';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RICOMM_LIFE' AND INDEX_NAME = 'IX_RICOMM_LIFE_IDUSEDBY';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_RICOMM_LIFE_IDUSEDBY ON {skema}.RICOMM_LIFE (IDUSEDBY)';
  END IF;
END;
/
INSERT INTO {skema}.RICOMM_LIFE (ID, IDUSEDBY, USEDBY, CONTRACT, YEAR, COMM)
SELECT m.ID, m.IDUSEDBY, m.USEDBY, m.CONTRACT, m.YEAR, m.COMM FROM {skema}.M_RICOMM_LIFE m
 WHERE NOT EXISTS (SELECT 1 FROM {skema}.RICOMM_LIFE f WHERE f.ID = m.ID)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE' AND INDEX_NAME = 'IX_M_RICOMM_LIFE_IDUSEDBY';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_M_RICOMM_LIFE_IDUSEDBY';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE' AND COLUMN_NAME = 'JSONDATA';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_RICOMM_LIFE ADD (JSONDATA CLOB)';
  END IF;
END;
/
UPDATE {skema}.M_RICOMM_LIFE m
   SET JSONDATA = JSON_OBJECT('IDUSEDBY' VALUE m.IDUSEDBY, 'USEDBY' VALUE m.USEDBY, 'CONTRACT' VALUE m.CONTRACT,
                              'YEAR' VALUE m.YEAR, 'COMM' VALUE m.COMM ABSENT ON NULL RETURNING CLOB)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'M_RICOMM_LIFE' AND CONSTRAINT_NAME = 'ENSURE_M_RICOMM_LIFE_JSON';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.M_RICOMM_LIFE ADD CONSTRAINT ENSURE_M_RICOMM_LIFE_JSON CHECK (JSONDATA IS JSON)';
  END IF;
END;
/
