-- Mundur 937: kembalikan JSONDATA ringkasan dari kolom (JSON_OBJECT, kunci view: USEDBY, MODIFIEDDATE, OPERATORID;
-- ABSENT ON NULL) dan constraint IS JSON bernama asli; buang indeks nama. Sesudahnya 936_down membuang ketiga kolom dan
-- 935_down mengembalikan nama + view.
-- HANYA bila 937 TERCATAT di T_MIGRASI (LANGKAH-WO-RIRISKLIFE.md, Pemulihan). pxObjClass dan bentuk JSON asli hanya
-- dari cadangan CSV P3. JSONDATA dikembalikan NULLABLE (bukti NOT NULL tidak ada di repo; LANGKAH-WO (a) mencatat
-- NULLABLE aslinya). ENSURE_M_RIRISK_LIFE_SUMMARY_JSON = 33 byte: nama asli DEV (Oracle 12.2+, yang sudah memuatnya).
-- Aman DIULANG: indeks, kolom, constraint lewat blok berpelindung katalog; UPDATE menulis nilai yang sama.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE_SUMMARY' AND INDEX_NAME = 'IX_RIRISK_LIFE_SUMMARY_NAMA';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_RIRISK_LIFE_SUMMARY_NAMA';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE_SUMMARY' AND COLUMN_NAME = 'JSONDATA';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.RIRISK_LIFE_SUMMARY ADD (JSONDATA CLOB)';
  END IF;
END;
/
UPDATE {skema}.RIRISK_LIFE_SUMMARY m
   SET JSONDATA = JSON_OBJECT('USEDBY' VALUE m.USEDBY, 'MODIFIEDDATE' VALUE m.MODIFIEDDATE,
                              'OPERATORID' VALUE m.OPERATORID ABSENT ON NULL RETURNING CLOB)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE_SUMMARY' AND CONSTRAINT_NAME = 'ENSURE_M_RIRISK_LIFE_SUMMARY_JSON';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.RIRISK_LIFE_SUMMARY ADD CONSTRAINT ENSURE_M_RIRISK_LIFE_SUMMARY_JSON CHECK (JSONDATA IS JSON)';
  END IF;
END;
/
