-- Mundur 940: kembalikan JSONDATA rincian dari kolom (JSON_OBJECT, kunci Pega CONTRACT, IDUSEDBY, MONTH, RISK, USEDBY,
-- YEAR, AGE; ABSENT ON NULL) + constraint ENSURE_M_RIRISK_LIFE_JSON; buang indeks IX_RIRISK_LIFE_IDUSEDBY (bila dibuat
-- 940) dan PK_RIRISK_LIFE. Sesudahnya 939_down membuang AGE dan 938_down mengembalikan nama + view.
-- HANYA bila 940 TERCATAT di T_MIGRASI (LANGKAH-WO-RIRISKLIFE.md, Pemulihan).
-- RISK ditulis sebagai TEKS bertitik desimal (TO_CHAR TM9 ber-NLS eksplisit) - view lama mengeluarkan teks; bentuk
-- asli (mis. "921,9") dan pxObjClass hanya dari cadangan CSV P3. Kolom datar warisan tetap berisi nilai dari JSONDATA
-- (dulu basi). JSONDATA dikembalikan NULLABLE (LANGKAH-WO (a) mencatat NULLABLE aslinya).
-- Aman DIULANG: indeks, PK, kolom, constraint lewat blok berpelindung katalog; UPDATE menulis nilai yang sama.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE' AND INDEX_NAME = 'IX_RIRISK_LIFE_IDUSEDBY';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_RIRISK_LIFE_IDUSEDBY';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE' AND CONSTRAINT_NAME = 'PK_RIRISK_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.RIRISK_LIFE DROP CONSTRAINT PK_RIRISK_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE' AND COLUMN_NAME = 'JSONDATA';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.RIRISK_LIFE ADD (JSONDATA CLOB)';
  END IF;
END;
/
UPDATE {skema}.RIRISK_LIFE m
   SET JSONDATA = JSON_OBJECT('CONTRACT' VALUE m.CONTRACT, 'IDUSEDBY' VALUE m.IDUSEDBY, 'MONTH' VALUE m.MONTH,
                              'RISK' VALUE TO_CHAR(m.RISK, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''),
                              'USEDBY' VALUE m.USEDBY, 'YEAR' VALUE m.YEAR, 'AGE' VALUE m.AGE ABSENT ON NULL RETURNING CLOB)
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'RIRISK_LIFE' AND CONSTRAINT_NAME = 'ENSURE_M_RIRISK_LIFE_JSON';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.RIRISK_LIFE ADD CONSTRAINT ENSURE_M_RIRISK_LIFE_JSON CHECK (JSONDATA IS JSON)';
  END IF;
END;
/
