-- Jalur mundur 302 - T_TREATYREINSURER. CASCADE CONSTRAINTS membuang FK dari
-- T_MTREATYSECURITY bila anaknya belum sempat dibongkar.
DROP TABLE {skema}.T_TREATYREINSURER CASCADE CONSTRAINTS
/

DROP SEQUENCE {skema}.SEQ_T_TREATYREINSURER
/
