// Code generated oleh alat asisten (bdx_f/bangkit_kepala.py) dari `IPR - Format_Bordereaux_2025.xlsx` - JANGAN
// disunting tangan tanpa menyunting sumbernya. Satu sheet per kombinasi; baris kepala bertanda "No" dan baris di
// bawahnya. Aturan pemetaan (perintah work owner 05-10-2026 "ikuti sheet nya"): kolom TREATY_TYPE (tidak ada di
// sheet) disembunyikan; daun sheet `REINSURED*` dilewati bila kombinasinya tidak punya kolom REINSURED; sisanya
// berpasangan menurut POSISI. Kata "Indonesia Re" di sheet diganti "Nusantara Re". Judul yang diganti work owner:
// Fire Premium `*Premium (100% Ceded Premium)` menjadi `Premium (Reinsurer Share)`.

package models

var kepalaExcel = map[string]map[string]KepalaGrid{
	// Sheet `Fire Premium`.
	"premi.fire": {
		"COB":                    {Judul: "*COB"},
		"TREATY_TYPE":            {Sembunyi: true},
		"POLICY_NO":              {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NO":         {Judul: "CERTIFICATE NUMBER"},
		"INSUREDNAME":            {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":    {Judul: "INSURED AFFILIATION"},
		"POI_START":              {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                {Judul: "*UW YEAR"},
		"COVERAGE":               {Judul: "*COVERAGE"},
		"POLICY_TYPE":            {Judul: "POLICY TYPE"},
		"CURRENCY":               {Judul: "*CURRENCY"},
		"BREAK_SI_MD_BUILDING":   {Grup: "*BREAKDOWN OF SI", Judul: "MD/Building"},
		"BREAK_SI_MD_MACHINERY":  {Grup: "*BREAKDOWN OF SI", Judul: "Machinery"},
		"BREAK_SI_MD_STOCK":      {Grup: "*BREAKDOWN OF SI", Judul: "STOCK"},
		"BREAK_SI_MD_TPL":        {Grup: "*BREAKDOWN OF SI", Judul: "TPL"},
		"BREAK_SI_MD_BI":         {Grup: "*BREAKDOWN OF SI", Judul: "BI"},
		"BREAK_SI_MD_OTHERS":     {Grup: "*BREAKDOWN OF SI", Judul: "OTHERS"},
		"TSI100":                 {Judul: "*100% TSI"},
		"BASIS_OF_INDEMNITY":     {Judul: "*BASIS OF INDEMNITY"},
		"LOL_PML_EML_AMOUT":      {Judul: "* LOL / PML / EML (amount)"},
		"LOL_PML_EML_PCT":        {Judul: "* LOL / PML / EML (%)"},
		"EQ_ZONE":                {Judul: "*EQ ZONE"},
		"OCCUPATION_CODE":        {Judul: "*OCCUPATION CODE"},
		"OCCUPATION":             {Judul: "OCCUPATION"},
		"LOCATION":               {Judul: "*LOCATION"},
		"ZIP_CODE":               {Judul: "*ZIP CODE"},
		"LATITUDE":               {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":              {Grup: "COORDINATES", Judul: "Longitude"},
		"CONSTRUCTION_CLASS":     {Judul: "*CONSTRUCTION CLASS"},
		"SOURCE":                 {Judul: "*SOURCE (DIRECT/INWARD)"},
		"ENDORSMENT":             {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVEDATE_EDM":      {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION_1":          {Judul: "Description"},
		"CEDANT_SHARE_PCT":       {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":    {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANELS":     {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":      {Grup: "*SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":      {Grup: "*SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SURPLUS": {Grup: "*SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS":  {Grup: "*SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM100":             {Judul: "*100% Premium"},
		"PREMIUM_GROSS_RATE":     {Judul: "*Premium Gross Rate"},
		"DISCOUNT":               {Judul: "Discount"},
		"FIRST_LOSS_SCALE":       {Judul: "First Loss Scale"},
		"PREMIUM_NET_RATE":       {Judul: "Premium Net Rate"},
		"PREMIUM_REINSURER":      {Judul: "Premium (Reinsurer Share)"},
		"PREMIUM_RNM":            {Judul: "*Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":     {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION_2":          {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                   {Judul: "NOTE"},
	},
	// Sheet `Eng Premium`.
	"premi.engineering": {
		"COB":                      {Judul: "*COB"},
		"TREATY_TYPE":              {Sembunyi: true},
		"POLICY_NUMBER":            {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":             {Judul: "*INSURED NAME"},
		"BANKER_CLAUSE":            {Judul: "*BANKER CLAUSE"},
		"START_POI":                {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"END_POI":                  {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                  {Judul: "*UW YEAR"},
		"COVERAGE":                 {Judul: "*COVERAGE"},
		"TRANSACTION_TYPE":         {Judul: "* NEW/ RENEWAL/ EXTEND"},
		"START_EXTEND":             {Grup: "Extend Period", Judul: "START"},
		"END_EXTEND":               {Grup: "Extend Period", Judul: "END"},
		"REASON_FOR_EXTEND":        {Judul: "REASON FOR EXTEND (CAR/EAR)"},
		"POLICY_TYPE":              {Judul: "*POLICY TYPE"},
		"ADDITIONAL_COVERAGE":      {Judul: "*ADDITIONAL COVERAGE"},
		"PRINCIPAL_PROJECT":        {Grup: "FOR CAR/EAR", Judul: "*PRINCIPAL PROJECT"},
		"CONTRACTOR_PROJECT":       {Grup: "FOR CAR/EAR", Judul: "*CONTRACTOR PROJECT"},
		"CONTRACTOR_SHARE_HOLDER":  {Grup: "FOR CAR/EAR", Judul: "*CONTRACTOR'S SHAREHOLDER"},
		"PROJECT_NAME":             {Grup: "FOR CAR/EAR", Judul: "*PROJECT NAME"},
		"PROJECT_DESCRIPTION":      {Grup: "FOR CAR/EAR", Judul: "*PROJECT DESCRIPTION"},
		"TYPE_OF_ASSET":            {Grup: "FOR CECR", Judul: "TYPE OF ASSET"},
		"OWNER":                    {Grup: "FOR CECR", Judul: "OWNER"},
		"RUTE":                     {Grup: "FOR CECR", Judul: "RUTE"},
		"YEAR_OF_OPERATION":        {Grup: "FOR CECR", Judul: "YEAR OF OPERATION"},
		"CURRENCY":                 {Judul: "*CURRENCY"},
		"BREAK_SI_TCV":             {Grup: "*BREAKDOWN OF SI", Judul: "TCV (CAR/EAR)"},
		"BREAK_SI_TPLCAREAR":       {Grup: "*BREAKDOWN OF SI", Judul: "TPL (CAR/EAR)"},
		"BREAK_SI_DSU":             {Grup: "*BREAKDOWN OF SI", Judul: "DSU (CAR/EAR)"},
		"BREAK_SI_LOL":             {Grup: "*BREAKDOWN OF SI", Judul: "LOL"},
		"BREAK_SI_TPL":             {Grup: "*BREAKDOWN OF SI", Judul: "TPL"},
		"BREAK_SI_OTHER":           {Grup: "*BREAKDOWN OF SI", Judul: "OTHER"},
		"TSI":                      {Judul: "*100% TSI"},
		"BASIS_OF_INDEMNITY":       {Judul: "*BASIS OF INDEMNITY"},
		"LOL_PML_EML":              {Judul: "* LOL / PML / EML (amount)"},
		"LOL_PML_EML_PCT":          {Judul: "*LOL / PML (%)"},
		"LOCATION":                 {Judul: "*LOCATION"},
		"ZIP_CODE":                 {Judul: "*ZIP CODE"},
		"LATITUDE":                 {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                {Grup: "COORDINATES", Judul: "Longitude"},
		"TESTING_PERIOD":           {Judul: "Testing & Commissioning Period (weeks)"},
		"MEINTENANCE_PERIOD":       {Judul: "*Maintenance Period (months)"},
		"SOURCE":                   {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":              {Judul: "*ENDORSEMENT\n(YES/ NO)"},
		"EFFECTIFDATE_EDM":         {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION1":             {Judul: "Description"},
		"TYPE_BUSINESS":            {Judul: "RENEWAL / NEW BUSINESS"},
		"CEDANTS_SHARE":            {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_IN_AMOUNT":  {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINSURANCE_PANELS": {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPRD_RISK_OR":             {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPRD_RISK_QS":             {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPRD_RISK_SURPLUS":        {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPRD_RISK_OTHERS":         {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":              {Judul: "100% Premium"},
		"PREMIUM_RATE":             {Judul: "Premium Rate"},
		"FIRST_LOSS_SCALE":         {Judul: "First Loss Scale"},
		"PREMIUM_REINSURER":        {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":              {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":       {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":             {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                     {Judul: "NOTE"},
	},
	// Sheet `Cargo Premi`.
	"premi.marine-cargo": {
		"COB":                             {Judul: "COB*"},
		"TREATY_TYPE":                     {Sembunyi: true},
		"POLICY_NUMBER":                   {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":              {Judul: "CERTIFICATE NUMBER"},
		"INSURED_NAME":                    {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":             {Judul: "INSURED AFFILIATION"},
		"POI_START":                       {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                         {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                         {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":              {Judul: "INSURABLE INTEREST"},
		"COVERAGE":                        {Judul: "Coverage (*)"},
		"TYPE_OF_CARGO":                   {Judul: "TYPE OF CARGO*"},
		"CARGO_DETAIL":                    {Judul: "CARGO DETAIL*"},
		"TRANSHIPMENT_TYPE":               {Judul: "TRANSHIPMENT TYPE"},
		"STANDARD_PACKAGING":              {Judul: "STANDARD PACKAGING"},
		"BILL_OF_LADDING":                 {Judul: "Bill Of Ladding/ Airway Bill Number"},
		"LAND_TRANSIT_VEHICLE_TYPE":       {Grup: "LAND TRANSIT", Judul: "VEHICLE TYPE*"},
		"LAND_TRANSIT_VEHICLE_LICENSED":   {Grup: "LAND TRANSIT", Judul: "VEHICLE LICENSED*"},
		"LAND_TRANSIT_BUILT_YEAR":         {Grup: "LAND TRANSIT", Judul: "BUILT YEAR*"},
		"SEA_TRANSIT_VESSEL_NAME":         {Grup: "SEA TRANSIT", Judul: "VESSEL NAME*"},
		"SEA_TRANSIT_VESSEL_TYPE":         {Grup: "SEA TRANSIT", Judul: "VESSEL TYPE*"},
		"SEA_TRANSIT_VESSEL_CONSTRUCTION": {Grup: "SEA TRANSIT", Judul: "VESSEL CONSTRUCTION*"},
		"SEA_TRANSIT_VESSEL_GT":           {Grup: "SEA TRANSIT", Judul: "VESSEL GT / SIZE"},
		"SEA_TRANSIT_VESSEL_CLASS":        {Grup: "SEA TRANSIT", Judul: "VESSEL CLASS*"},
		"SEA_TRANSIT_BUILT_YEAR":          {Grup: "SEA TRANSIT", Judul: "BUILT YEAR*"},
		"SEA_TRANSIT_LAST_DOCKING_DATE":   {Grup: "SEA TRANSIT", Judul: "LAST DOCKING DATE"},
		"AIR_TRANSIT_AIRLINES":            {Grup: "AIR TRANSIT", Judul: "AIRLINES*"},
		"AIR_TRANSIT_AIRCRAFT_REGISTERED": {Grup: "AIR TRANSIT", Judul: "AIRCRAFT REGISTERED*"},
		"SHIPMENT_FROM":                   {Grup: "SHIPMENT", Judul: "from*"},
		"SHIPMENT_TO":                     {Grup: "SHIPMENT", Judul: "to*"},
		"DEPARTURE_DATE":                  {Judul: "Departure/ Sailing Date*"},
		"ARRIVAL_DATE":                    {Judul: "Arrival Date*"},
		"ENDORSEMENT":                     {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_OF_EDM":           {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION1":                    {Judul: "Description"},
		"CURRENCY":                        {Judul: "CURRENCY*"},
		"SUM_INSURED":                     {Judul: "SUM INSURED (*)"},
		"CEDANT_SHARE_PCT":                {Grup: "CEDANT'S SHARE (*)", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":             {Grup: "CEDANT'S SHARE (*)", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANELS":              {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":               {Grup: "SPREADING OF RISK", Judul: "OR*"},
		"SPREAD_OF_RISK_QS":               {Grup: "SPREADING OF RISK", Judul: "QS*"},
		"SPREAD_OF_RISK_SURPLUS":          {Grup: "SPREADING OF RISK", Judul: "SURPLUS*"},
		"SPREAD_OF_RISK_OTHERS":           {Grup: "SPREADING OF RISK", Judul: "OTHERS*"},
		"PREMIUM_100":                     {Judul: "100% Premium"},
		"PREMIUM_RATE":                    {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":               {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                     {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":              {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                    {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                            {Judul: "NOTE"},
	},
	// Sheet `Hull Premi`.
	"premi.marine-hull": {
		"COB":                           {Judul: "COB*"},
		"TREATY_TYPE":                   {Sembunyi: true},
		"POLICY_NUMBER":                 {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":            {Judul: "CERTIFICATE NUMBER"},
		"INSURED_NAME":                  {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":           {Judul: "INSURED AFFILIATION"},
		"POI_START":                     {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                       {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                       {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":            {Judul: "INSURABLE INTEREST"},
		"SHIP_BUILDER_ADDRESS":          {Judul: "SHIP BUILDER ADDRESS (ONLY FOR BUILDER RISK)*"},
		"VESSEL_NAME":                   {Judul: "VESSEL NAME*"},
		"IMO_NUMBER":                    {Judul: "IMO NUMBER"},
		"FLAG":                          {Judul: "FLAG"},
		"VESSEL_TYPE":                   {Judul: "VESSEL TYPE*"},
		"JENIS_MUATAN":                  {Judul: "JENIS MUATAN*"},
		"VESSEL_CONSTRUCTION":           {Judul: "VESSEL CONSTRUCTION*"},
		"VESSEL_GT":                     {Judul: "VESSEL GT / SIZE (*)"},
		"VESSEL_CLASS":                  {Judul: "VESSEL CLASS*"},
		"BUILT_YEAR":                    {Judul: "BUILT YEAR*"},
		"LAST_DOCKING_DATE":             {Judul: "LAST DOCKING DATE"},
		"TRADING_AREA":                  {Judul: "TRADING AREA"},
		"COVERAGE":                      {Judul: "COVERAGE*"},
		"CURRENCY":                      {Judul: "CURRENCY*"},
		"SUM_INSURED":                   {Judul: "SUM INSURED (*)"},
		"LOL_PML_EML_AMOUNT":            {Judul: "* LOL / PML / EML (amount)"},
		"LIMIT_OF_LIABILITY":            {Judul: "LIMIT OF LIABILITY for P&I and SRL"},
		"ENDORSEMENT":                   {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EEFFECTIVE_DATE_EDM":           {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION1":                  {Judul: "Description"},
		"CEDANT_SHARE_PCT":              {Grup: "CEDANT'S SHARE*", Judul: "IN PERCENTAGE*"},
		"CEDANT_SHARE_AMOUNT":           {Grup: "CEDANT'S SHARE*", Judul: "IN AMOUNT*"},
		"TOTAL_COINS_PANELS":            {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":             {Grup: "SPREADING OF RISK", Judul: "OR*"},
		"SPREAD_OF_RISK_QS":             {Grup: "SPREADING OF RISK", Judul: "QS*"},
		"SPREAD_OF_RISK_SURPLUS":        {Grup: "SPREADING OF RISK", Judul: "SURPLUS*"},
		"SPREAD_OF_RISK_OTHERS":         {Grup: "SPREADING OF RISK", Judul: "OTHERS*"},
		"HULL_AND_MACHINERY_RATE_HM":    {Grup: "Hull and Machinery Rate*", Judul: "HM"},
		"HULL_AND_MACHINERY_RATE_IV":    {Grup: "Hull and Machinery Rate*", Judul: "IV"},
		"HULL_AND_MACHINERY_RATE_WAR":   {Grup: "Hull and Machinery Rate*", Judul: "WAR"},
		"BUILDER_RISK_RATE":             {Judul: "Builder Risk Rate"},
		"SHIP_REPAIR_LIABILITY_RATE":    {Judul: "Ship Repair Liability Rate"},
		"PROTECTION_AND_INDEMNITY_RATE": {Judul: "Protection and Indemnity Rate"},
		"PREMIUM_100":                   {Judul: "100% Premium"},
		"PREMIUM_REINSURER":             {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                   {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":            {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                  {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                          {Judul: "NOTE"},
	},
	// Sheet `MV Premi`.
	"premi.motor-vehicle": {
		"COB":                         {Judul: "COB*"},
		"TREATY_TYPE":                 {Sembunyi: true},
		"REINSURED":                   {Judul: "REINSURED*"},
		"POLICY_NUMBER":               {Judul: "POLICY NUMBER*"},
		"INSURED_NAME":                {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":         {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":   {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":     {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                     {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":          {Judul: "INSURABLE INTEREST"},
		"BANKER_CLAUSE":               {Judul: "BANKER CLAUSE"},
		"MV_BRAND":                    {Grup: "MOTOR VEHICLE", Judul: "BRAND"},
		"MV_TYPE_OF_MOTOR_VEHICLE":    {Grup: "MOTOR VEHICLE", Judul: "TYPE OF MOTOR VEHICLE"},
		"MV_OCCUPATION":               {Grup: "MOTOR VEHICLE", Judul: "OCCUPATION"},
		"MV_TYPE_OF_ENGINE_MOTOR":     {Grup: "MOTOR VEHICLE", Judul: "TYPE OF ENGINE MOTOR"},
		"MV_WILAYAH":                  {Grup: "MOTOR VEHICLE", Judul: "WILAYAH (CRESTA)"},
		"MV_YEAR_OF_BUILD":            {Grup: "MOTOR VEHICLE", Judul: "YEAR OF BUILT"},
		"MV_CATEGORIZATION":           {Grup: "MOTOR VEHICLE", Judul: "CATEGORIZATION\n(A / B /C)"},
		"MV_ENGINE_NUMBER":            {Grup: "MOTOR VEHICLE", Judul: "ENGINE NUMBER"},
		"MV_CHASSIS_NUMBER":           {Grup: "MOTOR VEHICLE", Judul: "CHASSIS NUMBER"},
		"MV_LISENCE_NUMBER":           {Grup: "MOTOR VEHICLE", Judul: "LISENCE NUMBER"},
		"HE_BRAND":                    {Grup: "HEAVY EQUIPMENT", Judul: "BRAND"},
		"HE_TYPE_OF_HE":               {Grup: "HEAVY EQUIPMENT", Judul: "TYPE OF HE"},
		"HE_OCCUPATION":               {Grup: "HEAVY EQUIPMENT", Judul: "OCCUPATION"},
		"HE_YEAR_OF_BUILD":            {Grup: "HEAVY EQUIPMENT", Judul: "YEAR OF BUILT"},
		"HE_ENGINE_NUMBER":            {Grup: "HEAVY EQUIPMENT", Judul: "ENGINE NUMBER"},
		"HE_CHASSIS_NUMBER":           {Grup: "HEAVY EQUIPMENT", Judul: "CHASSIS NUMBER"},
		"HE_LOCATION":                 {Judul: "LOCATION"},
		"HE_COVERAGE":                 {Judul: "COVERAGE*"},
		"CURRENCY":                    {Judul: "CURRENCY*"},
		"MV_SUM_INSURED":              {Grup: "MOTOR VEHICLE", Judul: "SUM INSURED"},
		"MV_TPL":                      {Grup: "MOTOR VEHICLE", Judul: "TPL - Limit"},
		"MV_PA_PENGEMUDI":             {Grup: "MOTOR VEHICLE", Judul: "PA Pengemudi - Limit"},
		"MV_PA_PENUMPANG":             {Grup: "MOTOR VEHICLE", Judul: "PA Penumpang - Limit/ penumpang"},
		"MV_PA_JUMLAH_PENUMPANG":      {Grup: "MOTOR VEHICLE", Judul: "PA - jumlah penumpang"},
		"HE_SUM_INSURED":              {Grup: "HEAVY EQUIPMENT", Judul: "SUM INSURED"},
		"HE_TPL":                      {Grup: "HEAVY EQUIPMENT", Judul: "TPL - Limit"},
		"ENDORSEMENT":                 {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":          {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION1":                {Judul: "Description"},
		"CEDANT_SHARE_PCT":            {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":         {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANEL":           {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":           {Grup: "SPREADING OF RISK", Judul: "OR*"},
		"SPREAD_OF_RISK_QS":           {Grup: "SPREADING OF RISK", Judul: "QS*"},
		"SPREAD_OF_RISK_SURPLUS":      {Grup: "SPREADING OF RISK", Judul: "SURPLUS*"},
		"SPREAD_OF_RISK_OTHERS":       {Grup: "SPREADING OF RISK", Judul: "OTHERS*"},
		"RATE_MV_JAMINAN_UTAMA":       {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Jaminan Utama (Kendaraan)"},
		"RATE_MV_LOADING_USIA":        {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Loading Usia"},
		"RATE_MV_BANJIR":              {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Banjir"},
		"RATE_MV_GEMPA_BUMI":          {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Gempa Bumi"},
		"RATE_MV_HURU_HARA":           {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Huru Hara"},
		"RATE_MV_TERORISME":           {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Terorisme"},
		"RATE_MV_AUTHORIZED_WORKSHOP": {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Authorized Workshop"},
		"RATE_MV_OTHERS":              {Grup: "RATE OF MOTOR VEHICLE (%)", Judul: "Others"},
		"RATA_HE_PREMIUM_RATE":        {Grup: "RATE OF HEAVY EQUIPMENT", Judul: "Premium Rate*"},
		"PREMIUM_100":                 {Judul: "100% Premium"},
		"PREMIUM_RATE":                {Judul: "Premium Rate"},
		"FIRST_LOSS_SCALE":            {Judul: "First Loss Scale"},
		"PREMIUM_REINSURER":           {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                 {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":          {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                        {Judul: "NOTE"},
	},
	// Sheet `Bond Premium`.
	"premi.bonding": {
		"COB":                           {Judul: "*COB"},
		"TREATY_TYPE":                   {Sembunyi: true},
		"TYPE_OF_BOND":                  {Judul: "TYPE OF BOND"},
		"POLICY_NUMBER":                 {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":            {Judul: "CERTIFICATE NUMBER"},
		"INSURED_NAME":                  {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":           {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":     {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":       {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                       {Judul: "*UW YEAR"},
		"PRINCIPAL":                     {Judul: "*PRINCIPAL"},
		"OBLIGEE":                       {Judul: "*OBLIGEE"},
		"BANK_PENERBIT":                 {Judul: "*Bank Penerbit"},
		"PROJECT_TITLE":                 {Judul: "*PROJECT TITLE"},
		"LOCATION":                      {Judul: "LOCATION"},
		"SOURCE_DIRECT_INWARD":          {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSMENENT":                  {Judul: "*ENDORSEMENT\n(YES/NO)"},
		"EFFECTIVE_DATE_OF_ENDORSEMENT": {Judul: "*Effective Date of Endorsement"},
		"DESCRIPTION":                   {Judul: "Description"},
		"CURRENCY":                      {Judul: "Currency"},
		"CONTRACT_VALUE":                {Judul: "CONTRACT VALUE"},
		"BOND_VALUE":                    {Judul: "BOND VALUE"},
		"COLLATERAL_DESCRIPTION":        {Grup: "*COLLATERAL", Judul: "DESCRIPTION"},
		"COLLATERAL_INAMOUNT":           {Grup: "*COLLATERAL", Judul: "IN AMOUNT"},
		"CEDANTS_SHARE_PCT":             {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":        {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_CO_INSURANCE_PANELS":     {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREADING_OF_RISK_OR":          {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREADING_OF_RISK_QS":          {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREADING_OF_RISK_SURPLUS":     {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREADING_OF_RISK_OTHERS":      {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":                   {Judul: "100% Premium"},
		"PREMIUM_RATE":                  {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":             {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                   {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":            {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION_2":                 {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                          {Judul: "NOTE"},
	},
	// Sheet `Liability Premi`.
	"premi.liability": {
		"COB":                           {Judul: "COB*"},
		"TREATY_TYPE":                   {Sembunyi: true},
		"POLICY_NUMBER":                 {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":            {Judul: "CERTIFICATE NUMBER"},
		"INSURED_NAME":                  {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":           {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":     {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":       {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                       {Judul: "*UW YEAR"},
		"POLICY_BASIS":                  {Judul: "*Policy Basis"},
		"TYPE_OF_POLICY":                {Judul: "*Type of Policy"},
		"PROJECT_TITLE":                 {Grup: "*if Type of Policy = \"Project Basis\"", Judul: "*Project Title"},
		"PRINCIPAL":                     {Grup: "*if Type of Policy = \"Project Basis\"", Judul: "*Principal"},
		"SCOPE_OF_WORK":                 {Grup: "*if Type of Policy = \"Project Basis\"", Judul: "*Scope of Work"},
		"CONTRACT_VALUE":                {Grup: "*if Type of Policy = \"Project Basis\"", Judul: "*Contract Value"},
		"OCCUPANCY":                     {Judul: "*Occupancy"},
		"OCCUPANCY_DETAIL":              {Judul: "Occupancy Detail"},
		"CURRENCY":                      {Judul: "CURRENCY"},
		"TSI_100":                       {Judul: "*100% TSI"},
		"LOCATION":                      {Judul: "*LOCATION"},
		"ZIP_CODE":                      {Judul: "*ZIP CODE"},
		"COORDINATES_LATITUDE":          {Grup: "COORDINATES", Judul: "Latitude"},
		"COORDINATES_LONGITUDE":         {Grup: "COORDINATES", Judul: "Longitude"},
		"SOURCE_DIRECT_INWARD":          {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":                   {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_OF_ENDORSEMENT": {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                   {Judul: "Description"},
		"CEDANTS_SHARE_PCT":             {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":        {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_CO_INSURANCE_PANEL":      {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREADING_OF_RISK_OR":          {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREADING_OF_RISK_QS":          {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREADING_OF_RISK_SURPLUS":     {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREADING_OF_RISK_OTHERS":      {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMI_100":                     {Judul: "100% Premium"},
		"PREMIUM_RATE":                  {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":             {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                   {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":            {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                  {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                          {Judul: "NOTE"},
	},
	// Sheet `PA Premi`.
	"premi.personal-accident": {
		"COB":                           {Judul: "*COB"},
		"TREATY_TYPE":                   {Sembunyi: true},
		"POLICY_NUMBER":                 {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":                  {Judul: "*INSURED NAME"},
		"CERTIFICATE_NUMBER":            {Judul: "CERTIFICATE NUMBER"},
		"NIK":                           {Judul: "*NIK"},
		"INSURED_AFFILIATION":           {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":     {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":       {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                       {Judul: "*UW YEAR"},
		"TYPE_OF_POLICY":                {Judul: "Type of Policy"},
		"TYPE_OF_COVER":                 {Judul: "Type of Cover"},
		"OCCUPANCY":                     {Judul: "Occupancy"},
		"OCCUPANCY_DETAIL":              {Judul: "Occupancy Detail"},
		"CURRENCY":                      {Judul: "Currency"},
		"LOL_100":                       {Judul: "*100% LOL"},
		"LOCATION":                      {Judul: "*LOCATION"},
		"ZIP_CODE":                      {Judul: "*ZIP CODE"},
		"COORDINATES_LATITUDE":          {Grup: "COORDINATES", Judul: "Latitude"},
		"COORDINATES_LONGITUDE":         {Grup: "COORDINATES", Judul: "Longitude"},
		"SOURCE_DIRECT_INWARD":          {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":                   {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_OF_ENDORSEMENT": {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                   {Judul: "Description"},
		"CEDANTS_SHARE_PCT":             {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":        {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_CO_INSURANCE_PANELS":     {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREADING_OF_RISK_OR":          {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREADING_OF_RISK_QS":          {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREADING_OF_RISK_SURPLUS":     {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREADING_OF_RISK_OTHERS":      {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":                   {Judul: "100% Premium"},
		"PREMIUM_RATE":                  {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":             {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                   {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":            {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                  {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                          {Judul: "NOTE"},
	},
	// Sheet `Offshore Premi`.
	"premi.offshore": {
		"COB":                                {Judul: "*COB"},
		"TREATY_TYPE":                        {Sembunyi: true},
		"POLICY_NUMBER":                      {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":                       {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":                {Judul: "INSURED AFFILIATION"},
		"POI_START":                          {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                            {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                            {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":                 {Judul: "INSURABLE INTEREST"},
		"TYPE_OF_RISK":                       {Judul: "*TYPE OF RISK"},
		"OFFSHOREASSET_NAME_OF_ASSET":        {Grup: "OFFSHORE ASSET", Judul: "NAME OF ASSET"},
		"OFFSHOREASSET_YEAR_OFBUILT":         {Grup: "OFFSHORE ASSET", Judul: "YEAR OF BUILT"},
		"OFFSHOREASSET_CLASSIFICATION":       {Grup: "OFFSHORE ASSET", Judul: "CLASSIFICATION"},
		"OFFSHOREASSET_COVERAGE":             {Grup: "OFFSHORE ASSET", Judul: "COVERAGE"},
		"OFFSHOREASSET_SCOPE_OF_COVERAGE":    {Grup: "OFFSHORE ASSET", Judul: "SCOPE OF COVERAGE"},
		"OFFSHORECONS_NAME_OF_PROJECT":       {Grup: "OFFSHORE CONSTRUCTION", Judul: "NAME OF PROJECT"},
		"OFFSHORECONS_COVERAGE":              {Grup: "OFFSHORE CONSTRUCTION", Judul: "COVERAGE"},
		"OFFSHORECONS_OCCUPATION_OF_PROJECT": {Grup: "OFFSHORE CONSTRUCTION", Judul: "OCCUPATION OF PROJECT"},
		"OFFSHORECONS_PROJECT_SUPERVISOR":    {Grup: "OFFSHORE CONSTRUCTION", Judul: "PROJECT SUPERVISOR"},
		"OFFSHORECONS_MAIN_SUB_CONTRACTOR":   {Grup: "OFFSHORE CONSTRUCTION", Judul: "MAIN / SUB CONTRACTOR"},
		"OFFSHORECONS_TYPE_OF_INSTALLATION":  {Grup: "OFFSHORE CONSTRUCTION", Judul: "TYPE OF INSTALLATION"},
		"LOCATION":                           {Judul: "*LOCATION"},
		"SOURCE":                             {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":                        {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":                 {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                        {Judul: "Description"},
		"CURRENCY":                           {Judul: "*CURRENCY"},
		"TSI_100":                            {Judul: "*100% TSI"},
		"CEDANT_SHARE_PCT":                   {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":                {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANEL":                  {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":                  {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":                  {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SURPLUS":             {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS":              {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":                        {Judul: "100% Premium"},
		"PREMIUM_RATE":                       {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":                  {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                        {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":                 {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                       {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                               {Judul: "NOTE"},
	},
	// Sheet `Credit Premi`.
	"premi.credit": {
		"COB":                         {Judul: "*COB"},
		"TREATY_TYPE":                 {Sembunyi: true},
		"TYPE_OF_CREDIT":              {Judul: "TYPE OF CREDIT"},
		"TERTANGGUNG":                 {Judul: "NAMA BANK / TERTANGGUNG"},
		"DEBITUR":                     {Judul: "INSURED NAME / DEBITUR"},
		"NO_SP":                       {Judul: "NO POLIS / NO SP"},
		"ID_TERJAMIN":                 {Judul: "ID TERJAMIN/UNIQUE IDENTIFIER"},
		"NAMA_PRODUK":                 {Judul: "NAMA PRODUK"},
		"UW_YEAR":                     {Judul: "UW YEAR"},
		"TGL_LAHIR":                   {Judul: "TGL LAHIR"},
		"JENIS_KELAMIN":               {Judul: "JENIS KELAMIN"},
		"JENIS_PEKERJAAN":             {Judul: "JENIS PEKERJAAN"},
		"TANGGAL_AKAD_KREDIT":         {Judul: "TANGGAL AKAD KREDIT"},
		"USIA_SAAT_AKAD":              {Judul: "USIA SAAT AKAD (TAHUN)"},
		"USIA_AKHIR_AKAD":             {Judul: "USIA AKHIR AKAD (TAHUN)"},
		"PERIOD_KREDIT_START":         {Grup: "PERIODE KREDIT", Judul: "MULAI"},
		"PERIOD_KREDIT_END":           {Grup: "PERIODE KREDIT", Judul: "BERKAHIR"},
		"TENOR":                       {Judul: "JANGKA WAKTU KREDIT/ TENOR\n(DALAM BULAN)"},
		"PERIODE_PERTANGGUNGAN_START": {Grup: "PERIODE PERTANGGUNGAN", Judul: "MULAI"},
		"PERIODE_PERTANGGUNGAN_END":   {Grup: "PERIODE PERTANGGUNGAN", Judul: "BERKAHIR"},
		"JANGKA_WAKTU_PERTANGGUNGAN":  {Judul: "JANGKA WAKTU PERTANGGUNGAN\n(DALAM BULAN)"},
		"LOKASI":                      {Judul: "LOKASI/ WILAYAH"},
		"NEW_EXTENDED_SUPLESI":        {Judul: "New or Extended or Suplesi"},
		"COLLECTABILITY":              {Judul: "COLLECTABILITY"},
		"PLAFOND":                     {Judul: "NILAI KREDIT/ PLAFOND"},
		"BANK_RETENTION":              {Judul: "BANK RETENTION (%)"},
		"NILAI_PERTANGGUNGAN":         {Judul: "NILAI PERTANGGUNGAN"},
		"ENDORSEMENT":                 {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":          {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                 {Judul: "Description"},
		"CEDANT_SHARE_PCT":            {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":         {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANEL":           {Judul: "TOTAL CO-INSURANCE PANELS"},
		"COLLATERAL":                  {Judul: "COLLATERAL"},
		"AGUNAN":                      {Judul: "AGUNAN"},
		"NILAI_AGUNAN":                {Judul: "NILAI AGUNAN"},
		"SPREAD_OF_RISK_OR":           {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":           {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SURPLUS":      {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS":       {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"IJP":                         {Judul: "IJP/PREMI ORIGINAL"},
		"TINGKAT_SUKU_BUNGA":          {Judul: "TINGKAT SUKU BUNGA (INTEREST RATE)"},
		"PREMIUM_REINSURER":           {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                 {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":          {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                        {Judul: "NOTE"},
	},
	// Sheet `Onshore Premi`.
	"premi.onshore": {
		"COB":                               {Judul: "*COB"},
		"TREATY_TYPE":                       {Sembunyi: true},
		"POLICY_NUMBER":                     {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":                      {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":               {Judul: "INSURED AFFILIATION"},
		"POI_START":                         {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                           {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                           {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":                {Judul: "INSURABLE INTEREST"},
		"TYPE_OF_RISK":                      {Judul: "*TYPE OF RISK"},
		"ONSHORE_ASSET_NAME_OF_ASSET":       {Grup: "ONSHORE ASSET", Judul: "NAME OF ASSET"},
		"ONSHORE_ASSET_YEAR_OF_BUILT":       {Grup: "ONSHORE ASSET", Judul: "YEAR OF BUILT"},
		"ONSHORE_ASSET_CLASSIFICATION":      {Grup: "ONSHORE ASSET", Judul: "CLASSIFICATION"},
		"ONSHORE_ASSET_COVERAGE":            {Grup: "ONSHORE ASSET", Judul: "COVERAGE"},
		"ONSHORE_ASSET_SCOPE_OF_COVERAGE":   {Grup: "ONSHORE ASSET", Judul: "SCOPE OF COVERAGE"},
		"ONSHORECONS_NAME_OF_PROJECT":       {Grup: "ONSHORE CONSTRUCTION", Judul: "NAME OF PROJECT"},
		"ONSHORECONS_COVERAGE":              {Grup: "ONSHORE CONSTRUCTION", Judul: "COVERAGE"},
		"ONSHORECONS_OCCUPATION_OF_PROJECT": {Grup: "ONSHORE CONSTRUCTION", Judul: "OCCUPATION OF PROJECT"},
		"ONSHORECONS_TYPE_OF_INSTALLATION":  {Grup: "ONSHORE CONSTRUCTION", Judul: "TYPE OF INSTALLATION"},
		"LOCATION":                          {Judul: "*LOCATION"},
		"SOURCE":                            {Judul: "SOURCE (DIRECT/INWARD)"},
		"RNW_NB_EDM":                        {Judul: "RENEWAL / NEW BUSINESS / ENDORSEMENT"},
		"LOL_PML_EML_AMOUNT":                {Judul: "* LOL / PML / EML (amount)"},
		"LOL_PML_EML_PCT":                   {Judul: "%LOL / PML / EML (Main Coverage)"},
		"ENDORSEMENT":                       {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":                {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                       {Judul: "Description"},
		"CURRENCY":                          {Judul: "*CURRENCY"},
		"TSI_100":                           {Judul: "*100% TSI"},
		"BASIS_OF_INDEMNITY":                {Judul: "*BASIS OF INDEMNITY"},
		"CEDANT_SHARE_PCT":                  {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":               {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANEL":                 {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":                 {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":                 {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SURPLUS":            {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS":             {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":                       {Judul: "100% Premium"},
		"PREMIUM_RATE":                      {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":                 {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                       {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":                {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                      {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                              {Judul: "NOTE"},
	},
	// Sheet `HIO Ins. Premium`.
	"premi.hole-in-one": {
		"COB":                        {Judul: "COB"},
		"TREATY_TYPE":                {Sembunyi: true},
		"POLICY_NUMBER":              {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":               {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":        {Judul: "INSURED AFFILIATION"},
		"POI_START":                  {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                    {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                    {Judul: "*UW YEAR"},
		"GOLF_COURSE_NAME":           {Judul: "GOLF COURSE NAME"},
		"EVENT_NAME":                 {Judul: "*EVENT'S NAME"},
		"EVENT_DATE":                 {Judul: "*EVENT'S DATE\n(DD/MM/YY)"},
		"LOCATION":                   {Judul: "*LOCATION"},
		"ZIP_CODE":                   {Judul: "*ZIP CODE"},
		"LATITUDE":                   {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                  {Grup: "COORDINATES", Judul: "Longitude"},
		"SOURCE":                     {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":                {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":         {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                {Judul: "Description"},
		"CURRENCY":                   {Judul: "*CURRENCY"},
		"TSI_100":                    {Judul: "*100% TSI"},
		"BREAK_OF_SI_GOODS":          {Grup: "BREAKDOWN OF SI", Judul: "GOODS (CAR, GADGET, ETC)"},
		"BREAK_OF_SI_1TS_PRIZE":      {Grup: "BREAKDOWN OF SI", Judul: "1ST PRIZE"},
		"BREAK_OF_SI_2ND_PRIZE":      {Grup: "BREAKDOWN OF SI", Judul: "2ND PRIZE"},
		"BREAK_OF_SI_OTHERS":         {Grup: "BREAKDOWN OF SI", Judul: "OTHER"},
		"INSURED_HOLE_HOLE":          {Grup: "*INSURED HOLE", Judul: "HOLE"},
		"INSURED_HOLE_HOLE_DISTANCE": {Grup: "*INSURED HOLE", Judul: "HOLE DISTANCE  FROM TEE (METER)"},
		"CEDANT_SHARE_PCT":           {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":        {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS_PANEL":          {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":          {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":          {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SURPLUS":     {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS":      {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"RATE_HOLE_DAY_GROSS_NET":    {Grup: "RATE/HOLE/DAY", Judul: "GROSS/NETT"},
		"RATE_HOLE_DAY_RATE":         {Grup: "RATE/HOLE/DAY", Judul: "RATE"},
		"FIRST_LOSS_SCALE":           {Judul: "First Loss Scale"},
		"PREMIUM_100":                {Judul: "100% Premium"},
		"PREMIUM_RATE":               {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":          {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":         {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":               {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                       {Judul: "NOTE"},
	},
	// Sheet `Aviation Premi`.
	"premi.aviation": {
		"COB":                                {Judul: "*COB"},
		"TREATY_TYPE":                        {Sembunyi: true},
		"POLICY_NUMBER":                      {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":                       {Judul: "*INSURED NAME"},
		"POI_START":                          {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                            {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                            {Judul: "*UW YEAR"},
		"TYPE_OF_COVERAGE":                   {Judul: "*TYPE OF COVERAGE"},
		"INSURED_AFFILIATION":                {Judul: "INSURED AFFILIATION"},
		"INSURABLE_INTEREST":                 {Judul: "INSURABLE INTEREST"},
		"OCCUPATION":                         {Judul: "*OCCUPATION"},
		"BANKER_CLAUSE":                      {Judul: "BANKER CLAUSE"},
		"AV_HULL_LIAB_REGIS_NUMBER":          {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Registered Number"},
		"AV_HULL_LIAB_TYPEOFAIRCRAFT":        {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Type of Aircraft"},
		"AV_HULL_LIAB_SERIESOFAIRCRAFT":      {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Series of Aircarft"},
		"AV_HULL_LIAB_YEAROFMANUFACTURER":    {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Year of Manufacturer"},
		"AV_HULL_LIAB_NUMBERSEATOFPASSANGER": {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Number seat of Passanger"},
		"AV_HULL_LIAB_TERRITORIALLIMIT":      {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Territorial Limit"},
		"AV_HULL_LIAB_CURRENCY":              {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "Currency"},
		"AV_HULL_LIAB_HULLAGREEDVALUE":       {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "HULL AGREED VALUE"},
		"AV_HULL_LIAB_HULLLIABILITY":         {Grup: "AVIATION HULL SPARE AND LIABILITY", Judul: "HULL LIABILITY (CSL)"},
		"AV_SERV_LIAB_NUMBEROFPREMISES":      {Grup: "AVIATION SERVICE LIABILITY", Judul: "Number of Premises"},
		"AV_SERV_LIAB_PREMISELOCATION":       {Grup: "AVIATION SERVICE LIABILITY", Judul: "Premise's location"},
		"AV_SERV_LIAB_INSUREDCLIENT":         {Grup: "AVIATION SERVICE LIABILITY", Judul: "Insured's client"},
		"AV_SERV_LIAB_CURRENCY":              {Grup: "AVIATION SERVICE LIABILITY", Judul: "Currency"},
		"AV_SERV_LIAB_LOL":                   {Grup: "AVIATION SERVICE LIABILITY", Judul: "Limit of Liability"},
		"AV_PA_LOL_NAMEOFCREW":               {Grup: "AVIATION PA AND LOL", Judul: "Name of Crew"},
		"AV_PA_LOL_CREWPOSITION":             {Grup: "AVIATION PA AND LOL", Judul: "Crew's Position"},
		"AV_PA_LOL_YEAROFBIRTH":              {Grup: "AVIATION PA AND LOL", Judul: "Year of birth"},
		"AV_PA_LOL_FLYINGHOURS":              {Grup: "AVIATION PA AND LOL", Judul: "Flying Hours"},
		"AV_PA_LOL_CURRENCY":                 {Grup: "AVIATION PA AND LOL", Judul: "Currency"},
		"AV_PA_LOL_INSUREDVALUEPERCREW":      {Grup: "AVIATION PA AND LOL", Judul: "Insured value per crew"},
		"LOCATION":                           {Judul: "*LOCATION"},
		"ZIPCODE":                            {Judul: "*ZIP CODE"},
		"LATITUDE":                           {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                          {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                           {Judul: "*CURRENCY"},
		"SOURCE":                             {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":                        {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":                 {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":                        {Judul: "Description"},
		"RNW_NEW_EDM":                        {Judul: "RENEWAL / NEW / ENDORSEMENT"},
		"CEDANT_SHARE_PCT":                   {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":                {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS":                        {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":                  {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":                  {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SPL":                 {Grup: "SPREADING OF RISK", Judul: "SPL"},
		"SPREAD_OF_RISK_OTHERS":              {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":                        {Judul: "100% Premium"},
		"PREMIUM_RATE":                       {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":                  {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":                        {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":                 {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":                       {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                               {Judul: "NOTE"},
	},
	// Sheet `Money Insurance Premium`.
	"premi.money-insurance": {
		"COB":                   {Judul: "*COB"},
		"TREATY_TYPE":           {Sembunyi: true},
		"POLICY_NUMBER":         {Judul: "*POLICY NUMBER"},
		"INSURED_NAME":          {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":   {Judul: "INSURED AFFILIATION"},
		"CERTIFICATE_NUMBER":    {Judul: "CERTIFICATE NUMBER"},
		"POI_START":             {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":               {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":               {Judul: "*UW YEAR"},
		"COVERAGE":              {Judul: "*COVERAGE"},
		"TYPE_OF_POLICY":        {Judul: "TYPE OF POLICY"},
		"CURRENCY":              {Judul: "*CURRENCY"},
		"TSI_100":               {Judul: "100% TSI"},
		"OCCUPANCY":             {Judul: "Occupancy"},
		"OCCUPANCY_DETAIL":      {Judul: "Occupancy Detail"},
		"RISK_LOCATION":         {Judul: "*RISK LOCATION/TERRITORY"},
		"ZIP_CODE":              {Judul: "*ZIP CODE"},
		"LATITUDE":              {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":             {Grup: "COORDINATES", Judul: "Longitude"},
		"SOURCE":                {Judul: "SOURCE (DIRECT/INWARD)"},
		"ENDORSEMENT":           {Judul: "*ENDORSEMENT (YES/ NO)"},
		"EFFECTIVE_DATE_EDM":    {Judul: "Effective Date of Endorsement"},
		"DESCRIPTION":           {Judul: "Description"},
		"CEDANT_SHARE_PCT":      {Grup: "CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":   {Grup: "CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"TOTAL_COINS":           {Judul: "TOTAL CO-INSURANCE PANELS"},
		"SPREAD_OF_RISK_OR":     {Grup: "SPREADING OF RISK", Judul: "OR"},
		"SPREAD_OF_RISK_QS":     {Grup: "SPREADING OF RISK", Judul: "QS"},
		"SPREAD_OF_RISK_SPL":    {Grup: "SPREADING OF RISK", Judul: "SURPLUS"},
		"SPREAD_OF_RISK_OTHERS": {Grup: "SPREADING OF RISK", Judul: "OTHERS"},
		"PREMIUM_100":           {Judul: "100% Premium"},
		"PREMIUM_RATE":          {Judul: "Premium Rate"},
		"PREMIUM_REINSURER":     {Judul: "Premium\n(Reinsurer Share)"},
		"PREMIUM_RNM":           {Judul: "Premium\n(Nusantara Re Share)"},
		"SPECIAL_ACCEPTANCE":    {Judul: "*SPECIAL ACCEPTANCE (YES / NO)"},
		"DESCRIPTION2":          {Judul: "Description (reason/ subjectivities)"},
		"NOTE":                  {Judul: "NOTE"},
	},
	// Sheet `Fire Claim`.
	"claim.fire": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "*CLAIM REFFERENCE NUMBER"},
		"POLICY_NO":                    {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NO":               {Judul: "CERTIFICATE NUMBER"},
		"REFFNO_OF_BORDEREAUX":         {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSUREDNAME":                  {Judul: "*INSURED NAME"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"OCCUPATION_CODE":              {Judul: "*OCCUPATION CODE"},
		"OCCUPATION":                   {Judul: "OCCUPATION"},
		"LOCATION":                     {Judul: "*LOCATION"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"DATE_OF_LOSS":                 {Judul: "*Date of Loss"},
		"SETTLED_DATE":                 {Judul: "*Settled Date"},
		"PROXIMATE_CAUSE":              {Judul: "*PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "*CAUSE OF LOSS"},
		"COVERAGE_AFFECTED":            {Judul: "*COVERAGE AFFECTED"},
		"CURRENCY":                     {Judul: "*CURR"},
		"CLAIM100_MD_BUILDING":         {Grup: "*CLAIM 100%", Judul: "MD/Building"},
		"CLAIM100_MACHINERY":           {Grup: "*CLAIM 100%", Judul: "Machinery"},
		"CLAIM100_STOCK":               {Grup: "*CLAIM 100%", Judul: "STOCK"},
		"CLAIM100_TPL":                 {Grup: "*CLAIM 100%", Judul: "TPL"},
		"CLAIM100_BI":                  {Grup: "*CLAIM 100%", Judul: "BI"},
		"CLAIM100_OTHER":               {Grup: "*CLAIM 100%", Judul: "OTHER"},
		"CLAIM100_ADJUSTER_FEE":        {Grup: "*CLAIM 100%", Judul: "Adjuster Fee"},
		"TOTAL_INCURRED_CLAIM":         {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "*SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "*SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "*SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "*SPREADING OF CLAIM", Judul: "OTHERS"},
		"TYPE_OF_LOSS":                 {Judul: "*TYPE OF LOSS (RISK / CAT)"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Eng Claim`.
	"claim.engineering": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "*CLAIM REFFERENCE NUMBER"},
		"POLICY_NUMBER":                {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFFNO_OF_BORDEREAUX":         {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSUREDNAME":                  {Judul: "*INSURED NAME"},
		"START_POI":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"END_POI":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"COVERAGE":                     {Judul: "*COVERAGE"},
		"POLICY_TYPE":                  {Judul: "*POLICY TYPE"},
		"LOCATION":                     {Judul: "*LOCATION"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"DATE_OF_LOSS":                 {Judul: "*DOL"},
		"SETTLED_DATE":                 {Judul: "*Settled Date"},
		"PROXIMATE_CAUSE":              {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "CAUSE OF LOSS"},
		"COVERAGE_AFFECTED":            {Judul: "COVERAGE AFFECTED"},
		"CURRENCY":                     {Judul: "*CURR"},
		"CLAIM100_MATERIAL_DAMEGE":     {Grup: "CLAIM 100%", Judul: "Material Damage"},
		"CLAIM100_DSU":                 {Grup: "CLAIM 100%", Judul: "DSU"},
		"CLAIM100_OTHERS":              {Grup: "CLAIM 100%", Judul: "Others"},
		"TOTAL_INCURRED_CLAIM100":      {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE":                {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_IN_AMOUNT":      {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPRD_CLAIM_OR":                {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPRD_CLAIM_QS":                {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPRD_CLAIM_SURPLUS":           {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPRD_CLAIM_OTHERS":            {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Cargo Claim`.
	"claim.marine-cargo": {
		"COB":                             {Judul: "COB*"},
		"TREATY_TYPE":                     {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":         {Judul: "*CLAIM REFFERENCE NUMBER"},
		"POLICY_NUMBER":                   {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":              {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_BORDEREAUX":              {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                    {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":             {Judul: "INSURED AFFILIATION"},
		"INSURABLE_INTEREST":              {Judul: "INSURABLE INTEREST"},
		"TYPE_OF_CARGO":                   {Judul: "TYPE OF CARGO*"},
		"CARGO_DETAIL":                    {Judul: "CARGO DETAIL*"},
		"TRANSHIPMENT_TYPE":               {Judul: "TRANSHIPMENT TYPE"},
		"STANDARD_PACKING":                {Judul: "STANDARD PACKAGING"},
		"BILL_OF_LADDING":                 {Judul: "Bill Of Ladding / Airway Bill Number"},
		"LAND_TRANSIT_VEHICLE_TYPE":       {Grup: "LAND TRANSIT", Judul: "VEHICLE TYPE*"},
		"LAND_TRANSIT_VEHICLE_LICENSED":   {Grup: "LAND TRANSIT", Judul: "VEHICLE LICENSED*"},
		"LAND_TRANSIT_BUILT_YEAR":         {Grup: "LAND TRANSIT", Judul: "BUILT YEAR*"},
		"SEA_TRANSIT_VESSEL_NAME":         {Grup: "SEA TRANSIT", Judul: "VESSEL NAME*"},
		"SEA_TRANSIT_VESSEL_TYPE":         {Grup: "SEA TRANSIT", Judul: "VESSEL TYPE*"},
		"SEA_TRANSIT_VESSEL_CONSTRUCTION": {Grup: "SEA TRANSIT", Judul: "VESSEL CONSTRUCTION*"},
		"SEA_TRANSIT_VESSEL_GT":           {Grup: "SEA TRANSIT", Judul: "VESSEL GT / SIZE"},
		"SEA_TRANSIT_VESSEL_CLASS":        {Grup: "SEA TRANSIT", Judul: "VESSEL CLASS*"},
		"SEA_TRANSIT_BUILT_YEAR":          {Grup: "SEA TRANSIT", Judul: "BUILT YEAR*"},
		"SEA_TRANSIT_LAST_DOCKING_DATE":   {Grup: "SEA TRANSIT", Judul: "LAST DOCKING DATE"},
		"AIR_TRANSIT_AIRLINES":            {Grup: "AIR TRANSIT", Judul: "AIRLINES*"},
		"AIR_TRANSIT_AIRCRAFT_REGISTERED": {Grup: "AIR TRANSIT", Judul: "AIRCRAFT REGISTERED*"},
		"SHIPMENT_FROM":                   {Grup: "SHIPMENT", Judul: "from*"},
		"SHIPMENT_TO":                     {Grup: "SHIPMENT", Judul: "to*"},
		"SAILING_DATE":                    {Judul: "Departure/ Sailing Date*"},
		"ARRIVAL_DATE":                    {Judul: "Arrival Date*"},
		"COVERAGE":                        {Judul: "COVERAGE*"},
		"DATE_OF_LOSS":                    {Judul: "DATE OF LOSS*"},
		"SETTLED_DATE":                    {Judul: "Settled Date (*)"},
		"LOSS_TYPE":                       {Judul: "LOSS TYPE*"},
		"PROXIMATE_CAUSE":                 {Judul: "PROXIMATE CAUSE*"},
		"CAUSE_OF_LOSS":                   {Judul: "CAUSE OF LOSS*"},
		"LOCATION_OF_LOSS":                {Judul: "LOCATION OF LOSS*"},
		"LATITUDE":                        {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                       {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                        {Judul: "CURRENCY*"},
		"CLAIM_100_CARGO_DAMAGE":          {Grup: "CLAIM 100%", Judul: "CARGO DAMAGE"},
		"CLAIM_100_SALVAGE":               {Grup: "CLAIM 100%", Judul: "SALVAGE"},
		"CLAIM_100_GENERAL_AVERAGE":       {Grup: "CLAIM 100%", Judul: "GENERAL AVERAGE"},
		"CLAIM_100_ADJUSTER_FEE":          {Grup: "CLAIM 100%", Judul: "ADJUSTER FEE"},
		"CLAIM_100_OTHERS":                {Grup: "CLAIM 100%", Judul: "OTHERS"},
		"TOTAL_INCURED_CLAIM_100":         {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":                {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":             {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREADING_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREADING_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIM_REINSURER":            {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIM_REINSURER":     {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIM_RNM":                  {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIM_RNM":           {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                            {Judul: "NOTE"},
	},
	// Sheet `Hull Claim`.
	"claim.marine-hull": {
		"COB":                         {Judul: "COB*"},
		"TREATY_TYPE":                 {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":     {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":               {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":          {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_BORDEREAUX":          {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":         {Judul: "INSURED AFFILIATION"},
		"INSURABLE_INTEREST":          {Judul: "INSURABLE INTEREST"},
		"SHIP_BUILDER_ADDRESS":        {Judul: "SHIP BUILDER ADDRESS (ONLY FOR BUILDER RISK)*"},
		"VESSEL_NAME":                 {Judul: "VESSEL NAME*"},
		"IMO_NUMBER":                  {Judul: "IMO NUMBER"},
		"FLAG":                        {Judul: "FLAG"},
		"VESSEL_TYPE":                 {Judul: "VESSEL TYPE*"},
		"JENIS_MUATAN":                {Judul: "JENIS MUATAN*"},
		"VESSEL_CONSTRUCTION":         {Judul: "VESSEL CONSTRUCTION*"},
		"VESSEL_GT":                   {Judul: "VESSEL GT / SIZE (*)"},
		"VESSEL_CLASS":                {Judul: "VESSEL CLASS*"},
		"BUILT_YEAR":                  {Judul: "BUILT YEAR*"},
		"LAST_DOCKING_DATE":           {Judul: "LAST DOCKING DATE"},
		"TRADING_AREA":                {Judul: "TRADING AREA"},
		"POI_START":                   {Grup: "PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                     {Grup: "PERIOD OF INSURANCE", Judul: "END"},
		"COVERAGE":                    {Judul: "COVERAGE*"},
		"DATE_OF_LOSS":                {Judul: "DATE OF LOSS*"},
		"SETTLED_DATE":                {Judul: "Settled Date"},
		"LOSS_TYPE":                   {Judul: "LOSS TYPE*"},
		"PROXIMATE_CAUSE":             {Judul: "PROXIMATE CAUSE (*)"},
		"CAUSE_OF_LOSS":               {Judul: "CAUSE OF LOSS (*)"},
		"JENIS_ENGINE_YANG_RUSAK":     {Judul: "JENIS ENGINE YANG RUSAK (For ENGINE DAMAGE)"},
		"NAMA_TUG_PENARIK":            {Judul: "NAMA TUG PENARIK (for BARGE)"},
		"POWER_TUG_PENARIK":           {Judul: "POWER TUG PENARIK (for BARGE)"},
		"SAILING_BERTHING_ANCHORING":  {Judul: "SAILING / BERTHING / ANCHORING"},
		"LOCATION_OF_LOSS":            {Judul: "*LOCATION OF LOSS"},
		"ZIP_CODE":                    {Judul: "*ZIP CODE"},
		"LATITUDE":                    {Grup: "COORDINATES (*)", Judul: "Latitude"},
		"LONGITUDE":                   {Grup: "COORDINATES (*)", Judul: "Longitude"},
		"CURRENCY":                    {Judul: "CURRENCY*"},
		"CLAIM_100_H_M_DAMAGE":        {Grup: "CLAIM 100%", Judul: "H&M DAMAGE"},
		"CLAIM_100_SALVAGE":           {Grup: "CLAIM 100%", Judul: "SALVAGE"},
		"CLAIM_100_GENERAL_AVERAGE":   {Grup: "CLAIM 100%", Judul: "GENERAL AVERAGE"},
		"CLAIM_100_ADJUSTER_FEE":      {Grup: "CLAIM 100%", Judul: "ADJUSTER FEE"},
		"CLAIM_100_OTHERS":            {Grup: "CLAIM 100%", Judul: "OTHERS"},
		"TOTAL_INCURRED_CLAIM_100":    {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":            {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":         {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":          {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":          {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":     {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":      {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIM_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIM_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIM_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIM_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                        {Judul: "NOTE"},
	},
	// Sheet `MV Claim`.
	"claim.motor-vehicle": {
		"COB":                          {Judul: "COB*"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFERENCE_NUMBER":       {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX":        {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":          {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":           {Judul: "INSURABLE INTEREST"},
		"TYPE_OF_MV_HE":                {Judul: "TYPE OF MV/ HE"},
		"BRAND":                        {Judul: "BRAND"},
		"LICENSE_NUMBER":               {Judul: "LICENSE NUMBER"},
		"ENGINE_NUMBER":                {Judul: "ENGINE NUMBER"},
		"CHASIS_NUMBER":                {Judul: "CHASIS NUMBER"},
		"COVERAGE":                     {Judul: "COVERAGE*"},
		"DATE_OF_LOSS":                 {Judul: "DATE OF LOSS*"},
		"SETTLED_DATE":                 {Judul: "Settled Date"},
		"LOSS_TYPE":                    {Judul: "LOSS TYPE*"},
		"TYPE_OF_LOSS_RISK_CAT":        {Judul: "*TYPE OF LOSS (RISK / CAT)"},
		"PROXIMATE_CAUSE":              {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "CAUSE OF LOSS"},
		"LOCATION_OF_LOSS":             {Judul: "LOCATION OF LOSS"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"COORDINATES_LATITUDE":         {Grup: "COORDINATES", Judul: "Latitude"},
		"COORDINATES_LONGITUDE":        {Grup: "COORDINATES", Judul: "Longitude"},
		"PARKING_DRIVE":                {Judul: "PARKING / DRIVE"},
		"CURRENCY":                     {Judul: "CURRENCY*"},
		"CLAIM100_MV_DAMAGE":           {Grup: "CLAIM 100%", Judul: "MV DAMAGE"},
		"CLAIM100_SALVAGE":             {Grup: "CLAIM 100%", Judul: "SALVAGE"},
		"CLAIM100_TPL":                 {Grup: "CLAIM 100%", Judul: "TPL"},
		"CLAIM100_ADJUSTER_FEE":        {Grup: "CLAIM 100%", Judul: "ADJUSTER FEE"},
		"CLAIM100_OTHERS":              {Grup: "CLAIM 100%", Judul: "OTHERS"},
		"TOTAL_INCURRED_CLAIM":         {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE_PCT":            {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_IN_AMOUNT":      {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_OR":        {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREADING_OF_CLAIM_QS":        {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREADING_OF_CLAIM_SURPLUS":   {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_OTHERS":    {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Bond Claim`.
	"claim.bonding": {
		"COB":                                   {Judul: "*COB"},
		"TREATY_TYPE":                           {Sembunyi: true},
		"TYPE_OF_BOND":                          {Judul: "TYPE OF BOND"},
		"CLAIM_REFFERENCE_NUMBER":               {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                         {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":                    {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX_PREMIUM_CESSION": {Judul: "*Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                          {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":                   {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":             {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":               {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                               {Judul: "*UW YEAR"},
		"PRINCIPAL":                             {Judul: "*PRINCIPAL"},
		"OBLIGEE":                               {Judul: "*OBLIGEE"},
		"PROJECT_TITLE":                         {Judul: "*PROJECT TITLE"},
		"CONTRACT_VALUE":                        {Judul: "*CONTRACT VALUE"},
		"BOND_VALUE":                            {Judul: "*BOND VALUE"},
		"DATE_OF_LOSS":                          {Judul: "*DATE OF LOSS"},
		"SETTLED_DATE":                          {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":                       {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                         {Judul: "*CAUSE OF LOSS"},
		"CURRENCY":                              {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":              {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE_PCT":                     {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_INAMOUNT":                      {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_OR":                 {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREADING_OF_CLAIM_QS":                 {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREADING_OF_CLAIM_SURPLUS":            {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_OTHERS":             {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":                 {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER":          {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":                       {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":                {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                                  {Judul: "NOTE"},
	},
	// Sheet `Liability Claim`.
	"claim.liability": {
		"COB":                                   {Judul: "COB*"},
		"TREATY_TYPE":                           {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":               {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                         {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":                    {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX_PREMIUM_CESSION": {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                          {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":                   {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":             {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":               {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                               {Judul: "*UW YEAR"},
		"COVERAGE_AFFECTED":                     {Judul: "COVERAGE AFFECTED"},
		"DATE_OF_LOSS":                          {Judul: "*DATE OF LOSS"},
		"SETTLED_DATE":                          {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":                       {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                         {Judul: "*CAUSE OF LOSS"},
		"LOCATION_OF_LOSS":                      {Judul: "LOCATION OF LOSS"},
		"ZIP_CODE":                              {Judul: "*ZIP CODE"},
		"COORDINATES_LATITUDE":                  {Grup: "COORDINATES", Judul: "Latitude"},
		"COORDINATES_LONGITUDE":                 {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                              {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":              {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE_PCT":                     {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":                {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_OR":                 {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREADING_OF_CLAIM_QS":                 {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREADING_OF_CLAIM_SURPLUS":            {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_OTHERS":             {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":                 {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER":          {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":                       {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":                {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                                  {Judul: "NOTE"},
	},
	// Sheet `PA Claim`.
	"claim.personal-accident": {
		"COB":                                   {Judul: "COB*"},
		"TREATY_TYPE":                           {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":               {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                         {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":                    {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX_PREMIUM_CESSION": {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                          {Judul: "INSURED NAME*"},
		"NIK":                                   {Judul: "*NIK"},
		"INSURED_AFFILIATION":                   {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":             {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":               {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                               {Judul: "*UW YEAR"},
		"DATE_OF_LOSS":                          {Judul: "DATE OF LOSS*"},
		"SETTLED_DATE":                          {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":                       {Judul: "PROXIMATE CAUSE"},
		"CASUE_OF_LOSS":                         {Judul: "*CASUE OF LOSS"},
		"LOCATION_OF_LOSS":                      {Judul: "*LOCATION OF LOSS"},
		"ZIP_CODE":                              {Judul: "*ZIP CODE"},
		"COORDINATES_LATITUDE":                  {Grup: "COORDINATES", Judul: "Latitude"},
		"COORDINATES_LONGITUDE":                 {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                              {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":              {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE_PCT":                     {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":                {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_OR":                 {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREADING_OF_CLAIM_QS":                 {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREADING_OF_CLAIM_SURPLUS":            {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_OTHERS":             {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":                 {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER":          {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":                       {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":                {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                                  {Judul: "NOTE"},
	},
	// Sheet `Offshore Claim`.
	"claim.offshore": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX":        {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "*INSURED NAME"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"TYPE_OF_RISK":                 {Judul: "*TYPE OF RISK"},
		"INSURABLE_INTEREST":           {Judul: "INSURABLE INTEREST"},
		"LOCATION":                     {Judul: "*LOCATION"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"DATE_OF_LOSS":                 {Judul: "*DOL"},
		"SETTLED_DATE":                 {Judul: "SETTLED DATE"},
		"EQUIPMENT":                    {Judul: "EQUIPMENT / PART of LOSS"},
		"PROXIMATE_CAUSE":              {Judul: "*PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "CAUSE OF LOSS"},
		"TYPE_OF_LOSS":                 {Judul: "TYPE OF LOSS"},
		"CURRENCY":                     {Judul: "*CURR"},
		"CLAIM_100_MD":                 {Grup: "CLAIM 100%", Judul: "MD"},
		"CLAIM_100_TPL":                {Grup: "CLAIM 100%", Judul: "TPL"},
		"CLAIM_100_ADJUSTER_FEE":       {Grup: "CLAIM 100%", Judul: "Adjuster Fee"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Credit Claim`.
	"claim.credit": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX":        {Judul: "Reff No of Bordereaux (premium cession)"},
		"TERTANGGUNG":                  {Judul: "NAMA BANK / TERTANGGUNG"},
		"DEBITUR":                      {Judul: "*INSURED NAME / DEBITUR"},
		"NAMA_PRODUK":                  {Judul: "NAMA PRODUK"},
		"PLAFOND":                      {Judul: "NILAI KREDIT/ PLAFOND"},
		"NILAI_PERTANGGUNGAN":          {Judul: "NILAI PERTANGGUNGAN"},
		"PERIODE_KREDIT_START":         {Grup: "PERIODE KREDIT", Judul: "START"},
		"PERIODE_KREDIT_END":           {Grup: "PERIODE KREDIT", Judul: "END"},
		"TENOR":                        {Judul: "JANGKA WAKTU KREDIT/ TENOR\n(DALAM BULAN)"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"JANGKA_WAKTU_PERTANGGUNGAN":   {Judul: "JANGKA WAKTU PERTANGGUNGAN\n(DALAM BULAN)"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"DATE_OF_LOSS":                 {Judul: "DATE OF LOSS"},
		"SETTLED_DATE":                 {Judul: "SETTLED DATE"},
		"TANGGAL_PELAPORAN_KLAIM":      {Judul: "TANGGAL PELAPORAN KLAIM"},
		"KOLEKTIBILITAS":               {Judul: "KOLEKTIBILITAS"},
		"CAUSE_OF_LOSS":                {Judul: "*CAUSE OF LOSS"},
		"CURRENCY":                     {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Onshore Claim`.
	"claim.onshore": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_BORDEREAUX":           {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":          {Judul: "INSURED AFFILIATION"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"INSURABLE_INTEREST":           {Judul: "INSURABLE INTEREST"},
		"TYPE_OF_RISK":                 {Judul: "*TYPE OF RISK"},
		"DATE_OF_LOSS":                 {Judul: "*Date of Loss"},
		"SETTLED_DATE":                 {Judul: "SETTLED DATE"},
		"LOSS_TYPE":                    {Judul: "*Loss type"},
		"PROXIMATE_CAUSE":              {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "CAUSE OF LOSS"},
		"LOCATION_OF_LOSS":             {Judul: "LOCATION OF LOSS"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                     {Judul: "*CURR"},
		"CLAIM_100_MD":                 {Grup: "CLAIM 100%", Judul: "MD"},
		"CLAIM_100_TPL":                {Grup: "CLAIM 100%", Judul: "TPL"},
		"CLAIM_100_ADJUSTER_FEE":       {Grup: "CLAIM 100%", Judul: "Adjuster Fee"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `HIO Ins. Claim`.
	"claim.hole-in-one": {
		"COB":                          {Judul: "COB*"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "POLICY NUMBER*"},
		"REFF_NO_BORDEREAUX":           {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":          {Judul: "INSURED AFFILIATION"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"GOLF_COURSE_NAME":             {Judul: "*GOLF COURSE NAME"},
		"EVENT_NAME":                   {Judul: "*EVENT'S NAME"},
		"EVENT_DATE":                   {Judul: "*EVENT'S DATE\n(DD/MM/YY)"},
		"DATE_OF_LOSS":                 {Judul: "*DOL"},
		"SETTLED_DATE":                 {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":              {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "**CAUSE OF LOSS"},
		"LOCATION_OF_LOSS":             {Judul: "*LOCATION OF LOSS"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                     {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Aviation Claim`.
	"claim.aviation": {
		"COB":                          {Judul: "*COB"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "*CLAIM REFFERENCE NUMBER"},
		"POLICY_NUMBER":                {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_BORDEREAUX":           {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "*INSURED NAME"},
		"POI_START":                    {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"POI_END":                      {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"TYPE_OF_COVERAGE":             {Judul: "*TYPE OF COVERAGE"},
		"INSURABLE_INTEREST":           {Judul: "INSURABLE INTEREST"},
		"AV_HULL_LIAB_REGISTERNUMBER":  {Grup: "AVIATION HULL SPARE LIABILITY", Judul: "Registered Number"},
		"AV_HULL_LIAB_TYPEOFAIRCRAFT":  {Grup: "AVIATION HULL SPARE LIABILITY", Judul: "Type of Aircraft"},
		"AV_PREMISE_LOCATION":          {Grup: "AVIATION SERVICE LIABILITY", Judul: "Premise's location"},
		"AV_PA_LOL_NAMEOFCREW":         {Grup: "AVIATION PA LOL", Judul: "Name of Crew"},
		"AV_PA_LOL_CREWPOSITION":       {Grup: "AVIATION PA LOL", Judul: "Crew's Position"},
		"LOCATION":                     {Judul: "*LOCATION"},
		"ZIPCODE":                      {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"DOL":                          {Judul: "*DOL"},
		"SETTLED_DATE":                 {Judul: "Settled Date"},
		"PROXIMATE_CAUSE":              {Judul: "*PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "CAUSE OF LOSS"},
		"TYPE_OF_LOSS":                 {Judul: "TYPE OF LOSS"},
		"CURRENCY":                     {Judul: "*CURR"},
		"CLAIM_100_HULL":               {Grup: "CLAIM 100%", Judul: "HULL"},
		"CLAIM_100_LIABILITY":          {Grup: "CLAIM 100%", Judul: "LIABILITY"},
		"CLAIM_100_ADJUSTERFEE":        {Grup: "CLAIM 100%", Judul: "Adjuster Fee"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "*SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "*SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "*SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Money Insurance Claim`.
	"claim.money-insurance": {
		"COB":                          {Judul: "COB*"},
		"TREATY_TYPE":                  {Sembunyi: true},
		"CLAIM_REFFERENCE_NUMBER":      {Judul: "CLAIM REFFERENCE NUMBER*"},
		"POLICY_NUMBER":                {Judul: "POLICY NUMBER*"},
		"CERTIFICATE_NUMBER":           {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_BORDEREAUX":           {Judul: "Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                 {Judul: "INSURED NAME*"},
		"INSURED_AFFILIATION":          {Judul: "INSURED AFFILIATION"},
		"PERIOD_START":                 {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_END":                   {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                      {Judul: "*UW YEAR"},
		"OCCUPANCY":                    {Judul: "Occupancy"},
		"OCCUPANCY_DETAIL":             {Judul: "Occupancy Detail"},
		"COVERAGE_AFFECTED":            {Judul: "COVERAGE AFFECTED"},
		"DOL":                          {Judul: "DATE OF LOSS*"},
		"SETTLED_DATE":                 {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":              {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                {Judul: "*CAUSE OF LOSS"},
		"LOCATION_OF_LOSS":             {Judul: "*LOCATION OF LOSS"},
		"ZIP_CODE":                     {Judul: "*ZIP CODE"},
		"LATITUDE":                     {Grup: "COORDINATES", Judul: "Latitude"},
		"LONGITUDE":                    {Grup: "COORDINATES", Judul: "Longitude"},
		"CURRENCY":                     {Judul: "CURRENCY*"},
		"TOTAL_INCURRED_CLAIM_100":     {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANT_SHARE_PCT":             {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANT_SHARE_AMOUNT":          {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREAD_OF_CLAIM_OR":           {Grup: "SPREADING OF CLAIM", Judul: "OR"},
		"SPREAD_OF_CLAIM_QS":           {Grup: "SPREADING OF CLAIM", Judul: "QS"},
		"SPREAD_OF_CLAIM_SURPLUS":      {Grup: "SPREADING OF CLAIM", Judul: "SURPLUS"},
		"SPREAD_OF_CLAIM_OTHERS":       {Grup: "SPREADING OF CLAIM", Judul: "OTHERS"},
		"PAID_CLAIMS_REINSURER":        {Judul: "*Paid Claims\n(Reinsurer Share)"},
		"OUTSTANDING_CLAIMS_REINSURER": {Judul: "Outstanding Claims\n(Reinsurer Share)"},
		"PAID_CLAIMS_RNM":              {Judul: "*Paid Claims\n(Nusantara Re Share)"},
		"OUTSTANDING_CLAIMS_RNM":       {Judul: "Outstanding Claims\n(Nusantara Re Share)"},
		"NOTE":                         {Judul: "NOTE"},
	},
	// Sheet `Bond Subrogation`.
	"subrogation.bonding": {
		"COB":                                    {Judul: "*COB"},
		"TREATY_TYPE":                            {Sembunyi: true},
		"TYPE_OF_BOND":                           {Judul: "*TYPE OF BOND"},
		"CLAIM_REFFERENCE_NUMBER":                {Judul: "*CLAIM REFFERENCE NUMBER"},
		"POLICY_NUMBER":                          {Judul: "*POLICY NUMBER"},
		"CERTIFICATE_NUMBER":                     {Judul: "CERTIFICATE NUMBER"},
		"REFF_NO_OF_BORDEREAUX_PREMIUM_CESSION":  {Judul: "*Reff No of Bordereaux (premium cession)"},
		"INSURED_NAME":                           {Judul: "*INSURED NAME"},
		"INSURED_AFFILIATION":                    {Judul: "INSURED AFFILIATION"},
		"PERIOD_OF_INSURANCE_START":              {Grup: "*PERIOD OF INSURANCE", Judul: "START"},
		"PERIOD_OF_INSURANCE_END":                {Grup: "*PERIOD OF INSURANCE", Judul: "END"},
		"UW_YEAR":                                {Judul: "*UW YEAR"},
		"PRINCIPAL":                              {Judul: "*PRINCIPAL"},
		"OBLIGAEE":                               {Judul: "*OBLIGEE"},
		"PROJECT_TITLE":                          {Judul: "*PROJECT TITLE"},
		"CONTRACT_VALUE":                         {Judul: "*CONTRACT VALUE"},
		"BOND_VALUE":                             {Judul: "*BOND VALUE"},
		"DATE_OF_LOSS":                           {Judul: "*DATE OF LOSS"},
		"SETTLED_DATE":                           {Judul: "SETTLED DATE"},
		"PROXIMATE_CAUSE":                        {Judul: "PROXIMATE CAUSE"},
		"CAUSE_OF_LOSS":                          {Judul: "*CAUSE OF LOSS"},
		"CURRENCY":                               {Judul: "*CURRENCY"},
		"TOTAL_INCURRED_CLAIM_100":               {Judul: "*TOTAL INCURRED CLAIM 100%"},
		"CEDANTS_SHARE_PCT":                      {Grup: "*CEDANT'S SHARE", Judul: "%"},
		"CEDANTS_SHARE_INAMOUNT":                 {Grup: "*CEDANT'S SHARE", Judul: "IN AMOUNT"},
		"SPREADING_OF_CLAIM_SUBROGATION_OR":      {Grup: "*SPREADING OF CLAIM SUBROGATION", Judul: "OR"},
		"SPREADING_OF_CLAIM_SUBROGATION_QS":      {Grup: "*SPREADING OF CLAIM SUBROGATION", Judul: "QS"},
		"SPREADING_OF_CLAIM_SUBROGATION_SURPLUS": {Grup: "*SPREADING OF CLAIM SUBROGATION", Judul: "SURPLUS"},
		"SPREADING_OF_CLAIM_SUBROGATION_OTHERS":  {Grup: "*SPREADING OF CLAIM SUBROGATION", Judul: "OTHERS"},
		"PAID_CLAIMS_SUBROGATION_REINSURER":      {Judul: "*Paid Claims Subrogation\n(Reinsurer Share)"},
		"PAID_CLAIMS_SUBROGATION_RNM":            {Judul: "*Paid Claims Subrogation\n(Nusantara Re's Share)"},
		"NOTE":                                   {Judul: "NOTE"},
	},
}
