-- 321 - T_POLIS_QUOTATION: halaman Quotation polis, 1:1 dengan T_GENERAL_POLIS
-- (spec-penyimpanan ID-23; tiket 19 AC 27). Kunci utama = POLIS_ID.
CREATE TABLE {skema}.T_POLIS_QUOTATION (
  POLIS_ID            VARCHAR2(32) NOT NULL,
  PROPORTIONAL_TYPE   VARCHAR2(32),
  MO_ID               VARCHAR2(64),
  BUSINESS_CODE       VARCHAR2(64),
  BUSINESS_OLD_ID     VARCHAR2(16),
  GROUP_PANEL         VARCHAR2(16),
  SOURCE_OF_BUSINESS  VARCHAR2(64),
  TYPE                VARCHAR2(64),
  EDM_TYPE            VARCHAR2(16),
  OLD_POLICY_NO       VARCHAR2(64),
  MARKETING_NAME      VARCHAR2(255),
  BUSINESS_NAME       VARCHAR2(255),
  BUSINESS_FAC        VARCHAR2(16),
  INSURED_ID          VARCHAR2(64),
  INSURED_NAME        VARCHAR2(255),
  NO_OFFER_SLIP       VARCHAR2(4000),
  IS_SURVEY_REPORT    VARCHAR2(16),
  CONSTRAINT PK_POLIS_QUOTATION PRIMARY KEY (POLIS_ID),
  CONSTRAINT FK_POLIS_QUOTATION_POLIS FOREIGN KEY (POLIS_ID) REFERENCES {skema}.T_GENERAL_POLIS (ID)
)
/
