-- 323 - T_POLIS_INSTALMENT <- PolicyTreatyIn.ListInstallment (ID-26).
-- NOURUT = nomor urut baris di dalam induknya, unik per induk (ID-11, AC 8, 10);
-- kunci pasangan antar generasi, bukan kunci dagang (ID-13, AC 11).
CREATE TABLE {skema}.T_POLIS_INSTALMENT (
  ID                       VARCHAR2(32) NOT NULL,
  POLIS_ID                 VARCHAR2(32) NOT NULL,
  NOURUT                   NUMBER(5) NOT NULL,
  INSTALLMENT_NO           NUMBER(10),
  DUE_DATE                 DATE,
  INSTALLMENT_PERCENTAGE   NUMBER(38,10),
  PREMIUM                  NUMBER(38,10),
  PAYMENT_TOTAL            NUMBER(38,10),
  PREMIUM_AFTER_PPH        NUMBER(38,10),
  PREMIUM_AFTER_PPN        NUMBER(38,10),
  PREMIUM_AFTER_TAX        NUMBER(38,10),
  CURRENCY                 VARCHAR2(16),
  ID_CURRENCY              VARCHAR2(64),
  PPN                      NUMBER(38,10),
  PPH                      NUMBER(38,10),
  PAYMENT_TOTAL_AFTER_PPN  NUMBER(38,10),
  PAYMENT_TOTAL_AFTER_TAX  NUMBER(38,10),
  CONSTRAINT PK_POLIS_INSTALMENT PRIMARY KEY (ID),
  CONSTRAINT FK_POLIS_INSTALMENT_POLIS FOREIGN KEY (POLIS_ID) REFERENCES {skema}.T_GENERAL_POLIS_TREATY (ID),
  CONSTRAINT UQ_POLIS_INSTALMENT_NOURUT UNIQUE (POLIS_ID, NOURUT)
)
/
