-- Mundur 870 - kolom IS_ACTIVE dibuang beserta isinya; untuk skema uji.
--
-- NOL COMMIT (ADR-U-0029).
ALTER TABLE {skema}.ADJUSTERCONSULTANT DROP CONSTRAINT CK_ADJUSTERCONSULTANT_ACTIVE
/
ALTER TABLE {skema}.ADJUSTERCONSULTANT DROP (IS_ACTIVE)
/
