-- Jalur mundur untuk 415_sequences_anak.sql
--
-- Dijalankan MENURUN: langkah bernomor besar dibongkar lebih dulu, supaya
-- anak hilang sebelum induknya.
DROP SEQUENCE {skema}.SEQ_TRIN_MATA_UANG_KONTRAK
/
DROP SEQUENCE {skema}.SEQ_TRIN_RETENSI_CEDANT
/
DROP SEQUENCE {skema}.SEQ_TRIN_EGNPI
/
DROP SEQUENCE {skema}.SEQ_TRIN_PORTOFOLIO
/
DROP SEQUENCE {skema}.SEQ_TRIN_PERIODE_PELAPORAN
/
DROP SEQUENCE {skema}.SEQ_TRIN_PERIODE_AKUMULASI
/
DROP SEQUENCE {skema}.SEQ_TRIN_TERMIN
/
DROP SEQUENCE {skema}.SEQ_TRIN_SKALA_KOASURANSI
/
DROP SEQUENCE {skema}.SEQ_TRIN_BATAS_PER_BAHAYA
/
DROP SEQUENCE {skema}.SEQ_TRIN_DOKUMEN_KONTRAK
/
DROP SEQUENCE {skema}.SEQ_TRIN_LAYER
/
DROP SEQUENCE {skema}.SEQ_TRIN_NILAI_MDP
/
DROP SEQUENCE {skema}.SEQ_TRIN_NILAI_MDP_MINIMUM
/
DROP SEQUENCE {skema}.SEQ_TRIN_PEMULIHAN_LIMIT
/
DROP SEQUENCE {skema}.SEQ_TRIN_JEJAK_PERUBAHAN
/
