-- Perilaku hapus menurut ERD.md §2 — migrasi KOREKTIF
--
-- Migrasi tiket 14, 20, 22-31, 33, 34, 37 Treaty In. Satu berkas = satu langkah.
-- Pernyataan dipisahkan oleh baris yang hanya berisi tanda garis miring.
--
-- ⚠️ KENAPA KOREKTIF, BUKAN SUNTINGAN DI TEMPAT
--
-- Ronde sebelumnya menyunting ke-21 kunci asing langsung di migrasi 400-419,
-- dengan alasan tertulis bahwa POOLDATA akan dibersihkan sehingga sejarah
-- T_MIGRASI di sana ikut terbuang. Pemilik proses kemudian menyatakan POOLDATA
-- adalah SKEMA SASARAN - ia tidak dibersihkan dan tidak diganti.
--
-- Dengan begitu suntingan di tempat membuat berkas migrasi MENYIMPANG dari yang
-- tercatat di T_MIGRASI: tiap pemasangan baru akan membaca berkas yang berbeda
-- dari yang pernah dijalankan. Syarat pembalikan yang ditulis sendiri di
-- KEPUTUSAN-PENYELARASAN-REPO.md §9 karena itu kepicu, dan berkas ini adalah
-- pembalikannya.
--
-- ⛔ SEPASANG DROP + ADD, bukan satu ALTER: Oracle TIDAK dapat mengubah aturan
-- hapus sebuah kunci asing yang sudah berdiri. Satu-satunya jalan membongkarnya
-- lalu membuatnya kembali.
--
-- ⛔ INDEX TIDAK IKUT DIBONGKAR. Index kunci asing dibuat terpisah di migrasi
-- aslinya dan tidak bergantung pada constraint-nya.
--
-- Sumber tiap baris: `4-erd-dan-tabel-datar/ERD.md` §2 - dokumen MENGIKAT.
-- Penjelasan INV-18 tetap di migrasi aslinya; yang pindah klausa DDL-nya saja.

-- FK_MATA_UANG_KONTRAK_1: VERSI_KONTRAK 1--< MATA_UANG_KONTRAK [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.MATA_UANG_KONTRAK DROP CONSTRAINT FK_MATA_UANG_KONTRAK_1
/
ALTER TABLE {skema}.MATA_UANG_KONTRAK ADD CONSTRAINT FK_MATA_UANG_KONTRAK_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_RETENSI_CEDANT_1: VERSI_KONTRAK 1--< RETENSI_CEDANT [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.RETENSI_CEDANT DROP CONSTRAINT FK_RETENSI_CEDANT_1
/
ALTER TABLE {skema}.RETENSI_CEDANT ADD CONSTRAINT FK_RETENSI_CEDANT_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_EGNPI_1: VERSI_KONTRAK 1--< EGNPI [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.EGNPI DROP CONSTRAINT FK_EGNPI_1
/
ALTER TABLE {skema}.EGNPI ADD CONSTRAINT FK_EGNPI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_PORTOFOLIO_1: VERSI_KONTRAK 1--< PORTOFOLIO [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.PORTOFOLIO DROP CONSTRAINT FK_PORTOFOLIO_1
/
ALTER TABLE {skema}.PORTOFOLIO ADD CONSTRAINT FK_PORTOFOLIO_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_PERIODE_PELAPORAN_1: VERSI_KONTRAK 1--< PERIODE_PELAPORAN [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.PERIODE_PELAPORAN DROP CONSTRAINT FK_PERIODE_PELAPORAN_1
/
ALTER TABLE {skema}.PERIODE_PELAPORAN ADD CONSTRAINT FK_PERIODE_PELAPORAN_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_PERIODE_AKUMULASI_1: VERSI_KONTRAK 1--< PERIODE_AKUMULASI [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.PERIODE_AKUMULASI DROP CONSTRAINT FK_PERIODE_AKUMULASI_1
/
ALTER TABLE {skema}.PERIODE_AKUMULASI ADD CONSTRAINT FK_PERIODE_AKUMULASI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_TERMIN_1: VERSI_KONTRAK 1--< TERMIN [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.TERMIN DROP CONSTRAINT FK_TERMIN_1
/
ALTER TABLE {skema}.TERMIN ADD CONSTRAINT FK_TERMIN_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_SKALA_KOASURANSI_1: VERSI_KONTRAK 1--< SKALA_KOASURANSI [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.SKALA_KOASURANSI DROP CONSTRAINT FK_SKALA_KOASURANSI_1
/
ALTER TABLE {skema}.SKALA_KOASURANSI ADD CONSTRAINT FK_SKALA_KOASURANSI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_BATAS_PER_BAHAYA_1: VERSI_KONTRAK 1--< BATAS_PER_BAHAYA [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.BATAS_PER_BAHAYA DROP CONSTRAINT FK_BATAS_PER_BAHAYA_1
/
ALTER TABLE {skema}.BATAS_PER_BAHAYA ADD CONSTRAINT FK_BATAS_PER_BAHAYA_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_DOKUMEN_KONTRAK_1: VERSI_KONTRAK 1--< DOKUMEN_KONTRAK [hapus: ikut hapus] - ERD.md §2.3
ALTER TABLE {skema}.DOKUMEN_KONTRAK DROP CONSTRAINT FK_DOKUMEN_KONTRAK_1
/
ALTER TABLE {skema}.DOKUMEN_KONTRAK ADD CONSTRAINT FK_DOKUMEN_KONTRAK_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_LAYER_1: VERSI_KONTRAK 1--< LAYER [hapus: ikut hapus] - ERD.md §2.4
ALTER TABLE {skema}.LAYER DROP CONSTRAINT FK_LAYER_1
/
ALTER TABLE {skema}.LAYER ADD CONSTRAINT FK_LAYER_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK) ON DELETE CASCADE
/
-- FK_DETAIL_PROPORSIONAL_1: LAYER 1--< DETAIL_PROPORSIONAL [hapus: ikut hapus] - ERD.md §2.4
ALTER TABLE {skema}.DETAIL_PROPORSIONAL DROP CONSTRAINT FK_DETAIL_PROPORSIONAL_1
/
ALTER TABLE {skema}.DETAIL_PROPORSIONAL ADD CONSTRAINT FK_DETAIL_PROPORSIONAL_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER) ON DELETE CASCADE
/
-- FK_BAGIAN_1: LAYER 1--< BAGIAN [hapus: ikut hapus] - ERD.md §2.4
ALTER TABLE {skema}.BAGIAN DROP CONSTRAINT FK_BAGIAN_1
/
ALTER TABLE {skema}.BAGIAN ADD CONSTRAINT FK_BAGIAN_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER) ON DELETE CASCADE
/
-- FK_POTONGAN_1: BAGIAN 1--< POTONGAN [hapus: ikut hapus] - ERD.md §2.5
ALTER TABLE {skema}.POTONGAN DROP CONSTRAINT FK_POTONGAN_1
/
ALTER TABLE {skema}.POTONGAN ADD CONSTRAINT FK_POTONGAN_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN) ON DELETE CASCADE
/
-- FK_POTONGAN_2: DETAIL_PROPORSIONAL 1--< POTONGAN [hapus: ikut hapus] - ERD.md §2.5
ALTER TABLE {skema}.POTONGAN DROP CONSTRAINT FK_POTONGAN_2
/
ALTER TABLE {skema}.POTONGAN ADD CONSTRAINT FK_POTONGAN_2 FOREIGN KEY (ID_DETAIL_PROPORSIONAL)
  REFERENCES {skema}.DETAIL_PROPORSIONAL (ID_DETAIL_PROPORSIONAL) ON DELETE CASCADE
/
-- FK_PEMULIHAN_LIMIT_1: LAYER 1--< PEMULIHAN_LIMIT [hapus: ikut hapus] - ERD.md §2.3b
ALTER TABLE {skema}.PEMULIHAN_LIMIT DROP CONSTRAINT FK_PEMULIHAN_LIMIT_1
/
ALTER TABLE {skema}.PEMULIHAN_LIMIT ADD CONSTRAINT FK_PEMULIHAN_LIMIT_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER) ON DELETE CASCADE
/
-- FK_NILAI_MDP_1: LAYER 1--< NILAI_MDP [hapus: ikut hapus] - ERD.md §2.3c
ALTER TABLE {skema}.NILAI_MDP DROP CONSTRAINT FK_NILAI_MDP_1
/
ALTER TABLE {skema}.NILAI_MDP ADD CONSTRAINT FK_NILAI_MDP_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER) ON DELETE CASCADE
/
-- FK_NILAI_MDP_MINIMUM_1: LAYER 1--< NILAI_MDP_MINIMUM [hapus: ikut hapus] - ERD.md §2.3c
ALTER TABLE {skema}.NILAI_MDP_MINIMUM DROP CONSTRAINT FK_NILAI_MDP_MINIMUM_1
/
ALTER TABLE {skema}.NILAI_MDP_MINIMUM ADD CONSTRAINT FK_NILAI_MDP_MINIMUM_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER) ON DELETE CASCADE
/
-- FK_NILAI_PREMI_BRUTO_1: BAGIAN 1--< NILAI_PREMI_BRUTO [hapus: ikut hapus] - ERD.md §2.3c
ALTER TABLE {skema}.NILAI_PREMI_BRUTO DROP CONSTRAINT FK_NILAI_PREMI_BRUTO_1
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO ADD CONSTRAINT FK_NILAI_PREMI_BRUTO_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN) ON DELETE CASCADE
/
-- FK_NILAI_PREMI_BRUTO_MIN_1: BAGIAN 1--< NILAI_PREMI_BRUTO_MINIMUM [hapus: ikut hapus] - ERD.md §2.3c
ALTER TABLE {skema}.NILAI_PREMI_BRUTO_MINIMUM DROP CONSTRAINT FK_NILAI_PREMI_BRUTO_MIN_1
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO_MINIMUM ADD CONSTRAINT FK_NILAI_PREMI_BRUTO_MIN_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN) ON DELETE CASCADE
/
-- FK_NILAI_CADANGAN_PREMI_1: DETAIL_PROPORSIONAL 1--< NILAI_CADANGAN_PREMI [hapus: ikut hapus] - ERD.md §2.3c
ALTER TABLE {skema}.NILAI_CADANGAN_PREMI DROP CONSTRAINT FK_NILAI_CADANGAN_PREMI_1
/
ALTER TABLE {skema}.NILAI_CADANGAN_PREMI ADD CONSTRAINT FK_NILAI_CADANGAN_PREMI_1 FOREIGN KEY (ID_DETAIL_PROPORSIONAL)
  REFERENCES {skema}.DETAIL_PROPORSIONAL (ID_DETAIL_PROPORSIONAL) ON DELETE CASCADE
/
-- FK_KONTRAK_DISALIN_DARI: KONTRAK 1--o< KONTRAK [hapus: PUTUS] — ERD.md §2.1
--
-- Kunci asing ini BELUM PERNAH ADA: kolomnya berdiri sejak migrasi 401, tetapi
-- tanpa kunci asing sama sekali. Karena itu ia DIBUAT di sini, bukan dibongkar
-- lalu dibuat ulang - nol DROP yang mendahuluinya.
--
-- Satu-satunya relasi `putus` di seluruh modul: kontrak salinan BERTAHAN ketika
-- asalnya dihapus, rujukannya saja yang dikosongkan. Kontrak salinan punya
-- versinya sendiri, dan versi itu memuat angka yang pernah dibukukan.
ALTER TABLE {skema}.KONTRAK ADD CONSTRAINT FK_KONTRAK_DISALIN_DARI
  FOREIGN KEY (ID_KONTRAK_DISALIN_DARI) REFERENCES {skema}.KONTRAK (ID_KONTRAK) ON DELETE SET NULL
/
CREATE INDEX {skema}.IX_KONTRAK_DISALIN_DARI ON {skema}.KONTRAK (ID_KONTRAK_DISALIN_DARI)
/
