-- =====================================================================
-- Z00_ISIAN_AWAL.sql
--
-- ⚠  BERKAS INI BERISI DML. SATU-SATUNYA DI SELURUH ddl-usulan/.
--
-- Dua puluh dua berkas tabel, sembilan view, dan berkas skema semuanya
-- menyatakan "TIDAK ADA DML DI BERKAS INI". Berkas ini kekecualiannya, dan
-- dipisahkan justru supaya kekecualian itu TERLIHAT — bukan terselip di kaki
-- sebuah berkas DDL tempat tidak ada yang mencarinya.
--
-- USULAN. BELUM PERNAH DIJALANKAN. UNTUK DIBACA, BUKAN UNTUK DIJALANKAN.
--
-- Tiket 21. Dijalankan SESUDAH 15_TUTUP_BUKU.sql dan 16_TARIF_BERLAKU.sql
-- (keduanya membuat sequence yang dipakai di bawah),
-- SEBELUM Z02_KUNCI_PEMILIK.sql — sesudah akun pemilik dikunci, tidak ada
-- lagi yang dapat mengisinya.
-- =====================================================================


-- ---------------------------------------------------------------------
-- KENAPA ID-nya TIDAK DITULIS TANGAN
-- ---------------------------------------------------------------------
-- Versi pertama menulis ID_TUTUP_BUKU = 1 dan ID_TARIF = 1, 2, 3 sebagai
-- angka. Itu SALAH pada kedua kemungkinan bentuk kolomnya:
--
--   * bila kolomnya GENERATED ALWAYS AS IDENTITY, keempat INSERT DITOLAK
--     (ORA-32795: cannot insert into a generated always identity column);
--   * bila GENERATED BY DEFAULT, ia jalan — tetapi sequence di belakangnya
--     TERTINGGAL di 1, dan INSERT PERTAMA dari aplikasi bertabrakan dengan
--     baris yang sudah ada di sini.
--
-- Yang kedua lebih berbahaya daripada yang pertama: ia gagal NANTI, di
-- tempat lain, atas sebab yang tidak tampak dari sini.
--
-- Bentuk kolomnya diperiksa, dan jawabannya BUKAN salah satu dari keduanya:
-- sampai 19 September 2026 TIDAK ADA pembangkit pengenal sama sekali — nol
-- IDENTITY, nol SEQUENCE, nol DEFAULT di seluruh 36 berkas. Sequence per
-- tabel dibuat pada tanggal itu, dan berkas ini memakai NEXTVAL-nya.
--
-- Dengan NEXTVAL, tidak ada nomor yang diandaikan dan tidak ada sequence
-- yang tertinggal — keduanya sekaligus, tanpa perlu memilih.


-- ---------------------------------------------------------------------
-- Kenapa baris ini ada di berkas, bukan diketik orang saat pemasangan
-- ---------------------------------------------------------------------
-- Karena keempat nilai di bawah SEKARANG TERTANAM DI KODE sistem lama, dan
-- seluruh maksud ADR-0025 adalah memindahkannya dari kode ke data. Baris
-- yang diketik orang saat pemasangan tidak dapat ditinjau, tidak dapat
-- dibandingkan, dan tidak meninggalkan jejak siapa yang memilih angkanya.
--
-- Angka 25 punya DUA sumber kebenaran di sistem lama: tertanam di
-- HitServiceToKasir_Act, DAN dibaca PROC_GENERATE_SEQUENCE_NUMBER dari
-- POOLDATA.TANGGAL_CLOSING. Dua sumber untuk satu aturan adalah cacat yang
-- tabel ini tutup — tetapi hanya bila tabelnya benar-benar terisi.
--
-- BERLAKU_SEJAK = 1900-01-01 bukan tanggal yang berarti. Ia menyatakan
-- "berlaku sejak sebelum data tertua yang akan dimigrasi", sehingga tidak
-- ada baris lama yang jatuh di luar masa berlaku tarif mana pun. Bila kelak
-- tarif berubah, barisnya BERTAMBAH dengan BERLAKU_SEJAK yang sebenarnya;
-- baris ini tidak pernah diubah.
--
-- DIBUAT_OLEH = 'MIGRASI' karena tidak ada orang yang memutuskannya — ia
-- dibaca dari kode lama apa adanya. Menuliskan nama seseorang di sini akan
-- mengarang pelaku untuk keputusan yang tidak pernah diambil siapa pun.


-- ---------------------------------------------------------------------
-- Tanggal tutup buku — AK-6.3
-- ---------------------------------------------------------------------
INSERT INTO KLAIMNP.TUTUP_BUKU
  (ID_TUTUP_BUKU, LINGKUP, BERLAKU_SEJAK, HARI_TUTUP_BUKU, DIBUAT_OLEH, DIBUAT_PADA)
VALUES
  (KLAIMNP.SQ_TUTUP_BUKU.NEXTVAL, 'GLOBAL', DATE '1900-01-01', 25, 'MIGRASI', SYSTIMESTAMP);


-- ---------------------------------------------------------------------
-- Tarif — AK-5. Nilainya MENUNGGU RATIFIKASI, dan ratifikasi TIDAK MENAHAN.
-- ASK-AKUNTANSI butir 5 memverifikasi apakah ketiganya masih berlaku.
-- Bila ternyata tidak, yang berubah ISI BARIS — pekerjaan entri, bukan
-- pekerjaan kode. Itu seluruh maksud ADR-0025.
-- ---------------------------------------------------------------------
INSERT INTO KLAIMNP.TARIF_BERLAKU
  (ID_TARIF, LINGKUP, JENIS_TARIF, BERLAKU_SEJAK, NILAI_TARIF_PERSEN, DIBUAT_OLEH, DIBUAT_PADA)
VALUES
  (KLAIMNP.SQ_TARIF_BERLAKU.NEXTVAL, 'GLOBAL', 'BROKERAGE', DATE '1900-01-01', 2.5, 'MIGRASI', SYSTIMESTAMP);

INSERT INTO KLAIMNP.TARIF_BERLAKU
  (ID_TARIF, LINGKUP, JENIS_TARIF, BERLAKU_SEJAK, NILAI_TARIF_PERSEN, DIBUAT_OLEH, DIBUAT_PADA)
VALUES
  (KLAIMNP.SQ_TARIF_BERLAKU.NEXTVAL, 'GLOBAL', 'PAJAK_PENGHASILAN', DATE '1900-01-01', 2.0, 'MIGRASI', SYSTIMESTAMP);

INSERT INTO KLAIMNP.TARIF_BERLAKU
  (ID_TARIF, LINGKUP, JENIS_TARIF, BERLAKU_SEJAK, NILAI_TARIF_PERSEN, DIBUAT_OLEH, DIBUAT_PADA)
VALUES
  (KLAIMNP.SQ_TARIF_BERLAKU.NEXTVAL, 'GLOBAL', 'PAJAK_PERTAMBAHAN_NILAI', DATE '1900-01-01', 2.2, 'MIGRASI', SYSTIMESTAMP);

COMMIT;


-- ---------------------------------------------------------------------
-- Apa yang SENGAJA TIDAK ada di sini
-- ---------------------------------------------------------------------
--   1. Faktor 102,2. Ia TIDAK DISIMPAN — ia diturunkan sebagai
--      (100 + tarif PPN). Menyimpan keduanya berarti menyimpan satu
--      kebenaran di dua tempat, yaitu cacat yang tabel ini tutup.
--   2. Riwayat tarif. TIDAK ADA BUKTI tarif pernah berubah (AK-5), dan
--      riwayat yang dikarang lebih buruk daripada riwayat yang kosong.
--   3. Baris per lini usaha. LINGKUP = 'GLOBAL' untuk seluruhnya, karena
--      tidak ada bukti tarif pernah berbeda per lini. Kolomnya ada supaya
--      pembedaan itu MUNGKIN, bukan supaya ia diandaikan.
--
-- Pemeriksaan sesudah dijalankan — harapan: 1 dan 3.
--   SELECT COUNT(*) FROM KLAIMNP.TUTUP_BUKU;
--   SELECT COUNT(*) FROM KLAIMNP.TARIF_BERLAKU;
-- =====================================================================
