-- Sequence identitas tabel anak - tiket 20, 22-31, 39
--
-- Migrasi tiket 20, 22-31, dan 39 Treaty In. Satu berkas = satu langkah migrasi.
-- Pernyataan dipisahkan oleh baris yang hanya berisi tanda garis miring.
--
-- INV-02: pengenal datang dari SEQUENCE, tidak pernah dari cap waktu maupun
-- teks. INV-03: NOCYCLE - satu nomor tidak pernah terpakai dua kali.
--
-- ⛔ `ddl-usulan/` tidak memuat satu pun CREATE SEQUENCE untuk tabel mana pun
-- (lihat `docs/KEPUTUSAN-PENYELARASAN-REPO.md` butir 4). Berkas ini menutup
-- lubang itu untuk kelima belas tabel yang langkah 403-414 buat, dan
-- menutupnya DI SINI - bukan di dalam berkas tabelnya - supaya ketiadaannya
-- di spec tetap terbaca sebagai temuan.
--
-- Nama dibatasi 30 bita (§16); yang terpanjang di bawah 26 bita.
CREATE SEQUENCE {skema}.SEQ_TRIN_MATA_UANG_KONTRAK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_RETENSI_CEDANT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_EGNPI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_PORTOFOLIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_PERIODE_PELAPORAN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_PERIODE_AKUMULASI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_TERMIN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_SKALA_KOASURANSI START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_BATAS_PER_BAHAYA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_DOKUMEN_KONTRAK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_LAYER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_NILAI_MDP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_NILAI_MDP_MINIMUM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_PEMULIHAN_LIMIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_JEJAK_PERUBAHAN START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
