-- Jalur mundur untuk 420_perilaku_hapus_erd.sql
--
-- Mengembalikan perilaku hapus ke bentuk yang tercatat di T_MIGRASI sebelum
-- 420: seluruh kunci asing TANPA klausa ON DELETE, dan FK_KONTRAK_DISALIN_DARI
-- kembali TIDAK ADA.
--
-- ⚠️ Membongkar ini mengembalikan pelanggaran INV-18 yang 420 perbaiki:
-- perilaku hapus kembali menjadi bawaan yang dibiarkan, bukan keputusan yang
-- dinyatakan. Jalankan hanya untuk mengembalikan skema ke keadaan pra-420.
DROP INDEX {skema}.IX_KONTRAK_DISALIN_DARI
/
ALTER TABLE {skema}.KONTRAK DROP CONSTRAINT FK_KONTRAK_DISALIN_DARI
/
ALTER TABLE {skema}.NILAI_CADANGAN_PREMI DROP CONSTRAINT FK_NILAI_CADANGAN_PREMI_1
/
ALTER TABLE {skema}.NILAI_CADANGAN_PREMI ADD CONSTRAINT FK_NILAI_CADANGAN_PREMI_1 FOREIGN KEY (ID_DETAIL_PROPORSIONAL)
  REFERENCES {skema}.DETAIL_PROPORSIONAL (ID_DETAIL_PROPORSIONAL)
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO_MINIMUM DROP CONSTRAINT FK_NILAI_PREMI_BRUTO_MIN_1
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO_MINIMUM ADD CONSTRAINT FK_NILAI_PREMI_BRUTO_MIN_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN)
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO DROP CONSTRAINT FK_NILAI_PREMI_BRUTO_1
/
ALTER TABLE {skema}.NILAI_PREMI_BRUTO ADD CONSTRAINT FK_NILAI_PREMI_BRUTO_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN)
/
ALTER TABLE {skema}.NILAI_MDP_MINIMUM DROP CONSTRAINT FK_NILAI_MDP_MINIMUM_1
/
ALTER TABLE {skema}.NILAI_MDP_MINIMUM ADD CONSTRAINT FK_NILAI_MDP_MINIMUM_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER)
/
ALTER TABLE {skema}.NILAI_MDP DROP CONSTRAINT FK_NILAI_MDP_1
/
ALTER TABLE {skema}.NILAI_MDP ADD CONSTRAINT FK_NILAI_MDP_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER)
/
ALTER TABLE {skema}.PEMULIHAN_LIMIT DROP CONSTRAINT FK_PEMULIHAN_LIMIT_1
/
ALTER TABLE {skema}.PEMULIHAN_LIMIT ADD CONSTRAINT FK_PEMULIHAN_LIMIT_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER)
/
ALTER TABLE {skema}.POTONGAN DROP CONSTRAINT FK_POTONGAN_2
/
ALTER TABLE {skema}.POTONGAN ADD CONSTRAINT FK_POTONGAN_2 FOREIGN KEY (ID_DETAIL_PROPORSIONAL)
  REFERENCES {skema}.DETAIL_PROPORSIONAL (ID_DETAIL_PROPORSIONAL)
/
ALTER TABLE {skema}.POTONGAN DROP CONSTRAINT FK_POTONGAN_1
/
ALTER TABLE {skema}.POTONGAN ADD CONSTRAINT FK_POTONGAN_1 FOREIGN KEY (ID_BAGIAN)
  REFERENCES {skema}.BAGIAN (ID_BAGIAN)
/
ALTER TABLE {skema}.BAGIAN DROP CONSTRAINT FK_BAGIAN_1
/
ALTER TABLE {skema}.BAGIAN ADD CONSTRAINT FK_BAGIAN_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER)
/
ALTER TABLE {skema}.DETAIL_PROPORSIONAL DROP CONSTRAINT FK_DETAIL_PROPORSIONAL_1
/
ALTER TABLE {skema}.DETAIL_PROPORSIONAL ADD CONSTRAINT FK_DETAIL_PROPORSIONAL_1 FOREIGN KEY (ID_LAYER)
  REFERENCES {skema}.LAYER (ID_LAYER)
/
ALTER TABLE {skema}.LAYER DROP CONSTRAINT FK_LAYER_1
/
ALTER TABLE {skema}.LAYER ADD CONSTRAINT FK_LAYER_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.DOKUMEN_KONTRAK DROP CONSTRAINT FK_DOKUMEN_KONTRAK_1
/
ALTER TABLE {skema}.DOKUMEN_KONTRAK ADD CONSTRAINT FK_DOKUMEN_KONTRAK_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.BATAS_PER_BAHAYA DROP CONSTRAINT FK_BATAS_PER_BAHAYA_1
/
ALTER TABLE {skema}.BATAS_PER_BAHAYA ADD CONSTRAINT FK_BATAS_PER_BAHAYA_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.SKALA_KOASURANSI DROP CONSTRAINT FK_SKALA_KOASURANSI_1
/
ALTER TABLE {skema}.SKALA_KOASURANSI ADD CONSTRAINT FK_SKALA_KOASURANSI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.TERMIN DROP CONSTRAINT FK_TERMIN_1
/
ALTER TABLE {skema}.TERMIN ADD CONSTRAINT FK_TERMIN_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.PERIODE_AKUMULASI DROP CONSTRAINT FK_PERIODE_AKUMULASI_1
/
ALTER TABLE {skema}.PERIODE_AKUMULASI ADD CONSTRAINT FK_PERIODE_AKUMULASI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.PERIODE_PELAPORAN DROP CONSTRAINT FK_PERIODE_PELAPORAN_1
/
ALTER TABLE {skema}.PERIODE_PELAPORAN ADD CONSTRAINT FK_PERIODE_PELAPORAN_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.PORTOFOLIO DROP CONSTRAINT FK_PORTOFOLIO_1
/
ALTER TABLE {skema}.PORTOFOLIO ADD CONSTRAINT FK_PORTOFOLIO_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.EGNPI DROP CONSTRAINT FK_EGNPI_1
/
ALTER TABLE {skema}.EGNPI ADD CONSTRAINT FK_EGNPI_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.RETENSI_CEDANT DROP CONSTRAINT FK_RETENSI_CEDANT_1
/
ALTER TABLE {skema}.RETENSI_CEDANT ADD CONSTRAINT FK_RETENSI_CEDANT_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
ALTER TABLE {skema}.MATA_UANG_KONTRAK DROP CONSTRAINT FK_MATA_UANG_KONTRAK_1
/
ALTER TABLE {skema}.MATA_UANG_KONTRAK ADD CONSTRAINT FK_MATA_UANG_KONTRAK_1 FOREIGN KEY (ID_VERSI_KONTRAK)
  REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK)
/
