-- Pembalikan `434_cabut_mata_uang.sql` — MATA_UANG dan MATA_UANG_KONTRAK
-- dibangun kembali UTUH, beserta kedua kunci asingnya.
--
-- ⚠️ Urutannya terbalik dari yang mencabut, dan itu wajib: `MATA_UANG` harus
-- berdiri sebelum apa pun merujuknya, dan `MATA_UANG_KONTRAK` sebelum
-- indexnya.
--
-- Bentuknya disalin APA ADANYA dari `400_tabel_acuan.sql`, `402_sequences.sql`
-- dan `403_mata_uang_kontrak.sql` — termasuk presisi `NUMBER(38,8)` pada
-- `KURS` dan lebar `VARCHAR2(1000 CHAR)` pada kolom acuan. Pembalikan yang
-- membangun bentuk BERBEDA bukan pembalikan.

CREATE SEQUENCE {skema}.SEQ_TRIN_MATA_UANG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE SEQUENCE {skema}.SEQ_TRIN_MATA_UANG_KONTRAK START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/
CREATE TABLE {skema}.MATA_UANG (
  ID_MATA_UANG  NUMBER(19)          NOT NULL,
  KODE          VARCHAR2(1000 CHAR) NOT NULL,
  NAMA          VARCHAR2(1000 CHAR) NOT NULL,
  AKTIF         VARCHAR2(40 CHAR)   NOT NULL,
  CONSTRAINT PK_MATA_UANG PRIMARY KEY (ID_MATA_UANG),
  CONSTRAINT UQ_MATA_UANG UNIQUE (KODE)
)
/
CREATE TABLE {skema}.MATA_UANG_KONTRAK (
  ID_MATA_UANG_KONTRAK   NUMBER(19)   NOT NULL,
  ID_VERSI_KONTRAK       NUMBER(19)   NOT NULL,
  KODE_MATA_UANG         NUMBER(19)   NOT NULL,
  KURS                   NUMBER(38,8) NOT NULL,
  TANGGAL_MULAI_BERLAKU  DATE         NOT NULL,
  TANGGAL_AKHIR_BERLAKU  DATE         NOT NULL,
  CONSTRAINT PK_MATA_UANG_KONTRAK PRIMARY KEY (ID_MATA_UANG_KONTRAK),
  CONSTRAINT UQ_MATA_UANG_KONTRAK UNIQUE (ID_VERSI_KONTRAK, KODE_MATA_UANG),
  CONSTRAINT FK_MATA_UANG_KONTRAK_1 FOREIGN KEY (ID_VERSI_KONTRAK)
    REFERENCES {skema}.VERSI_KONTRAK (ID_VERSI_KONTRAK),
  CONSTRAINT FK_MATA_UANG_KONTRAK_2 FOREIGN KEY (KODE_MATA_UANG)
    REFERENCES {skema}.MATA_UANG (ID_MATA_UANG)
)
/
CREATE INDEX {skema}.IX_MATA_UANG_KONTRAK_MU ON {skema}.MATA_UANG_KONTRAK (KODE_MATA_UANG)
/
ALTER TABLE {skema}.VERSI_KONTRAK ADD CONSTRAINT FK_VERSI_KONTRAK_MATA_UANG
  FOREIGN KEY (KODE_MATA_UANG_KONTRAK) REFERENCES {skema}.MATA_UANG (ID_MATA_UANG)
/
