-- Pembalikan `436_nama_tabel_tab.sql` — nama lama dan `PXOBJCLASS` kembali.
--
-- ⛔ Ia TIDAK mengembalikan ISINYA. 27.238 baris yang `436` hapus dimuat ulang
-- dari `M_TREATY_IN.JSONDATA` lewat pemuat yang sudah ada — pembalikan yang
-- mengaku memulihkan data yang tidak ia simpan lebih berbahaya daripada yang
-- menyatakan tidak.

-- 1 · Sequence, index, batasan — urutan terbalik dari yang maju.
RENAME SEQ_TT_REPORTING_PERIOD TO SEQ_MTI_REPORTINGPERIOD
/
RENAME SEQ_TT_PORTFOLIO TO SEQ_MTI_PORTFOLIO
/
RENAME SEQ_TT_ACCUMULATION TO SEQ_MTI_ACCUMULATION
/
RENAME SEQ_TT_EGNPI TO SEQ_MTI_EGNPI
/
RENAME SEQ_TT_RETENTION TO SEQ_MTI_RETENTION
/
RENAME SEQ_TT_INSTALLMENT TO SEQ_MTI_INSTALLMENT
/
RENAME SEQ_TT_INSTALLMENT_ITEM TO SEQ_MTI_INSTALLMENTITEM
/
RENAME SEQ_TV_COMMENT TO SEQ_MTI_COMMENT
/
ALTER INDEX {skema}.IX_TT_INSTALLMENT_ITEM_MST RENAME TO IX_MTI_INSTALLMENTITEM_MST
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT_ITEM RENAME CONSTRAINT FK_TT_INSTALLMENT_ITEM_1 TO FK_MTI_INSTALLMENTITEM_1
/
ALTER TABLE {skema}.T_TREATY_REPORTING_PERIOD RENAME CONSTRAINT PK_TT_REPORTING_PERIOD TO PK_MTI_REPORTINGPERIOD
/
ALTER TABLE {skema}.T_TREATY_REPORTING_PERIOD RENAME CONSTRAINT UQ_TT_REPORTING_PERIOD TO UQ_MTI_REPORTINGPERIOD
/
ALTER TABLE {skema}.T_TREATY_PORTFOLIO RENAME CONSTRAINT PK_TT_PORTFOLIO TO PK_MTI_PORTFOLIO
/
ALTER TABLE {skema}.T_TREATY_PORTFOLIO RENAME CONSTRAINT UQ_TT_PORTFOLIO TO UQ_MTI_PORTFOLIO
/
ALTER TABLE {skema}.T_TREATY_ACCUMULATION RENAME CONSTRAINT PK_TT_ACCUMULATION TO PK_MTI_ACCUMULATION
/
ALTER TABLE {skema}.T_TREATY_ACCUMULATION RENAME CONSTRAINT UQ_TT_ACCUMULATION TO UQ_MTI_ACCUMULATION
/
ALTER TABLE {skema}.T_TREATY_EGNPI RENAME CONSTRAINT PK_TT_EGNPI TO PK_MTI_EGNPI
/
ALTER TABLE {skema}.T_TREATY_EGNPI RENAME CONSTRAINT UQ_TT_EGNPI TO UQ_MTI_EGNPI
/
ALTER TABLE {skema}.T_TREATY_RETENTION RENAME CONSTRAINT PK_TT_RETENTION TO PK_MTI_RETENTION
/
ALTER TABLE {skema}.T_TREATY_RETENTION RENAME CONSTRAINT UQ_TT_RETENTION TO UQ_MTI_RETENTION
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT RENAME CONSTRAINT PK_TT_INSTALLMENT TO PK_MTI_INSTALLMENT
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT RENAME CONSTRAINT UQ_TT_INSTALLMENT TO UQ_MTI_INSTALLMENT
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT_ITEM RENAME CONSTRAINT PK_TT_INSTALLMENT_ITEM TO PK_MTI_INSTALLMENTITEM
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT_ITEM RENAME CONSTRAINT UQ_TT_INSTALLMENT_ITEM TO UQ_MTI_INSTALLMENTITEM
/
ALTER TABLE {skema}.T_VIEW_COMMENT RENAME CONSTRAINT PK_TV_COMMENT TO PK_MTI_COMMENT
/

-- 2 · Nama tabel kembali.
ALTER TABLE {skema}.T_TREATY_REPORTING_PERIOD RENAME TO M_TREATYIN_REPORTINGPERIOD
/
ALTER TABLE {skema}.T_TREATY_PORTFOLIO RENAME TO M_TREATYIN_PORTFOLIO
/
ALTER TABLE {skema}.T_TREATY_ACCUMULATION RENAME TO M_TREATYIN_ACCUMULATION
/
ALTER TABLE {skema}.T_TREATY_EGNPI RENAME TO M_TREATYIN_EGNPI
/
ALTER TABLE {skema}.T_TREATY_RETENTION RENAME TO M_TREATYIN_RETENTION
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT RENAME TO M_TREATYIN_INSTALLMENT
/
ALTER TABLE {skema}.T_TREATY_INSTALLMENT_ITEM RENAME TO M_TREATYIN_INSTALLMENTITEM
/
ALTER TABLE {skema}.T_VIEW_COMMENT RENAME TO M_TREATYIN_COMMENT
/

-- 3 · `PXOBJCLASS` kembali — bentuknya DISALIN apa adanya dari `430`/`432`.
ALTER TABLE {skema}.M_TREATYIN_REPORTINGPERIOD ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_PORTFOLIO ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_ACCUMULATION ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_EGNPI ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_RETENTION ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_INSTALLMENT ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_INSTALLMENTITEM ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_COMMENT ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
ALTER TABLE {skema}.M_TREATYIN_COINSCALE ADD (PXOBJCLASS VARCHAR2(200 CHAR))
/
