-- Pembalikan `437_anak_treaty_in.sql` — ketiga belas tabel dan sequence-nya
-- dicabut. Urutannya TERBALIK dari yang maju: anak sebelum induk, sebab kunci
-- asing `ON DELETE CASCADE` tetap menolak induk yang masih punya anak.
--
-- ⛔ Nol data hilang: ketiga belas tabel ini lahir KOSONG di `437` dan
-- pemuatnya belum dibangun.

DROP TABLE {skema}.T_TREATY_LIMIT_GROUP_COB CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_LIMIT_ACHIEVEMENT CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_LIMIT_COB CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_FAC_SHARE_DEDUCTION CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_SHARE_DEDUCTION CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_SHARE_SPREADING CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_LIMIT_GROUP CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_LIMIT_DETAIL CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_FAC_REINSURER CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_FAC_SHARE CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_RETRO_SHARE CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_SHARE CASCADE CONSTRAINTS
/
DROP TABLE {skema}.T_TREATY_LIMITS CASCADE CONSTRAINTS
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_GRP_COB
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_ACHIEVE
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_COB
/
DROP SEQUENCE {skema}.SEQ_TT_FAC_SHARE_DED
/
DROP SEQUENCE {skema}.SEQ_TT_SHARE_DEDUCTION
/
DROP SEQUENCE {skema}.SEQ_TT_SHARE_SPREADING
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_GROUP
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_DETAIL
/
DROP SEQUENCE {skema}.SEQ_TT_FAC_REINSURER
/
DROP SEQUENCE {skema}.SEQ_TT_FAC_SHARE
/
DROP SEQUENCE {skema}.SEQ_TT_RETRO_SHARE
/
DROP SEQUENCE {skema}.SEQ_TT_SHARE
/
DROP SEQUENCE {skema}.SEQ_TT_LIMITS
/
