-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."T_STORAGE_IMAGE" 
   (	"IMAGEID" VARCHAR2(200) NOT NULL ENABLE, 
	"URLPUBLIC" VARCHAR2(4000), 
	"APPFOLDER" VARCHAR2(4000), 
	"EXPDATE" DATE, 
	"FILENAME" VARCHAR2(4000), 
	"APPNAME" VARCHAR2(100), 
	"STORAGE" VARCHAR2(50), 
	"TANGGAL_UPLOAD" DATE DEFAULT SYSDATE, 
	 CONSTRAINT "T_STORAGE_IMAGE_PK" PRIMARY KEY ("IMAGEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLDATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBS_POOLDATA" 