-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."JSON_POLIS" 
   (	"TGL_INPUT" DATE DEFAULT sysdate, 
	"DATA_JSON" CLOB, 
	"NOPOLIS" VARCHAR2(100) NOT NULL ENABLE, 
	"NOENDORS" VARCHAR2(100), 
	"PRODKE" VARCHAR2(5), 
	"ERR_NOTE" VARCHAR2(1000), 
	"TGL_KONVERSI" DATE, 
	"IDPEGA" VARCHAR2(50), 
	"STS_KONVERSI" NUMBER, 
	"TGL_KONVERSI_RETRO" DATE, 
	"STS_KONVERSI_RETRO" NUMBER, 
	"OLDNOPOLIS" VARCHAR2(100), 
	"TGL_PROD" DATE, 
	"USERNAME" VARCHAR2(200), 
	 CONSTRAINT "VALID_JSON" CHECK (DATA_JSON IS JSON(STRICT)) DISABLE, 
	 CONSTRAINT "JSON_POLIS_U01" UNIQUE ("NOPOLIS", "IDPEGA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSON_POLIS_IDX"  ENABLE, 
	 CONSTRAINT "PK_JSON_POLIS" PRIMARY KEY ("IDPEGA")
  USING INDEX (CREATE INDEX "POOLDATA"."JSON_POLIS_IDX3" ON "POOLDATA"."JSON_POLIS" ("IDPEGA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSON_POLIS_IDX" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 100 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSON_POLIS" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "JSON_POLIS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 