-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."OS_AKSEPTASI_KLAIM" 
   (	"CASEID" VARCHAR2(100), 
	"NOCLAIM" VARCHAR2(100), 
	"DATA_JSON" CLOB, 
	"TANGGAL" DATE DEFAULT sysdate, 
	"NOPOLIS" VARCHAR2(30), 
	"STS_REJECT" NUMBER(38,0), 
	"STS_KONVERSI" CHAR(1) DEFAULT 0, 
	"TGL_KONVERSI" DATE, 
	"STS_DLA" VARCHAR2(100), 
	"ERR_NOTE" VARCHAR2(2000), 
	"MASTERID" VARCHAR2(50), 
	"DLA_NO" VARCHAR2(50), 
	"CLAIMOLD" VARCHAR2(50), 
	"DLA_DATE" DATE, 
	"TGL_PROD" DATE, 
	"OBJECTID" VARCHAR2(200), 
	"OBJECTNAME" VARCHAR2(2000), 
	"OBJECTITEMNAME" VARCHAR2(2000), 
	"PACKINGNAME" VARCHAR2(500), 
	"GOODSNAME" VARCHAR2(500), 
	"CONVEYANCENAME" VARCHAR2(500), 
	"BRANDNAME" VARCHAR2(200), 
	"MODELNAME" VARCHAR2(200), 
	"COVERAGEID" VARCHAR2(100), 
	"COVERAGENAME" VARCHAR2(4000), 
	"CURRENCYID" VARCHAR2(10), 
	"CURRENCY" VARCHAR2(20), 
	"VALUE" NUMBER, 
	"GROSSVALUE" NUMBER, 
	"DEDUCTIBLEVALUE" NUMBER, 
	"RNM_SHARE" NUMBER, 
	"CAUSEOFLOSSID" VARCHAR2(100), 
	"CAUSEOFLOSS" VARCHAR2(1000), 
	"DLA_OP" VARCHAR2(50), 
	"INSERT_OP" VARCHAR2(50), 
	"ACCEPTEDNO" VARCHAR2(50), 
	"DLANO_CEDING" VARCHAR2(200), 
	"DLANO_SOB" VARCHAR2(200), 
	"PAYMENTTYPE" VARCHAR2(10), 
	"NETFORCOLLECTION" VARCHAR2(10), 
	"TYPELOSSID" VARCHAR2(50), 
	"TYPELOSSNAME" VARCHAR2(50), 
	"ADJUSTERFEE" NUMBER, 
	"CNPOTHERSFEE" NUMBER, 
	"KURSVALUE" NUMBER, 
	"SALVAGE" NUMBER, 
	"TYPE" VARCHAR2(50), 
	"ESTIMATIONDATE" DATE, 
	"PERSENRNM" NUMBER, 
	"XOL" VARCHAR2(100), 
	"XOLID" VARCHAR2(50), 
	"ADJUSTERFEERNM" NUMBER, 
	"ADJUSTERFEEVALUE" NUMBER, 
	"CNPLIMIT" NUMBER, 
	"CNPMINDEP" NUMBER, 
	"CNPOTHERSFEERNM" NUMBER, 
	"CNPPCTREINSTATE" NUMBER, 
	"CNPREINSTATEMENT" NUMBER, 
	"CNPREINSTATEMENTRNM" NUMBER, 
	"GROSSADJUSTMENT" NUMBER, 
	"KURSIDR" NUMBER, 
	"SALVAGERNM" NUMBER, 
	"SALVAGEVALUE" NUMBER, 
	"TOTALXOL" NUMBER, 
	"TOTALXOLGROSS" NUMBER, 
	"TOTALXOLLAYERRNM" NUMBER, 
	"TOTALXOLRNM" NUMBER, 
	 CONSTRAINT "ENSURE_OS_AKSEPTASI_KLAIM_JSON" CHECK (DATA_JSON IS JSON) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "POOLMASTER" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 