-- SUMBER: ditempel langsung oleh pengguna 18 September 2026 (reverse-engineer Toad).
-- Tidak melalui DDL_Script_ClaimNonProp.xls.
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN.
-- Klausa DROP TABLE dan ALTER ... DROP PRIMARY KEY sudah dibuang oleh pengirim.
-- CATATAN LINGKUP: tabel ini dibuat Pega, bukan buatan tim. TIDAK DIMIGRASI.

CREATE TABLE DATAPEGA.PC_ASM_FW_GCNMFW_WORK
(
  PXCOMMITDATETIME              TIMESTAMP(6),
  PXSAVEDATETIME                TIMESTAMP(6),
  PXCOVERINSKEY                 VARCHAR2(255 CHAR),
  PXCOVEREDCOUNT                NUMBER(18),
  PXCOVEREDCOUNTOPEN            NUMBER(18),
  PXCOVEREDCOUNTUNSATISFIED     NUMBER(18),
  PXCREATEDATETIME              TIMESTAMP(6),
  PXCREATEOPNAME                VARCHAR2(128 CHAR),
  PXCREATEOPERATOR              VARCHAR2(128 CHAR),
  PXCREATESYSTEMID              VARCHAR2(32 CHAR),
  PXFLOWCOUNT                   NUMBER(18),
  PXINSNAME                     VARCHAR2(128 CHAR),
  PXOBJCLASS                    VARCHAR2(96 CHAR),
  PXUPDATEDATETIME              TIMESTAMP(6),
  PXUPDATEOPNAME                VARCHAR2(128 CHAR),
  PXUPDATEOPERATOR              VARCHAR2(128 CHAR),
  PXUPDATESYSTEMID              VARCHAR2(32 CHAR),
  PXURGENCYWORK                 NUMBER(18),
  PYACKTIMESTAMP                TIMESTAMP(6),
  PYAGEFROMDATE                 TIMESTAMP(6),
  PYCHARGEAMOUNT                NUMBER(18),
  PYCHARGETO                    VARCHAR2(64 CHAR),
  PYCONTACTCHANNEL              VARCHAR2(64 CHAR),
  PYCONTACTTYPE                 VARCHAR2(64 CHAR),
  PYCUSLEVEL                    VARCHAR2(32 CHAR),
  PYCUSTOMER                    VARCHAR2(128 CHAR),
  PYCUSTOMERENTERPRISE          VARCHAR2(32 CHAR),
  PYCUSTOMERNAME                VARCHAR2(64 CHAR),
  PYCUSTOMERORG                 VARCHAR2(32 CHAR),
  PYCUSTOMERSATISFIEDTIMESTAMP  TIMESTAMP(6),
  PYDESCRIPTION                 VARCHAR2(255 CHAR),
  PYEFFORTACTUAL                NUMBER(18),
  PYEFFORTESTIMATE              NUMBER(18),
  PYEFFORTESTIMATETIMESTAMP     TIMESTAMP(6),
  PYELAPSEDCUSTOMERACK          NUMBER(18),
  PYELAPSEDCUSTOMERUNSATISFIED  NUMBER(18),
  PYELAPSEDPASTDEADLINE         NUMBER(18),
  PYELAPSEDPASTGOAL             NUMBER(18),
  PYELAPSEDSTATUSNEW            NUMBER(18),
  PYELAPSEDSTATUSOPEN           NUMBER(18),
  PYELAPSEDSTATUSPENDING        NUMBER(18),
  PYEVENTID                     VARCHAR2(32 CHAR),
  PYFOLDERTYPE                  VARCHAR2(32 CHAR),
  PYID                          VARCHAR2(32 CHAR),
  PYLABEL                       VARCHAR2(64 CHAR),
  PYORIGDIVISION                VARCHAR2(32 CHAR),
  PYORIGORG                     VARCHAR2(32 CHAR),
  PYORIGORGUNIT                 VARCHAR2(32 CHAR),
  PYORIGUSERDIVISION            VARCHAR2(32 CHAR),
  PYORIGUSERID                  VARCHAR2(128 CHAR),
  PYORIGUSERWORKGROUP           VARCHAR2(64 CHAR),
  PYOWNERDIVISION               VARCHAR2(32 CHAR),
  PYOWNERORG                    VARCHAR2(32 CHAR),
  PYOWNERORGUNIT                VARCHAR2(32 CHAR),
  PYPRIMARYCONTACT              VARCHAR2(64 CHAR),
  PYPROBLEMREASON               VARCHAR2(64 CHAR),
  PYPROBLEMSOURCE               VARCHAR2(64 CHAR),
  PYPROBLEMTYPE                 VARCHAR2(64 CHAR),
  PYREOPENCOUNT                 NUMBER(18),
  PYREOPENTIMESTAMP             TIMESTAMP(6),
  PYRESOLUTIONCOMPLEXITY        VARCHAR2(8 CHAR),
  PYRESOLUTIONCOST              NUMBER(18),
  PYRESOLVEDDIVISION            VARCHAR2(32 CHAR),
  PYRESOLVEDORG                 VARCHAR2(32 CHAR),
  PYRESOLVEDORGUNIT             VARCHAR2(32 CHAR),
  PYRESOLVEDTIME                VARCHAR2(32 CHAR),
  PYRESOLVEDTIMESTAMP           TIMESTAMP(6),
  PYRESOLVEDUSERID              VARCHAR2(128 CHAR),
  PYRESOLVEDUSERWORKGROUP       VARCHAR2(64 CHAR),
  PYROOTCAUSE                   VARCHAR2(64 CHAR),
  PYSLADEADLINE                 TIMESTAMP(6),
  PYSLAGOAL                     TIMESTAMP(6),
  PYSLANAME                     VARCHAR2(32 CHAR),
  PYSTATUSCUSTOMERSAT           VARCHAR2(32 CHAR),
  PYSTATUSWORK                  VARCHAR2(32 CHAR),
  PXCURRENTSTAGELABEL           VARCHAR2(128 CHAR),
  PXCURRENTSTAGE                VARCHAR2(32 CHAR),
  PZINSKEY                      VARCHAR2(255 CHAR) NOT NULL,
  PXAPPLICATION                 VARCHAR2(64 CHAR),
  PXAPPLICATIONVERSION          VARCHAR2(32 CHAR),
  PZPVSTREAM                    BLOB,
  SOBNAME                       VARCHAR2(128 BYTE),
  BUSINESSNAME                  VARCHAR2(128 BYTE),
  CEDINGCONAME                  VARCHAR2(128 BYTE),
  INSUREDNAME                   VARCHAR2(255 BYTE),
  NOPOLIS                       VARCHAR2(128 BYTE),
  MASTERID                      VARCHAR2(128 BYTE),
  KOMITECOUNT                   NUMBER(18),
  DATEOFLOSS                    VARCHAR2(8 BYTE),
  ISSUBJECTIVITY                VARCHAR2(5 BYTE),
  NOCLAIM                       VARCHAR2(32 CHAR),
  FLAGONGOINGCOMMITTE           VARCHAR2(32 CHAR),
  CLMNO                         VARCHAR2(32 CHAR),
  DATERECEIVED                  DATE,
  PLA_CEDING                    VARCHAR2(500 BYTE),
  PLA_SOB                       VARCHAR2(500 BYTE),
  DLA_CEDING                    VARCHAR2(500 BYTE),
  DLA_SOB                       VARCHAR2(500 BYTE),
  POLICY_CEDING                 VARCHAR2(500 BYTE),
  CAUSEOFLOSS                   VARCHAR2(500 BYTE)
)
LOB (PZPVSTREAM) STORE AS SECUREFILE (
  TABLESPACE  DATAPEGA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
TABLESPACE DATAPEGA;

CREATE UNIQUE INDEX DATAPEGA.PC_ASM_FW_GCNMFW_WORK_PK
  ON DATAPEGA.PC_ASM_FW_GCNMFW_WORK (PZINSKEY);

CREATE INDEX DATAPEGA.PC_WORK_IDX1_2AED8
  ON DATAPEGA.PC_ASM_FW_GCNMFW_WORK (PXCOVERINSKEY, PXOBJCLASS, PYSTATUSWORK);

CREATE INDEX DATAPEGA.PC_WORK_IDX2_2AED8
  ON DATAPEGA.PC_ASM_FW_GCNMFW_WORK (PXAPPLICATION, PXAPPLICATIONVERSION, PXOBJCLASS, PYSTATUSWORK);

ALTER TABLE DATAPEGA.PC_ASM_FW_GCNMFW_WORK ADD (
  CONSTRAINT PC_ASM_FW_GCNMFW_WORK_PK
  PRIMARY KEY (PZINSKEY)
  USING INDEX DATAPEGA.PC_ASM_FW_GCNMFW_WORK_PK
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE,
      ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK
  ON DATAPEGA.PC_ASM_FW_GCNMFW_WORK TO POOLDATA;
