-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."JSON_KLAIM" 
   (	"MNK_NO_KLAIM" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_JSON" CLOB, 
	"IDPEGA" VARCHAR2(100), 
	"TGL_INPUT" DATE DEFAULT sysdate, 
	"TGL_KONVERSI" DATE, 
	"NOPOLIS" VARCHAR2(100) NOT NULL ENABLE, 
	"IDPROD" NUMBER(*,0), 
	"STS_KONVERSI" NUMBER(1,0), 
	 CONSTRAINT "JSON_KLAIM_C01" CHECK (DATA_JSON IS JSON) ENABLE NOVALIDATE, 
	 CONSTRAINT "PK_JSON_KLAIM" PRIMARY KEY ("IDPEGA")
  USING INDEX (CREATE INDEX "POOLDATA"."IDX_KLAIM_001" ON "POOLDATA"."JSON_KLAIM" ("IDPEGA", "NOPOLIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSON_KLAIM_IDX" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 50 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "JSON_KLAIM" 
 LOB ("DATA_JSON") STORE AS SECUREFILE (
  TABLESPACE "JSON_KLAIM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 