-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."EMAILKOMITE" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(150), 
	"EMAIL" VARCHAR2(150), 
	"LIMIT_BOTTOM" NUMBER(*,0), 
	"LIMIT_TOP" NUMBER(*,0), 
	"DEGREE" VARCHAR2(150), 
	"STS_AKTIF" VARCHAR2(150), 
	"OPERATOR_ID" VARCHAR2(50), 
	"STS_REJECT" VARCHAR2(15), 
	"STS_ADJ" VARCHAR2(15), 
	"TYPE_BUSINESS" VARCHAR2(20), 
	"TYPE_KOMITE" NUMBER(*,0), 
	"STS_REG" NUMBER(*,0), 
	"STS_SURVEY" NUMBER(*,0), 
	"STS_SALVAGE" NUMBER, 
	"STS_ADJUSTER" NUMBER, 
	"STS_KLAIM" VARCHAR2(10), 
	"JABATAN" VARCHAR2(20), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLIDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 