-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."MARKETINGOFFICER" 
   (	"ID" VARCHAR2(100), 
	"CLIENTID" VARCHAR2(100), 
	"BRANCHDETAILID" VARCHAR2(100), 
	"MOLEADER" VARCHAR2(100), 
	"MOSTATUS" VARCHAR2(100), 
	"CLIENTID2" VARCHAR2(100), 
	"BRANCHSTATUS" VARCHAR2(100), 
	"TEAMGROUP" VARCHAR2(100), 
	"CLIENTNAME" VARCHAR2(100), 
	"TANGGAL" DATE, 
	"USERUPDATE" VARCHAR2(100), 
	"BRANCHPARENT" VARCHAR2(10), 
	"BRANCHDETAILNAME" VARCHAR2(100), 
	"AKSES_LOGIN" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 