-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."CLAIMXOL2" 
   (	"CASEID" VARCHAR2(100), 
	"GrossAdjustment" VARCHAR2(4000), 
	"CNPReinstatement" VARCHAR2(4000), 
	"Currency" VARCHAR2(4000), 
	"KursIDR" VARCHAR2(4000), 
	"XOL" VARCHAR2(4000), 
	"TANGGAL" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 