-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."CLAIMREJECTED" 
   (	"INSKEY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"ID" VARCHAR2(32 CHAR), 
	"INSNAME" VARCHAR2(128 CHAR), 
	"LABEL" VARCHAR2(64 CHAR), 
	"STATUSWORK" VARCHAR2(32 CHAR), 
	"CREATEOPNAME" VARCHAR2(128 CHAR), 
	"CREATEOPERATOR" VARCHAR2(128 CHAR), 
	"OBJCLASS" VARCHAR2(96 CHAR), 
	"UPDATEDATETIME" DATE, 
	"UPDATEOPNAME" VARCHAR2(128 CHAR), 
	"UPDATEOPERATOR" VARCHAR2(128 CHAR), 
	"REMARK" VARCHAR2(1000), 
	 CONSTRAINT "CLAIMREJECTED_PK" PRIMARY KEY ("INSKEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLIDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 