-- SUMBER: DDL_Script_ClaimNonProp.xls (reverse-engineer Toad)
-- UNTUK DIBACA, BUKAN UNTUK DIJALANKAN. Klausa DROP/ALTER-DROP tidak boleh dieksekusi.


  CREATE TABLE "POOLDATA"."REINSURANCETYPE" 
   (	"ID" VARCHAR2(100), 
	"NOTE" VARCHAR2(100), 
	"TYPE" VARCHAR2(100), 
	"SOANOTE" VARCHAR2(100), 
	"CODE" VARCHAR2(100), 
	"FLAG" VARCHAR2(100), 
	"USERID" VARCHAR2(100), 
	"TGLUPDATE" VARCHAR2(100), 
	"NOURUT" VARCHAR2(100), 
	"GROUPTYPE" VARCHAR2(100)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "POOLMASTER" 