-- LANGKAH-WO-BENEFITLIFE.md bab Pemulihan - BACA-SAJA. Penentu keadaan sesudah 942-945 gagal di tengah; bandingkan
-- dengan tabel keputusan K0-K4 di dokumen. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 250 PAGESIZE 100
PROMPT 1. Objek, kolom, catatan T_MIGRASI, dan menu
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'BENEFIT_LIFE')                 AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_BENEFIT_LIFE')             AS ADA_SUMBER,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'BENEFIT_LIFE')               AS ADA_TARGET,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('BENEFIT_LIFE', 'M_BENEFIT_LIFE')
      AND COLUMN_NAME = 'BENEFIT')
    - (SELECT COUNT(*) FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'BENEFIT_LIFE')             AS ADA_BENEFIT,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('BENEFIT_LIFE', 'M_BENEFIT_LIFE')
      AND COLUMN_NAME = 'JSONDATA')                                                                            AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'BENEFIT_LIFE')    AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '942_benefit_life_ganti_nama')                        AS T942,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '943_benefit_life_kolom')                             AS T943,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '944_benefit_life_satu_tabel')                        AS T944,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '945_m_nav_menu_benefitlife')                         AS T945,
  (SELECT COUNT(*) FROM POOLDATA.M_NAV_MENU WHERE KODE = 'benefitlife')                                       AS ADA_MENU
FROM DUAL;
PROMPT 2. Isi kolom (ORA-00904 / ORA-00942 = kolom / tabel belum ada pada nama itu, wajar)
SELECT COUNT(*) AS N, COUNT(BENEFIT) AS N_BENEFIT FROM POOLDATA.BENEFIT_LIFE;
