-- LANGKAH-WO-BENEFITLIFE.md (a) P2 acuan dan (c)0 - BACA-SAJA. Angka acuan SEBELUM 942-945, dibaca lewat VIEW lama
-- BENEFIT_LIFE (sumber kebenaran = JSONDATA). Dijalankan DUA kali: sesaat SEBELUM cadangan P3 dan TEPAT SEBELUM
-- -migrate; kedua keluaran harus SAMA (beda = ada penulis yang masih hidup - ulangi P1-P3). Keluaran ditambahkan ke
-- benefit_acuan.txt. Nilai kunci pxCreateOperator / pxCreateOpName TIDAK pernah dicetak.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL benefit_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah dan ID tertinggi (pembanding WO 08-10-2026: 10 baris, ID 100001-100011 tanpa 100003) + sequence (last_number 12)
SELECT COUNT(*) AS N, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI, MIN(ID) AS ID_TERENDAH FROM POOLDATA.M_BENEFIT_LIFE;
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME = 'M_BENEFIT_LIFE_SEQ';
PROMPT 2. Sidik isi lewat view: cacah tidak-NULL + jumlah ORA_HASH(ID || '|' || Benefit) per baris
SELECT COUNT(*) AS N, COUNT(BENEFIT) AS N_BENEFIT, SUM(ORA_HASH(ID || '|' || BENEFIT)) AS H_BARIS,
       MAX(LENGTHB(BENEFIT)) AS MAKS_BYTE
  FROM POOLDATA.BENEFIT_LIFE;
PROMPT 3. Nilai yang melewati lebar kolom tujuan VARCHAR2(200) (harus NOL baris; bila ada: BERHENTI)
SELECT ID FROM POOLDATA.BENEFIT_LIFE WHERE LENGTHB(BENEFIT) > 200;
PROMPT 4. Definisi asli: kolom (NULLABLE JSONDATA - dipakai jalur mundur) dan constraint (PK SYS_C009031, IS JSON)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_BENEFIT_LIFE', 'BENEFIT_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_BENEFIT_LIFE' ORDER BY CONSTRAINT_NAME;
PROMPT 5. Objek bernama BENEFIT_LIFE / M_BENEFIT_LIFE*, dependensi, dan grant (pembanding: VIEW + TABLE + SEQUENCE + PROCEDURE; dependensi hanya view dan prosedur Pega; nol grant)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND (OBJECT_NAME IN ('BENEFIT_LIFE', 'PEGA_M_BENEFIT_LIFE') OR OBJECT_NAME LIKE 'M\_BENEFIT\_LIFE%' ESCAPE '\')
 ORDER BY OBJECT_NAME;
SELECT OWNER, NAME, TYPE FROM SYS.ALL_DEPENDENCIES
 WHERE REFERENCED_OWNER = 'POOLDATA' AND REFERENCED_NAME IN ('M_BENEFIT_LIFE', 'BENEFIT_LIFE') ORDER BY OWNER, NAME;
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS
 WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME IN ('M_BENEFIT_LIFE', 'BENEFIT_LIFE');
SPOOL OFF
