-- LANGKAH-WO-BENEFITLIFE.md (c) - BACA-SAJA, SESUDAH 942-945. Angka harus sama dengan benefit_acuan.txt; lalu CSV
-- sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL benefit_verifikasi.txt
PROMPT 1. Kolom akhir BENEFIT_LIFE: ID VARCHAR2(10) NOT NULL, BENEFIT VARCHAR2(200); nol JSONDATA; nol kolom setengah terbuang
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'BENEFIT_LIFE' ORDER BY COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'BENEFIT_LIFE';
PROMPT 2. Objek: BENEFIT_LIFE = TABLE (bukan VIEW); M_BENEFIT_LIFE tidak ada; sequence tetap; prosedur Pega INVALID (K3)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('BENEFIT_LIFE', 'M_BENEFIT_LIFE', 'M_BENEFIT_LIFE_SEQ', 'PEGA_M_BENEFIT_LIFE')
 ORDER BY OBJECT_NAME;
SELECT COUNT(*) AS N_VIEW FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'BENEFIT_LIFE';
PROMPT 3. Cacah (pembanding 10), ID tertinggi, dan sidik = acuan (a) kueri 1 dan 2
SELECT COUNT(*) AS N, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI, MIN(ID) AS ID_TERENDAH FROM POOLDATA.BENEFIT_LIFE;
SELECT COUNT(*) AS N, COUNT(BENEFIT) AS N_BENEFIT, SUM(ORA_HASH(ID || '|' || BENEFIT)) AS H_BARIS,
       MAX(LENGTHB(BENEFIT)) AS MAKS_BYTE
  FROM POOLDATA.BENEFIT_LIFE;
PROMPT 4. Constraint: PK SYS_C009031 tetap ada; ENSURE_M_BENEFIT_LIFE_JSON hilang
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'BENEFIT_LIFE' ORDER BY CONSTRAINT_NAME;
PROMPT 5. T_MIGRASI (empat baris 942-945) dan baris menu (benefitlife, Benefit, MASTER TREATY, 12, 1)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI WHERE NAMA IN ('942_benefit_life_ganti_nama',
  '943_benefit_life_kolom', '944_benefit_life_satu_tabel', '945_m_nav_menu_benefitlife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI, STATUS_AKTIF FROM POOLDATA.M_NAV_MENU
 WHERE KODE IN ('ririsklife', 'benefitlife') ORDER BY URUTAN;
SPOOL OFF
PROMPT 6. CSV sesudah (bentuk sama dengan BENEFIT_LIFE_SEBELUM.csv)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL BENEFIT_LIFE_SESUDAH.csv
SELECT ID, BENEFIT FROM POOLDATA.BENEFIT_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: benefit_verifikasi.txt, BENEFIT_LIFE_SESUDAH.csv
