-- Jalur mundur 600 - buang kolom khas NONPROP dari T_GENERAL_CLAIM.
ALTER TABLE {skema}.T_GENERAL_CLAIM DROP (
  BUSINESS_OLD_ID, MASTER_ID_TO, POLICY_COB, REINSURANCE_SLIP, CLAIM_NO_CEDING, CIRCUMSTANCES, SUPPORTING_DOCUMENT, DEDUCTIBLE_MIN_MAX, IS_TPL, TPL_FORMAT, TPL_TYPE, TPL_PCT, IS_SAVE_TO_OS, WAITING_ACTUAL_PREMIUM, STATUS_CASE, IS_REJECT, KOMITE_NO, FLAG_PRINT_PLA, RECEIVER_CURRENCY, RECEIVER_BANK_NAME2, RECEIVER_BANK_BRANCH2, RECEIVER_ACCOUNT_NO2, RECEIVER_SWIFT_CODE2, RECEIVER_BANK_ID2, RECEIVER_CURRENCY2
)
/
