-- Jalur mundur 601 - buang kolom khas NONPROP dari T_CLAIM_INTEREST.
ALTER TABLE {skema}.T_CLAIM_INTEREST DROP (
  IS_TPL, TPL_FORMAT, TPL_TYPE, TPL_PCT, TPL_AMOUNT, TPL_MIN_MAX, TPL_CURRENCY, TPL_NOTE, TPL_TYPE2, TPL_PCT2, TPL_AMOUNT2, TPL_MIN_MAX2, TPL_CURRENCY2
)
/
