-- Jalur mundur 602 - buang kolom khas NONPROP dari T_CLAIM_CLAIM_AMOUNT.
ALTER TABLE {skema}.T_CLAIM_CLAIM_AMOUNT DROP (
  TPL, ADJUSTER_FEE, SALVAGE, OTHERS_FEE, PROPORTION_PCT, CLAIM_AMOUNT_CEDANT, CLAIM_AMOUNT_ADJUST, TSI_VALUE, IS_LOCKED
)
/
