-- Jalur mundur 605 - buang kolom khas NONPROP dari T_CLAIM_ADJUSTMENT.
ALTER TABLE {skema}.T_CLAIM_ADJUSTMENT DROP (
  INTERIM_INDEX, BANK_NAME2, BANK_BRANCH2, BANK_ACCOUNT_NO2, SWIFT_CODE2, BANK_ID2, BANK_CURRENCY2, FLAG_ERROR_KASIR
)
/
