-- Jalur mundur 607 - buang kolom khas NONPROP dari T_CLAIM_ADJ_QUOTA_SHARE.
ALTER TABLE {skema}.T_CLAIM_ADJ_QUOTA_SHARE DROP (
  PREMIUM_SPREADED, ADJUSTER_FEE, SALVAGE, OTHERS_FEE, TOTAL_CLAIM, NET_CLAIM
)
/
