-- 608 - T_CLAIM_NP_LOSS_ALLOC <- `ClaimData.CNPSpreadLoss` (klaim, CLAIM_ID) dan `AdjustmentList(n).CNPSpreadLoss`
-- (akseptasi, ADJUSTMENT_ID): grid "Loss Allocation" + To XOL (Section OutstandingClaim / AdjustmentDetailNP).
-- Tabel baru khas XoL (OQ-CNP-06, docs/STRUKTUR-TABEL-CLAIM-NON-PROP.md). ID dari SEQ_T_CLAIM (claimprop 533).
-- Kolom = katalog `models/katalog.go`. NOL COMMIT. -migrate oleh work owner.
CREATE TABLE {skema}.T_CLAIM_NP_LOSS_ALLOC (
  ID                   VARCHAR2(32) NOT NULL,
  CLAIM_ID             VARCHAR2(32),
  ADJUSTMENT_ID        VARCHAR2(32),
  NOURUT               NUMBER(5) NOT NULL,
  CURRENCY_ID          VARCHAR2(64),
  CURRENCY_NAME        VARCHAR2(64),
  TREATY_NAME          VARCHAR2(255),
  CLAIM_PERCENTAGE     NUMBER(38,10),
  CLAIM_AMOUNT_ADJUST  NUMBER(38,10),
  ADJUSTER_FEE         NUMBER(38,10),
  SALVAGE              NUMBER(38,10),
  OTHERS_FEE           NUMBER(38,10),
  TO_XOL               VARCHAR2(16),
  IS_LOCKED            VARCHAR2(16),
  CONSTRAINT PK_CLAIM_NP_LOSS PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_NP_LOSS_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES {skema}.T_GENERAL_CLAIM (ID) ON DELETE CASCADE,
  CONSTRAINT FK_CLAIM_NP_LOSS_ADJ FOREIGN KEY (ADJUSTMENT_ID) REFERENCES {skema}.T_CLAIM_ADJUSTMENT (ID) ON DELETE CASCADE,
  CONSTRAINT CK_CLAIM_NP_LOSS_INDUK CHECK ((CLAIM_ID IS NOT NULL AND ADJUSTMENT_ID IS NULL) OR (CLAIM_ID IS NULL AND ADJUSTMENT_ID IS NOT NULL)),
  CONSTRAINT UQ_CLAIM_NP_LOSS_NOURUT UNIQUE (CLAIM_ID, ADJUSTMENT_ID, NOURUT)
)
/
-- Indeks induk kedua (kaskade hapus akseptasi; CLAIM_ID tercakup awal UQ).
CREATE INDEX {skema}.IX_CLAIM_NP_LOSS_ADJ ON {skema}.T_CLAIM_NP_LOSS_ALLOC (ADJUSTMENT_ID)
/
