-- LANGKAH-WO-COVERLIFE.md (a) P1 - BACA-SAJA. Sesi yang masih memegang kunci DML pada M_COVER_LIFE, dan
-- sesi yang masih tersambung. Jalankan SESUDAH Pega (penyimpan Cover / prosedur PEGA_M_COVER_LIFE) dan
-- backend :8080 dihentikan. Hasil yang diharapkan: kueri 1 NOL baris. Akun POOLDATA DEV TIDAK punya hak
-- V$LOCKED_OBJECT: ORA-00942 di sini = minta DBA menjalankan cov_p1_kunci_dba.sql.
SET LINESIZE 250 PAGESIZE 100
COLUMN USERNAME FORMAT A20
COLUMN OSUSER FORMAT A20
COLUMN MACHINE FORMAT A30
COLUMN PROGRAM FORMAT A30
COLUMN MODULE FORMAT A30
COLUMN OBJECT_NAME FORMAT A24
PROMPT 1. Kunci DML pada M_COVER_LIFE (harus nol baris)
SELECT s.SID, s.SERIAL#, s.USERNAME, s.OSUSER, s.MACHINE, s.PROGRAM, s.MODULE, s.STATUS, o.OBJECT_NAME, l.LOCKED_MODE
  FROM V$LOCKED_OBJECT l
  JOIN SYS.ALL_OBJECTS o ON o.OBJECT_ID = l.OBJECT_ID
  JOIN V$SESSION s ON s.SID = l.SESSION_ID
 WHERE o.OWNER = 'POOLDATA' AND o.OBJECT_NAME = 'M_COVER_LIFE';
PROMPT 2. Sesi yang tersambung sebagai POOLDATA (kenali Pega / backend; sesi SQL*Plus ini sendiri ikut tampil)
SELECT SID, SERIAL#, USERNAME, OSUSER, MACHINE, PROGRAM, MODULE, STATUS, LOGON_TIME
  FROM V$SESSION WHERE USERNAME = 'POOLDATA' ORDER BY LOGON_TIME;
