-- LANGKAH-WO-COVERLIFE.md (c) - BACA-SAJA, SESUDAH 085-086 dan 957. Angka harus sama dengan cov_acuan.txt; lalu CSV
-- sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL cov_verifikasi.txt
PROMPT 1. M_COVER_LIFE = TABLE dengan kolom PERSIS ID VARCHAR2(10) NOT NULL, COVER VARCHAR2(200), NOTE VARCHAR2(1000) (urutan view lama); nol JSONDATA
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_COVER_LIFE' ORDER BY COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_COVER_LIFE';
PROMPT 2. Objek: M_COVER_LIFE = TABLE; objek COVER_LIFE TIDAK ADA (nol baris); sequence tetap; prosedur Pega INVALID (C2)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('COVER_LIFE', 'M_COVER_LIFE', 'M_COVER_LIFE_SEQ', 'PEGA_M_COVER_LIFE')
 ORDER BY OBJECT_NAME;
SELECT COUNT(*) AS N_OBJEK_COVER_LIFE FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'COVER_LIFE';
PROMPT 3. Cacah (pembanding 4), ID tertinggi, dan sidik = acuan (a) P2 kueri 2
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_COVER_LIFE;
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(COVER) AS N_COVER, COUNT(NOTE) AS N_NOTE,
       SUM(ORA_HASH(ID || '|' || COVER || '|' || NOTE)) AS H_BARIS
  FROM POOLDATA.M_COVER_LIFE;
PROMPT 4. Constraint: PK SYS_C009203 (P, ENABLED) ada; ENSURE_M_COVER_LIFE_JSON hilang
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_COVER_LIFE' ORDER BY CONSTRAINT_NAME;
PROMPT 5. T_MIGRASI (tiga baris 085, 086, 957) dan baris menu (coverlife, Cover Life, MASTER TREATY, 16, 1; STATUS_AKTIF = causeoflosslife)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI
 WHERE NAMA IN ('085_cover_life_kolom', '086_cover_life_satu_tabel', '957_menu_coverlife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI, STATUS_AKTIF FROM POOLDATA.M_NAV_MENU
 WHERE KODE IN ('causeoflosslife', 'coverlife') ORDER BY URUTAN;
SPOOL OFF
PROMPT 6. CSV sesudah (bentuk sama dengan COVER_LIFE_SEBELUM.csv)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL COVER_LIFE_SESUDAH.csv
SELECT ID, COVER, NOTE FROM POOLDATA.M_COVER_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: cov_verifikasi.txt, COVER_LIFE_SESUDAH.csv
