-- LANGKAH-WO-COVERLIFE.md (a) P2 acuan dan (c)0 - BACA-SAJA. Angka acuan SEBELUM 085-086 / 957, dibaca lewat VIEW lama
-- COVER_LIFE (sumber kebenaran = JSONDATA). Dijalankan DUA kali: sesaat SEBELUM cadangan P3 dan TEPAT SEBELUM -migrate;
-- kedua keluaran harus SAMA (beda = ada penulis yang masih hidup - ulangi P1-P3). Keluaran ditambahkan ke
-- cov_acuan.txt. Kunci px* TIDAK pernah dicetak.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL cov_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah (pembanding WO 08-10-2026: 4) dan ID tertinggi + sequence (last_number 5)
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_COVER_LIFE;
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME = 'M_COVER_LIFE_SEQ';
PROMPT 2. Sidik isi lewat view: cacah tidak-NULL + jumlah ORA_HASH per baris (pembanding: N 4, N_COVER 4, N_NOTE 0)
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(COVER) AS N_COVER, COUNT(NOTE) AS N_NOTE,
       SUM(ORA_HASH(ID || '|' || COVER || '|' || NOTE)) AS H_BARIS
  FROM POOLDATA.COVER_LIFE;
PROMPT 3. Nilai yang melewati lebar kolom tujuan (harus NOL baris; bila ada: BERHENTI) dan panjang maksimum (17 / -)
SELECT ID FROM POOLDATA.COVER_LIFE WHERE LENGTHB(ID) > 10 OR LENGTHB(COVER) > 200 OR LENGTHB(NOTE) > 1000;
SELECT MAX(LENGTHB(COVER)) AS MAKS_COVER, MAX(LENGTHB(NOTE)) AS MAKS_NOTE FROM POOLDATA.COVER_LIFE;
PROMPT 4. Definisi asli: kolom (NULLABLE JSONDATA - dipakai jalur mundur) dan constraint (PK SYS_C009203, IS JSON)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_COVER_LIFE', 'COVER_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_COVER_LIFE' ORDER BY CONSTRAINT_NAME;
SELECT TEXT FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'COVER_LIFE';
PROMPT 5. Objek, dependensi, grant (pembanding: VIEW + TABLE + SEQUENCE + PROCEDURE; dependensi hanya view + prosedur Pega; nol grant)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('COVER_LIFE', 'M_COVER_LIFE', 'M_COVER_LIFE_SEQ', 'PEGA_M_COVER_LIFE')
 ORDER BY OBJECT_NAME;
SELECT OWNER, NAME, TYPE FROM SYS.ALL_DEPENDENCIES
 WHERE REFERENCED_OWNER = 'POOLDATA' AND REFERENCED_NAME IN ('M_COVER_LIFE', 'COVER_LIFE') ORDER BY OWNER, NAME;
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS
 WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME IN ('M_COVER_LIFE', 'COVER_LIFE');
PROMPT 6. Nomor 085-089 / 957 belum dipakai di T_MIGRASI (K0; harus NOL baris)
SELECT NAMA FROM POOLDATA.T_MIGRASI WHERE SUBSTR(NAMA, 1, 3) BETWEEN '085' AND '089' OR SUBSTR(NAMA, 1, 3) = '957';
SPOOL OFF
