// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/komiteclaimfacin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import komiteclaimfacin "nusantarare/modul/komiteclaimfacin/backend"

func init() { daftarkan(komiteclaimfacin.Pendaftaran()) }
