// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/claimfacin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import claimfacin "nusantarare/modul/claimfacin/backend"

func init() { daftarkan(claimfacin.Pendaftaran()) }
