// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/causeoflosslife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import causeoflosslife "nusantarare/modul/causeoflosslife/backend"

func init() { daftarkan(causeoflosslife.Pendaftaran()) }
