// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/mastercity/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import mastercity "nusantarare/modul/mastercity/backend"

func init() { daftarkan(mastercity.Pendaftaran()) }
