// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/nbtreatyin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import nbtreatyin "nusantarare/modul/nbtreatyin/backend"

func init() { daftarkan(nbtreatyin.Pendaftaran()) }
