// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterobjectitemtype/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterobjectitemtype "nusantarare/modul/masterobjectitemtype/backend"

func init() { daftarkan(masterobjectitemtype.Pendaftaran()) }
