// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/edmtreatyin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import edmtreatyin "nusantarare/modul/edmtreatyin/backend"

func init() { daftarkan(edmtreatyin.Pendaftaran()) }
