// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/endorsementlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import endorsementlife "nusantarare/modul/endorsementlife/backend"

func init() { daftarkan(endorsementlife.Pendaftaran()) }
