// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/claimnonprop/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import claimnonprop "nusantarare/modul/claimnonprop/backend"

func init() { daftarkan(claimnonprop.Pendaftaran()) }
