// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatydescription/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatydescription "nusantarare/modul/treatydescription/backend"

func init() { daftarkan(treatydescription.Pendaftaran()) }
