// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/claimlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import claimlife "nusantarare/modul/claimlife/backend"

func init() { daftarkan(claimlife.Pendaftaran()) }
