// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/adjusterconsultant/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import adjusterconsultant "nusantarare/modul/adjusterconsultant/backend"

func init() { daftarkan(adjusterconsultant.Pendaftaran()) }
