// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/coverlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import coverlife "nusantarare/modul/coverlife/backend"

func init() { daftarkan(coverlife.Pendaftaran()) }
