// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/komiteclaimnonprop/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import komiteclaimnonprop "nusantarare/modul/komiteclaimnonprop/backend"

func init() { daftarkan(komiteclaimnonprop.Pendaftaran()) }
