// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatyexchangeyearly/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatyexchangeyearly "nusantarare/modul/treatyexchangeyearly/backend"

func init() { daftarkan(treatyexchangeyearly.Pendaftaran()) }
