// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masteraccumulation/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masteraccumulation "nusantarare/modul/masteraccumulation/backend"

func init() { daftarkan(masteraccumulation.Pendaftaran()) }
