// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/aggregate/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import aggregate "nusantarare/modul/aggregate/backend"

func init() { daftarkan(aggregate.Pendaftaran()) }
