// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/bordereaux/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import bordereaux "nusantarare/modul/bordereaux/backend"

func init() { daftarkan(bordereaux.Pendaftaran()) }
