// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/companydetail/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import companydetail "nusantarare/modul/companydetail/backend"

func init() { daftarkan(companydetail.Pendaftaran()) }
