// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/ricommlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import ricommlife "nusantarare/modul/ricommlife/backend"

func init() { daftarkan(ricommlife.Pendaftaran()) }
