// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatygroupojk/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatygroupojk "nusantarare/modul/treatygroupojk/backend"

func init() { daftarkan(treatygroupojk.Pendaftaran()) }
