// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterdistrict/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterdistrict "nusantarare/modul/masterdistrict/backend"

func init() { daftarkan(masterdistrict.Pendaftaran()) }
