// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/komiteclaimprop/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import komiteclaimprop "nusantarare/modul/komiteclaimprop/backend"

func init() { daftarkan(komiteclaimprop.Pendaftaran()) }
