// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterprovince/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterprovince "nusantarare/modul/masterprovince/backend"

func init() { daftarkan(masterprovince.Pendaftaran()) }
