// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterczone/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterczone "nusantarare/modul/masterczone/backend"

func init() { daftarkan(masterczone.Pendaftaran()) }
