// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/ririsklife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import ririsklife "nusantarare/modul/ririsklife/backend"

func init() { daftarkan(ririsklife.Pendaftaran()) }
