// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/reinsurancetype/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import reinsurancetype "nusantarare/modul/reinsurancetype/backend"

func init() { daftarkan(reinsurancetype.Pendaftaran()) }
