// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masternation/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masternation "nusantarare/modul/masternation/backend"

func init() { daftarkan(masternation.Pendaftaran()) }
