// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/riratelife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import riratelife "nusantarare/modul/riratelife/backend"

func init() { daftarkan(riratelife.Pendaftaran()) }
