// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatyin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatyin "nusantarare/modul/treatyin/backend"

func init() { daftarkan(treatyin.Pendaftaran()) }
