// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/accounts/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import accounts "nusantarare/modul/accounts/backend"

func init() { daftarkan(accounts.Pendaftaran()) }
