// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/diseaselife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import diseaselife "nusantarare/modul/diseaselife/backend"

func init() { daftarkan(diseaselife.Pendaftaran()) }
