// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/planlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import planlife "nusantarare/modul/planlife/backend"

func init() { daftarkan(planlife.Pendaftaran()) }
