// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/claimprop/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import claimprop "nusantarare/modul/claimprop/backend"

func init() { daftarkan(claimprop.Pendaftaran()) }
