// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatygroup/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatygroup "nusantarare/modul/treatygroup/backend"

func init() { daftarkan(treatygroup.Pendaftaran()) }
