// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/businessgroup/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import businessgroup "nusantarare/modul/businessgroup/backend"

func init() { daftarkan(businessgroup.Pendaftaran()) }
