// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masteraccumulatedtype/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masteraccumulatedtype "nusantarare/modul/masteraccumulatedtype/backend"

func init() { daftarkan(masteraccumulatedtype.Pendaftaran()) }
