// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterdata/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterdata "nusantarare/modul/masterdata/backend"

func init() { daftarkan(masterdata.Pendaftaran()) }
