-- LANGKAH-WO-CAUSEOFLOSSLIFE.md (c) - BACA-SAJA, SESUDAH 090-092 dan 955. Angka harus sama dengan col_acuan.txt; lalu
-- CSV sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL col_verifikasi.txt
PROMPT 1. Kolom akhir CAUSEOFLOSS_LIFE: ID VARCHAR2(10) NOT NULL, CAUSEOFLOSS VARCHAR2(200) NULLABLE; nol JSONDATA
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'CAUSEOFLOSS_LIFE' ORDER BY COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'CAUSEOFLOSS_LIFE';
PROMPT 2. Objek: CAUSEOFLOSS_LIFE = TABLE; M_CAUSEOFLOSS_LIFE tidak ada; nol VIEW; sequence tetap; prosedur Pega INVALID (K3)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('CAUSEOFLOSS_LIFE', 'M_CAUSEOFLOSS_LIFE', 'M_CAUSEOFLOSS_LIFE_SEQ',
       'PEGA_M_CAUSEOFLOSS_LIFE') ORDER BY OBJECT_NAME;
SELECT COUNT(*) AS N_VIEW FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'CAUSEOFLOSS_LIFE';
PROMPT 3. Cacah (pembanding 4), ID tertinggi, dan sidik = acuan (a) P2 kueri 2
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.CAUSEOFLOSS_LIFE;
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(CAUSEOFLOSS) AS N_CAUSEOFLOSS,
       SUM(ORA_HASH(ID || '|' || CAUSEOFLOSS)) AS H_BARIS
  FROM POOLDATA.CAUSEOFLOSS_LIFE;
PROMPT 4. Constraint: PK SYS_C008825 (P, ENABLED) ada; ENSURE_M_CAUSEOFLOSS_LIFE_JSON hilang
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'CAUSEOFLOSS_LIFE' ORDER BY CONSTRAINT_NAME;
PROMPT 5. T_MIGRASI (empat baris 090, 091, 092, 955) dan baris menu (causeoflosslife, Cause Of Loss Life, MASTER TREATY, 14, 1)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI WHERE NAMA IN ('090_causeofloss_life_ganti_nama',
  '091_causeofloss_life_kolom', '092_causeofloss_life_satu_tabel', '955_menu_causeoflosslife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI, STATUS_AKTIF FROM POOLDATA.M_NAV_MENU
 WHERE KODE IN ('planlife', 'causeoflosslife') ORDER BY URUTAN;
PROMPT 6. Kueri pemilih Cause Of Loss modul masterproductnamelife (cari kosong = '%') tetap jalan - 3 baris urut ID (100001 NULL tidak cocok LIKE, sama seperti lewat view lama)
SELECT ID, CAUSEOFLOSS FROM POOLDATA.CAUSEOFLOSS_LIFE WHERE UPPER(CAUSEOFLOSS) LIKE '%' ORDER BY ID ASC;
SPOOL OFF
PROMPT 7. CSV sesudah (bentuk sama dengan CAUSEOFLOSS_LIFE_SEBELUM.csv)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL CAUSEOFLOSS_LIFE_SESUDAH.csv
SELECT ID, CAUSEOFLOSS FROM POOLDATA.CAUSEOFLOSS_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: col_verifikasi.txt, CAUSEOFLOSS_LIFE_SESUDAH.csv
