-- LANGKAH-WO-CAUSEOFLOSSLIFE.md (a) P1 - versi DBA, BACA-SAJA (akun POOLDATA tidak punya hak V$LOCKED_OBJECT).
-- Dijalankan DBA (SELECT_CATALOG_ROLE / SELECT ANY DICTIONARY). Hasil yang diharapkan: NOL baris di kedua kueri.
SET LINESIZE 200 PAGESIZE 100
COLUMN OWNER FORMAT A12
COLUMN NAME FORMAT A24
SELECT SESSION_ID, OWNER, NAME, MODE_HELD, MODE_REQUESTED
  FROM DBA_DML_LOCKS
 WHERE OWNER = 'POOLDATA' AND NAME = 'M_CAUSEOFLOSS_LIFE';
SELECT s.SID, s.SERIAL#, s.USERNAME, s.PROGRAM, s.MODULE, s.STATUS
  FROM V$LOCKED_OBJECT l
  JOIN DBA_OBJECTS o ON o.OBJECT_ID = l.OBJECT_ID
  JOIN V$SESSION s ON s.SID = l.SESSION_ID
 WHERE o.OWNER = 'POOLDATA' AND o.OBJECT_NAME = 'M_CAUSEOFLOSS_LIFE';
