-- 520 - kolom khas lini PROP di T_GENERAL_CLAIM (header klaim, tabel bersama milik Claim Life).
--
-- Keputusan work owner 07-10-2026 ("Tabel bersama"): data header klaim Claim Prop - medan skalar
-- pyWorkPage.ClaimData / pyWorkPage.TreatyInMaster / penanda pyWorkPage yang dibaca rule terjangkau -
-- disimpan di T_GENERAL_CLAIM sebagai kolom TAMBAHAN; baris kolomnya dicatat di STRUKTUR Claim Life.
-- Seluruh kolom nullable (kolom khas satu lini, STRUKTUR-TABEL-CLAIM-PROP.md T4); wajib-isi di Go.
-- Nol MODIFY / DROP atas kolom Claim Life yang sudah ada. Kolom Claim Life yang dipakai ulang apa adanya:
-- CLAIM_NO (NoClaim), POLICY_NO (PolicyData.PolicyNo), BUSINESS_CODE, BUSINESS_NAME, KATASTROFE_NOTE, PY_ID.
-- STS_KATASTROFE tidak dipakai: lebarnya VARCHAR2(8), nilai PROP "Non-Catastrophe" 15 karakter - maka
-- CATASTROPHE_STATUS (AC 122: satu ejaan, satu enum).
-- Uang, persen, dan kurs NUMBER(38,10) (keputusan work owner 07-10-2026).
ALTER TABLE {skema}.T_GENERAL_CLAIM ADD (
  SUMBER                      VARCHAR2(8),
  MASTER_ID                   VARCHAR2(64),
  TREATY_NAME                 VARCHAR2(500),
  TREATY_GROUP_ID             VARCHAR2(64),
  TREATY_GROUP_NAME           VARCHAR2(255),
  PROPORTION_TYPE             VARCHAR2(64),
  START_DATE_TREATY           DATE,
  END_DATE_TREATY             DATE,
  YEAR_OF_ACCOUNT             VARCHAR2(16),
  RNM_SHARE_PCT               NUMBER(38,10),
  CLAIM_NO_TEMP               VARCHAR2(64),
  POLICY_START_DATE           DATE,
  POLICY_END_DATE             DATE,
  QUARTER                     VARCHAR2(16),
  YEAR_OF_QUARTAL             VARCHAR2(16),
  TREATY_YEAR                 VARCHAR2(16),
  POLICY_NO_CEDING            VARCHAR2(255),
  INSURED_NAME                VARCHAR2(500),
  PLA_NO_CEDING               VARCHAR2(255),
  PLA_NO_SOB                  VARCHAR2(255),
  PERIOD_POLICY_TBA           VARCHAR2(16),
  DATE_OF_LOSS                DATE,
  REPORT_DATE                 DATE,
  DATE_RECEIVED               DATE,
  REPORTER_NAME               VARCHAR2(255),
  REPORTER_PHONE              VARCHAR2(64),
  REPORT_TYPE                 VARCHAR2(16),
  REPORTER_STATUS             VARCHAR2(16),
  INSURED_RELATIONSHIP_OTHERS VARCHAR2(500),
  REPORT_ADDRESS              VARCHAR2(2000),
  CATASTROPHE_STATUS          VARCHAR2(32),
  NON_CATASTROPHE_TYPE        VARCHAR2(32),
  CATASTROPHE_ID              VARCHAR2(100),
  CAUSE_OF_LOSS               VARCHAR2(1000),
  CAUSE_OF_LOSS_ID            VARCHAR2(100),
  CONSULTANT_ID               VARCHAR2(100),
  CONSULTANT_NAME             VARCHAR2(500),
  ADJUSTER_ID                 VARCHAR2(100),
  ADJUSTER_NAME               VARCHAR2(500),
  REPORT_DESCRIPTION          VARCHAR2(4000),
  LOCATION_OF_LOSS            VARCHAR2(4000),
  OCCUPATION                  VARCHAR2(4000),
  PROVINCE                    VARCHAR2(255),
  PROVINCE_ID                 VARCHAR2(64),
  POSTAL_CODE                 VARCHAR2(16),
  RW                          VARCHAR2(255),
  RW_ID                       VARCHAR2(64),
  DISTRICT                    VARCHAR2(255),
  DISTRICT_ID                 VARCHAR2(64),
  CITY                        VARCHAR2(255),
  CITY_ID                     VARCHAR2(64),
  INSURED_INTEREST            VARCHAR2(4000),
  SHARE_CEDING                NUMBER(38,10),
  DEDUCTIBLE_TYPE             VARCHAR2(16),
  DEDUCTIBLE_FORM_TYPE        VARCHAR2(16),
  DEDUCTIBLE_CURRENCY_ID      VARCHAR2(64),
  DEDUCTIBLE_PCT              NUMBER(38,10),
  DEDUCTIBLE_BASIS            VARCHAR2(16),
  TSI_DEDUCTIBLE              NUMBER(38,10),
  DEDUCTIBLE_VALUE            NUMBER(38,10),
  NET_DEDUCTIBLE_VALUE        NUMBER(38,10),
  IS_OUTSTANDING              VARCHAR2(16),
  IS_ACCEPTATION              VARCHAR2(16),
  IS_CFS                      VARCHAR2(16),
  RE_CFS                      VARCHAR2(16),
  IS_REALISATION              VARCHAR2(16),
  AKTIF_BUTTON                VARCHAR2(16),
  IS_PLA                      VARCHAR2(16),
  NO_PLA                      VARCHAR2(64),
  REMARK                      VARCHAR2(4000),
  REMARK_CLOSE                VARCHAR2(4000),
  PAYABLE                     VARCHAR2(16),
  PAYABLE_TO                  VARCHAR2(500),
  DLA_NO_CEDING               VARCHAR2(255),
  DLA_NO_SOB                  VARCHAR2(255),
  MARKETING_ID                VARCHAR2(64),
  MARKETING_CLIENT_ID         VARCHAR2(64),
  MARKETING_CLIENT_NAME       VARCHAR2(500),
  MARKETING_TEAM_GROUP        VARCHAR2(64),
  MARKETING_BRANCH_ID         VARCHAR2(64),
  MARKETING_BRANCH_NAME       VARCHAR2(500),
  RECEIVER_NAME               VARCHAR2(500),
  RECEIVER_BANK_NAME          VARCHAR2(500),
  RECEIVER_BANK_BRANCH        VARCHAR2(500),
  RECEIVER_ACCOUNT_NO         VARCHAR2(100),
  RECEIVER_SWIFT_CODE         VARCHAR2(64),
  RECEIVER_BANK_ID            VARCHAR2(64),
  START_DATE_ESTIMATION       DATE,
  END_DATE_ESTIMATION         DATE,
  START_DATE_ADJUSTMENT       DATE,
  IS_CLOSE_FILE               VARCHAR2(16),
  IS_RESERVED_CLAIM           VARCHAR2(16),
  IS_ANY_ACCEPTATION          VARCHAR2(16),
  IS_SUBJECTIVITY             VARCHAR2(16)
)
/
