-- Jalur mundur 520 - buang kolom khas PROP dari T_GENERAL_CLAIM.
ALTER TABLE {skema}.T_GENERAL_CLAIM DROP (
  SUMBER, MASTER_ID, TREATY_NAME, TREATY_GROUP_ID, TREATY_GROUP_NAME, PROPORTION_TYPE,
  START_DATE_TREATY, END_DATE_TREATY, YEAR_OF_ACCOUNT, RNM_SHARE_PCT, CLAIM_NO_TEMP, POLICY_START_DATE,
  POLICY_END_DATE, QUARTER, YEAR_OF_QUARTAL, TREATY_YEAR, POLICY_NO_CEDING, INSURED_NAME,
  PLA_NO_CEDING, PLA_NO_SOB, PERIOD_POLICY_TBA, DATE_OF_LOSS, REPORT_DATE, DATE_RECEIVED,
  REPORTER_NAME, REPORTER_PHONE, REPORT_TYPE, REPORTER_STATUS, INSURED_RELATIONSHIP_OTHERS, REPORT_ADDRESS,
  CATASTROPHE_STATUS, NON_CATASTROPHE_TYPE, CATASTROPHE_ID, CAUSE_OF_LOSS, CAUSE_OF_LOSS_ID, CONSULTANT_ID,
  CONSULTANT_NAME, ADJUSTER_ID, ADJUSTER_NAME, REPORT_DESCRIPTION, LOCATION_OF_LOSS, OCCUPATION,
  PROVINCE, PROVINCE_ID, POSTAL_CODE, RW, RW_ID, DISTRICT,
  DISTRICT_ID, CITY, CITY_ID, INSURED_INTEREST, SHARE_CEDING, DEDUCTIBLE_TYPE,
  DEDUCTIBLE_FORM_TYPE, DEDUCTIBLE_CURRENCY_ID, DEDUCTIBLE_PCT, DEDUCTIBLE_BASIS, TSI_DEDUCTIBLE, DEDUCTIBLE_VALUE,
  NET_DEDUCTIBLE_VALUE, IS_OUTSTANDING, IS_ACCEPTATION, IS_CFS, RE_CFS, IS_REALISATION,
  AKTIF_BUTTON, IS_PLA, NO_PLA, REMARK, REMARK_CLOSE, PAYABLE,
  PAYABLE_TO, DLA_NO_CEDING, DLA_NO_SOB, MARKETING_ID, MARKETING_CLIENT_ID, MARKETING_CLIENT_NAME,
  MARKETING_TEAM_GROUP, MARKETING_BRANCH_ID, MARKETING_BRANCH_NAME, RECEIVER_NAME, RECEIVER_BANK_NAME, RECEIVER_BANK_BRANCH,
  RECEIVER_ACCOUNT_NO, RECEIVER_SWIFT_CODE, RECEIVER_BANK_ID, START_DATE_ESTIMATION, END_DATE_ESTIMATION, START_DATE_ADJUSTMENT,
  IS_CLOSE_FILE, IS_RESERVED_CLAIM, IS_ANY_ACCEPTATION, IS_SUBJECTIVITY
)
/
