-- 525 - T_CLAIM_SPREADING <- pyWorkPage.ClaimData.SpreadingClaim (Section OutstandingClaim_Sprd grid "Spreading List" pertama).
-- TREATY_ID <- .TreatyType (kode REINSURANCETYPE baris spreading; penunjuk treaty diagram, ditegakkan di Go).
CREATE TABLE {skema}.T_CLAIM_SPREADING (
  ID                VARCHAR2(32) NOT NULL,
  CLAIM_ID          VARCHAR2(32) NOT NULL,
  NOURUT            NUMBER(5) NOT NULL,
  TREATY_ID         VARCHAR2(64),
  TREATY_NAME       VARCHAR2(255),
  SHARE_PERCENTAGE  NUMBER(38,10),
  CLAIM_SPREADED    NUMBER(38,10),
  CURRENCY_ID       VARCHAR2(64),
  CURRENCY_NAME     VARCHAR2(64),
  IS_OLD_DATA       VARCHAR2(16),
  CONSTRAINT PK_CLAIM_SPREADING PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_SPREADING_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES {skema}.T_GENERAL_CLAIM (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CLAIM_SPREADING_NOURUT UNIQUE (CLAIM_ID, NOURUT)
)
/
