-- 526 - T_CLAIM_BREAK_QS <- pyWorkPage.ClaimData.SpreadingBreakQS (Section OutstandingClaim_Sprd grid "Spreading List" kedua).
-- SEJAJAR T_CLAIM_SPREADING, bukan anaknya (CopyOldataCurr_act langkah 9 dan 10 mengulang dua daftar berbeda).
CREATE TABLE {skema}.T_CLAIM_BREAK_QS (
  ID                VARCHAR2(32) NOT NULL,
  CLAIM_ID          VARCHAR2(32) NOT NULL,
  NOURUT            NUMBER(5) NOT NULL,
  TREATY_ID         VARCHAR2(64),
  TREATY_NAME       VARCHAR2(255),
  SHARE_PERCENTAGE  NUMBER(38,10),
  CLAIM_SPREADED    NUMBER(38,10),
  CURRENCY_ID       VARCHAR2(64),
  CURRENCY_NAME     VARCHAR2(64),
  IS_OLD_DATA       VARCHAR2(16),
  CONSTRAINT PK_CLAIM_BREAK_QS PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_BREAK_QS_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES {skema}.T_GENERAL_CLAIM (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CLAIM_BREAK_QS_NOURUT UNIQUE (CLAIM_ID, NOURUT)
)
/
