-- 528 - T_CLAIM_ADJUSTMENT <- pyWorkPage.ClaimData.AdjustmentList + .DataCommitteeTreaty (Section InputAcceptation_Adjs
-- grid "Acceptation List", Section AdjustmentDetail). Baris adjustment = unit keputusan (ADR-0011).
-- ID STABIL (AC 63): disunting di tempat, tidak dihapus-sisip ulang - T_GENERAL_KOMITE.ADJUSTMENT_ID menunjuknya.
-- KOMITE_ID -> T_WORK_CLAIM.ID baris komite (TKMT-), UNIK, nullable, ditegakkan di Go (STRUKTUR K7).
-- Baris BEKU bila ada kasus komite yang menunjuknya - diturunkan, tanpa kolom penanda (AC 125).
-- PAYABLE <- .Payable: kode pilihan "Payable To" (RALAT nama STRUKTUR IS_PAYABLE - bukan penanda ya/tidak).
-- TOTAL_ESTIMATION_VALUE = potret estimasi saat baris dibuat, disimpan untuk audit, bukan pembanding (AC 40).
-- Tujuh kolom KOMITE_* <- .DataCommitteeTreaty (Section ComiteeClaimTreaty / DtlDataCommitte).
CREATE TABLE {skema}.T_CLAIM_ADJUSTMENT (
  ID                           VARCHAR2(32) NOT NULL,
  CLAIM_ID                     VARCHAR2(32) NOT NULL,
  NOURUT                       NUMBER(5) NOT NULL,
  KOMITE_ID                    VARCHAR2(32),
  ADJUSTMENT_TYPE              VARCHAR2(16),
  FORM_TYPE                    VARCHAR2(255),
  PAYMENT_TYPE                 VARCHAR2(16),
  CURRENCY_ID                  VARCHAR2(64),
  CURRENCY_NAME                VARCHAR2(64),
  KURS                         NUMBER(38,10),
  PERSEN_RNM                   NUMBER(38,10),
  LOSS_ALLOCATION_NAME         VARCHAR2(255),
  LOSS_ALLOCATION_SHARE        NUMBER(38,10),
  GROSS_ADJUSTMENT             NUMBER(38,10),
  GROSS_ADJUSTMENT_IDR         NUMBER(38,10),
  GROSS_VALUE                  NUMBER(38,10),
  INDIVIDUAL_RISK_TYPE         VARCHAR2(16),
  INDIVIDUAL_RISK_PCT          NUMBER(38,10),
  INDIVIDUAL_RISK_VALUE        NUMBER(38,10),
  INDIVIDUAL_RISK_RNM          NUMBER(38,10),
  PROPOSE_ADJUSTMENT_VALUE     NUMBER(38,10),
  ADJUSTMENT_VALUE             NUMBER(38,10),
  VALUE_ADJUSTMENT_IDR         NUMBER(38,10),
  TOTAL_ESTIMATION_VALUE       NUMBER(38,10),
  ADJUSTER_FEE_VALUE           NUMBER(38,10),
  SALVAGE_VALUE                NUMBER(38,10),
  PAYABLE                      VARCHAR2(16),
  PAYABLE_TO                   VARCHAR2(500),
  BANK_NAME                    VARCHAR2(500),
  BANK_BRANCH                  VARCHAR2(500),
  BANK_ACCOUNT_NO              VARCHAR2(100),
  SWIFT_CODE                   VARCHAR2(64),
  BANK_ID                      VARCHAR2(64),
  DLA_NO_CEDING                VARCHAR2(255),
  DLA_NO_SOB                   VARCHAR2(255),
  IS_DIRECT_TO_KASIR           VARCHAR2(16),
  STATUS_KASIR                 VARCHAR2(1000),
  ACCEPTED_NO                  VARCHAR2(64),
  ACCEPTED_DATE                DATE,
  ACCEPTANCE_STATUS            VARCHAR2(16),
  IS_APPROVED                  VARCHAR2(16),
  IS_KOMITE                    VARCHAR2(16),
  IS_SUBJECTIVITY              VARCHAR2(16),
  SUBJECTIVITY_NOTE            VARCHAR2(1000),
  NOTES                        VARCHAR2(4000),
  DLA_NO                       VARCHAR2(64),
  REMARKS_DLA                  VARCHAR2(4000),
  IS_FAC_RETRO                 VARCHAR2(16),
  IS_PRINT_ACCEPT              VARCHAR2(16),
  KOMITE_CIRCUM_CAUSE_OF_LOSS  VARCHAR2(4000),
  KOMITE_ADJUSTER_FEE          VARCHAR2(4000),
  KOMITE_REMARKS               VARCHAR2(4000),
  KOMITE_SALVAGE               VARCHAR2(4000),
  KOMITE_LEGAL_LIABILITY       VARCHAR2(4000),
  KOMITE_EXTENT_OF_LOSS        VARCHAR2(4000),
  KOMITE_OCCUPATION            VARCHAR2(4000),
  CREATED_BY                   VARCHAR2(64),
  CREATED_BY_NAME              VARCHAR2(128),
  CREATED_AT                   DATE,
  CONSTRAINT PK_CLAIM_ADJUSTMENT PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_ADJUSTMENT_CLAIM FOREIGN KEY (CLAIM_ID) REFERENCES {skema}.T_GENERAL_CLAIM (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CLAIM_ADJUSTMENT_NOURUT UNIQUE (CLAIM_ID, NOURUT),
  CONSTRAINT UQ_CLAIM_ADJUSTMENT_KOMITE UNIQUE (KOMITE_ID)
)
/
