-- 530 - T_CLAIM_ADJ_QUOTA_SHARE <- AdjustmentList(n).SpreadingQuotaShare (Section AdjustmentDetail grid "Spreading Out").
-- SEJAJAR T_CLAIM_ADJ_SPREADING (CountSpreadingADJ_Act langkah 6 dan 7 mengulang dua daftar berbeda).
-- Mata uang dan nama treaty ditampilkan sel grid "Spreading Out" (.Currency, .TreatyName) - RALAT STRUKTUR tabel 9.
CREATE TABLE {skema}.T_CLAIM_ADJ_QUOTA_SHARE (
  ID                VARCHAR2(32) NOT NULL,
  ADJUSTMENT_ID     VARCHAR2(32) NOT NULL,
  NOURUT            NUMBER(5) NOT NULL,
  TREATY_ID         VARCHAR2(64),
  TREATY_NAME       VARCHAR2(255),
  SHARE_PERCENTAGE  NUMBER(38,10),
  CLAIM_SPREADED    NUMBER(38,10),
  CURRENCY_ID       VARCHAR2(64),
  CURRENCY_NAME     VARCHAR2(64),
  CONSTRAINT PK_CLAIM_ADJ_QUOTA_SHARE PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_ADJ_QS_ADJ FOREIGN KEY (ADJUSTMENT_ID) REFERENCES {skema}.T_CLAIM_ADJUSTMENT (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CLAIM_ADJ_QS_NOURUT UNIQUE (ADJUSTMENT_ID, NOURUT)
)
/
