-- 531 - T_CLAIM_ADJ_LOSS_ALLOCATION <- AdjustmentList(n).LossAllocation (Section AdjustmentDetail grid Loss Allocation).
-- Potret SpreadingRisk saat baris adjustment lahir (AC 33; AddAdjustment_Act langkah 5, SetNameCurrency_Act langkah 11
-- menyalin seluruh halaman). Kolom mengikuti T_CLAIM_LOSS_ALLOCATION (RALAT STRUKTUR butir terbuka 9).
CREATE TABLE {skema}.T_CLAIM_ADJ_LOSS_ALLOCATION (
  ID                VARCHAR2(32) NOT NULL,
  ADJUSTMENT_ID     VARCHAR2(32) NOT NULL,
  NOURUT            NUMBER(5) NOT NULL,
  CURRENCY_ID       VARCHAR2(64),
  CURRENCY_NAME     VARCHAR2(64),
  TREATY_TYPE_ID    VARCHAR2(64),
  TREATY_NAME       VARCHAR2(255),
  SHARE_PERCENTAGE  NUMBER(38,10),
  CLAIM_SPREADED    NUMBER(38,10),
  CLAIM_ESTIMATION  NUMBER(38,10),
  KURS              NUMBER(38,10),
  CONSTRAINT PK_CLAIM_ADJ_LOSS_ALLOCATION PRIMARY KEY (ID),
  CONSTRAINT FK_CLAIM_ADJ_LA_ADJ FOREIGN KEY (ADJUSTMENT_ID) REFERENCES {skema}.T_CLAIM_ADJUSTMENT (ID) ON DELETE CASCADE,
  CONSTRAINT UQ_CLAIM_ADJ_LA_NOURUT UNIQUE (ADJUSTMENT_ID, NOURUT)
)
/
