-- Jalur mundur 532.
DROP INDEX {skema}.IDX_VS_CLAIM
/
ALTER TABLE {skema}.T_VIEW_SUGGEST DROP CONSTRAINT CK_VS_SATU_INDUK
/
ALTER TABLE {skema}.T_VIEW_SUGGEST DROP CONSTRAINT FK_VS_CLAIM
/
ALTER TABLE {skema}.T_VIEW_SUGGEST DROP COLUMN CLAIM_ID
/
