-- 536 - isi T_KATEGORI_DOC_KLAIM: 49 baris kategoriifile.xls (work owner 08-10-2026) APA ADANYA, urutan berkas
-- (FAC 18, PROP 15, NONPROP 16). Label dibiarkan seperti sumber (mis. "Acceptance Note" FAC / "AcceptanceNote"
-- PROP). Satu pernyataan sisip-banyak - atomik: gagal = nol baris.
--
-- NOL COMMIT (ADR-U-0029). -migrate dijalankan work owner.
INSERT ALL
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ADU', 'Approval', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('AcceptanceNote', 'Acceptance Note', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('AdjusterFee', 'Adjuster Fee', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('CFS', 'CFS', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ClaimAnalysis', 'ClaimAnalysis', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('CloseClaim', 'Close Claim', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('DLA', 'DLA', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('DLAFac-Out', 'DLA Fac-Out', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Invoice', 'Invoice', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('LOD', 'LOD', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('LossAdjuster', 'LossAdjuster', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('PLA', 'PLA', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('PLAFac-Out', 'PLA Fac-Out', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Premium', 'Premium', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('RejectClaim', 'RejectClaim', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('SPGR', 'Surat Persetujuan Ganti Rugi', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Salvage', 'Salvage', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('File', 'File', 'FAC')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ADU', 'Approval', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('AcceptanceNote', 'AcceptanceNote', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Acceptation', 'Acceptation', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ClaimAnalysis', 'ClaimAnalysis', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('CloseClaim', 'Close Claim', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('DLA', 'DLA', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Invoice', 'Invoice', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('KomiteAnalysis', 'KomiteAnalysis', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('LOD', 'LOD', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('PLA', 'PLA', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Premium', 'Premium', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('SPGR', 'Surat Persetujuan Ganti Rugi', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Salvage', 'Salvage', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('TLA', 'Treaty Leader Approval', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('File', 'File', 'PROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ADU', 'Approval', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('AcceptanceNote', 'AcceptanceNote', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('CFS', 'CFS', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('ClaimAnalysis', 'ClaimAnalysis', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('CloseClaim', 'CloseClaim', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('DLA', 'DLA', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Invoice', 'Invoice', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('LOD', 'LOD', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('LossAdjuster', 'LossAdjuster', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('PLA', 'PLA', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Premium', 'Premium', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('RejectClaim', 'RejectClaim', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('SPGR', 'Surat Persetujuan Ganti Rugi', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('Salvage', 'Salvage', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('TLA', 'Treaty Leader Approval', 'NONPROP')
  INTO {skema}.T_KATEGORI_DOC_KLAIM (ID, LABEL, TYPE_KLAIM) VALUES ('File', 'File', 'NONPROP')
SELECT 1 FROM DUAL
/
