DROP SEQUENCE {skema}.SEQ_TT_SHARE_SUMMARY
/
DROP TABLE {skema}.T_TREATY_SHARE_SUMMARY PURGE
/
ALTER TABLE {skema}.T_TREATY_REVISION DROP (
  RNMSHAREP,
  BROKERAGEPERCENTP,
  OPTIONLIMIT,
  INSTALLMENTNO,
  REVISIONSTATE,
  VIEWSTATE
)
/
