DROP SEQUENCE {skema}.SEQ_TT_LIMIT_REINST
/
DROP TABLE {skema}.T_TREATY_LIMIT_REINSTATEMENT PURGE
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_ACH_PARAM
/
DROP TABLE {skema}.T_TREATY_LIMIT_ACH_PARAM PURGE
/
DROP SEQUENCE {skema}.SEQ_TT_LIMIT_DEDUCTION
/
DROP TABLE {skema}.T_TREATY_LIMIT_DEDUCTION PURGE
/
