DROP SEQUENCE {skema}.SEQ_TT_FAC_SHARE_GROUP
/
DROP TABLE {skema}.T_TREATY_FAC_SHARE_GROUP PURGE
/
DROP SEQUENCE {skema}.SEQ_TT_SHARE_XOL_AMOUNT
/
DROP TABLE {skema}.T_TREATY_SHARE_XOL_AMOUNT PURGE
/
DROP SEQUENCE {skema}.SEQ_TT_SHARE_GROUP
/
DROP TABLE {skema}.T_TREATY_SHARE_GROUP PURGE
/
