-- LANGKAH-WO-RIRISKLIFE.md bab Pemulihan - BACA-SAJA. Penentu keadaan sesudah 935-941 gagal di tengah; bandingkan
-- dengan tabel keputusan K0-K5 di dokumen. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 250 PAGESIZE 100
PROMPT 1. Ringkasan (935/936/937)
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'RIRISK_LIFE_SUMMARY')                 AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RIRISK_LIFE_SUMMARY')             AS ADA_SUMBER,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'RIRISK_LIFE_SUMMARY')               AS ADA_TARGET,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE_SUMMARY')
      AND COLUMN_NAME IN ('USEDBY', 'MODIFIEDDATE', 'OPERATORID'))                                                    AS KOLOM_BARU,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE_SUMMARY')
      AND COLUMN_NAME = 'JSONDATA')                                                                                   AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'RIRISK_LIFE_SUMMARY')    AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '935_ririsk_life_summary_ganti_nama')                        AS T935,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '936_ririsk_life_summary_kolom')                             AS T936,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '937_ririsk_life_summary_satu_tabel')                        AS T937
FROM DUAL;
PROMPT 2. Rincian (938/939/940) dan menu (941)
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'RIRISK_LIFE')                         AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RIRISK_LIFE')                     AS ADA_SUMBER,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'RIRISK_LIFE')                       AS ADA_TARGET,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE', 'M_RIRISK_LIFE')
      AND COLUMN_NAME = 'AGE')                                                                                        AS ADA_AGE,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE', 'M_RIRISK_LIFE')
      AND COLUMN_NAME = 'JSONDATA')                                                                                   AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'RIRISK_LIFE')            AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM SYS.ALL_CONSTRAINTS WHERE OWNER = 'POOLDATA' AND CONSTRAINT_NAME = 'PK_RIRISK_LIFE')         AS ADA_PK,
  (SELECT COUNT(*) FROM SYS.ALL_IND_COLUMNS WHERE TABLE_OWNER = 'POOLDATA' AND TABLE_NAME = 'RIRISK_LIFE'
      AND COLUMN_NAME = 'IDUSEDBY' AND COLUMN_POSITION = 1)                                                           AS ADA_INDEKS_IDUSEDBY,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '938_ririsk_life_ganti_nama')                                AS T938,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '939_ririsk_life_kolom')                                     AS T939,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '940_ririsk_life_satu_tabel')                                AS T940,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '941_m_nav_menu_ririsklife')                                 AS T941,
  (SELECT COUNT(*) FROM POOLDATA.M_NAV_MENU WHERE KODE = 'ririsklife')                                               AS ADA_MENU
FROM DUAL;
PROMPT 3. Isi kolom baru (ORA-00904 / ORA-00942 = kolom / tabel belum ada pada nama itu, wajar)
SELECT COUNT(*) AS N, COUNT(USEDBY) AS N_USEDBY FROM POOLDATA.RIRISK_LIFE_SUMMARY;
SELECT COUNT(*) AS N, COUNT(IDUSEDBY) AS N_IDUSEDBY, COUNT(RISK) AS N_RISK FROM POOLDATA.RIRISK_LIFE;
