-- LANGKAH-WO-RIRISKLIFE.md (a) P2 - BACA-SAJA, dijalankan DBA. Pemakaian skema GL atas M_RIRISK_LIFE (GL punya SELECT
-- - fakta WO 08-10-2026). RENAME (938) dan pembuangan JSONDATA (940) MEMATAHKAN setiap objek GL yang menyebut
-- M_RIRISK_LIFE / M_RIRISK_LIFE_SUMMARY / JSONDATA tabel itu. Hasil yang diharapkan: SEMUA kueri NOL baris.
-- ⛔ Satu baris saja = BERHENTI, jangan -migrate, laporkan ke work owner.
SET LINESIZE 250 PAGESIZE 200 LONG 4000
COLUMN NAME FORMAT A32
COLUMN TYPE FORMAT A16
COLUMN TEXT FORMAT A120
PROMPT 1. Dependensi GL atas tabel / view R/I Risk
SELECT OWNER, NAME, TYPE, REFERENCED_OWNER, REFERENCED_NAME, REFERENCED_TYPE FROM DBA_DEPENDENCIES
 WHERE OWNER = 'GL' AND REFERENCED_OWNER = 'POOLDATA'
   AND REFERENCED_NAME IN ('M_RIRISK_LIFE', 'M_RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE', 'RIRISK_LIFE_SUMMARY');
PROMPT 2. Kode GL (prosedur, fungsi, paket, trigger) yang menyebut nama tabel
SELECT OWNER, NAME, TYPE, LINE, TEXT FROM DBA_SOURCE
 WHERE OWNER = 'GL' AND (UPPER(TEXT) LIKE '%M_RIRISK_LIFE%' OR UPPER(TEXT) LIKE '%RIRISK_LIFE%');
PROMPT 3. View GL yang menyebut nama tabel (teks view dibaca sebagai CLOB)
SELECT OWNER, VIEW_NAME FROM DBA_VIEWS
 WHERE OWNER = 'GL' AND UPPER(TO_LOB(TEXT)) LIKE '%RIRISK_LIFE%';
PROMPT 4. Sinonim (milik siapa pun) yang menunjuk tabel / view R/I Risk
SELECT OWNER, SYNONYM_NAME, TABLE_OWNER, TABLE_NAME FROM DBA_SYNONYMS
 WHERE TABLE_OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RIRISK_LIFE', 'M_RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE', 'RIRISK_LIFE_SUMMARY');
PROMPT 5. Grant ke GL (informasi: grant ikut tabel saat RENAME; SELECT GL atas JSONDATA tidak lagi bermakna sesudah 940)
SELECT GRANTEE, OWNER, TABLE_NAME, PRIVILEGE FROM DBA_TAB_PRIVS
 WHERE OWNER = 'POOLDATA' AND GRANTEE = 'GL' AND TABLE_NAME LIKE '%RIRISK%';
