-- LANGKAH-WO-RIRISKLIFE.md (c) - BACA-SAJA, SESUDAH 935-941. Angka harus sama dengan ririsk_acuan.txt; lalu dua CSV
-- sesudah untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL ririsk_verifikasi.txt
PROMPT 1. Kolom akhir: RIRISK_LIFE_SUMMARY (ID, USEDBY, MODIFIEDDATE, OPERATORID); RIRISK_LIFE (ID, IDUSEDBY, USEDBY, AGE, YEAR, MONTH, RISK, CONTRACT); nol JSONDATA
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE');
PROMPT 2. Objek: RIRISK_LIFE* = dua TABLE; M_RIRISK_LIFE dan M_RIRISK_LIFE_SUMMARY tidak ada; nol VIEW (M_RIRISK_LIFE_TEMP tetap ada)
SELECT OBJECT_NAME, OBJECT_TYPE FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('RIRISK_LIFE', 'RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE', 'M_RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE_TEMP')
 ORDER BY OBJECT_NAME;
PROMPT 3. Cacah (pembanding 117 / 16.398) dan ID tertinggi = acuan
SELECT COUNT(*) AS N_RINGKASAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.RIRISK_LIFE_SUMMARY;
SELECT COUNT(*) AS N_RINCIAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.RIRISK_LIFE;
PROMPT 4. Sidik = acuan (a) kueri 2 dan 3 (RISK NUMBER lewat TM9 = acuan konversi ber-format K2 lalu TM9)
SELECT COUNT(USEDBY) N_USEDBY, COUNT(MODIFIEDDATE) N_MODIFIEDDATE, COUNT(OPERATORID) N_OPERATORID,
       SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(MODIFIEDDATE)) H_MODIFIEDDATE, SUM(ORA_HASH(OPERATORID)) H_OPERATORID,
       SUM(ORA_HASH(ID || '|' || USEDBY || '|' || MODIFIEDDATE || '|' || OPERATORID)) H_BARIS
  FROM POOLDATA.RIRISK_LIFE_SUMMARY;
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(AGE) N_AGE, COUNT(YEAR) N_YEAR, COUNT(MONTH) N_MONTH,
       COUNT(RISK) N_RISK, COUNT(CONTRACT) N_CONTRACT,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || YEAR || '|' || MONTH || '|' || CONTRACT)) H_BARIS_TEKS,
       SUM(ORA_HASH(ID || '|' || TO_CHAR(RISK, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''))) H_RISK
  FROM POOLDATA.RIRISK_LIFE;
PROMPT 5. Sampel RISK berkoma di JSON lama: nilai NUMBER bertitik (bandingkan dengan M_RIRISK_LIFE_LENGKAP.csv)
SELECT ID, TO_CHAR(RISK, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS RISK FROM POOLDATA.RIRISK_LIFE
 WHERE RISK <> TRUNC(RISK) ORDER BY ID FETCH FIRST 10 ROWS ONLY;
PROMPT 6. Constraint dan indeks: PK_RIRISK_LIFE ada; IS JSON hilang; indeks berkolom pertama IDUSEDBY ada (INDEX4 atau IX_RIRISK_LIFE_IDUSEDBY); IX_RIRISK_LIFE_SUMMARY_NAMA ada
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE') ORDER BY TABLE_NAME, CONSTRAINT_NAME;
SELECT INDEX_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_POSITION FROM SYS.ALL_IND_COLUMNS
 WHERE TABLE_OWNER = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE') ORDER BY INDEX_NAME, COLUMN_POSITION;
PROMPT 7. T_MIGRASI (tujuh baris) dan baris menu
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI WHERE NAMA IN ('935_ririsk_life_summary_ganti_nama',
  '936_ririsk_life_summary_kolom', '937_ririsk_life_summary_satu_tabel', '938_ririsk_life_ganti_nama', '939_ririsk_life_kolom',
  '940_ririsk_life_satu_tabel', '941_m_nav_menu_ririsklife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI FROM POOLDATA.M_NAV_MENU WHERE KODE = 'ririsklife';
PROMPT 8. Status prosedur Pega (INVALID diharapkan, K3 - diterima WO; jangan dikompilasi ulang) dan grant (ikut RENAME)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PEGA_M_RIRISK_LIFE', 'PEGA_M_RIRISK_LIFE_SUMMARY');
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS
 WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME IN ('RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE');
SPOOL OFF
PROMPT 9. CSV sesudah (bentuk sama dengan CSV SEBELUM)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL RIRISK_LIFE_SUMMARY_SESUDAH.csv
SELECT ID, USEDBY, MODIFIEDDATE, OPERATORID FROM POOLDATA.RIRISK_LIFE_SUMMARY ORDER BY ID;
SPOOL OFF
SPOOL RIRISK_LIFE_SESUDAH.csv
SELECT ID, IDUSEDBY, USEDBY, YEAR, MONTH, TO_CHAR(RISK, 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,''') AS RISK, CONTRACT
  FROM POOLDATA.RIRISK_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: ririsk_verifikasi.txt, RIRISK_LIFE_SUMMARY_SESUDAH.csv, RIRISK_LIFE_SESUDAH.csv
