-- LANGKAH-WO-RIRISKLIFE.md (a) P1 acuan dan (c)0 - BACA-SAJA. Angka acuan SEBELUM 935-941, dibaca lewat VIEW lama
-- (sumber kebenaran = JSONDATA). Dijalankan DUA kali: sesaat SEBELUM cadangan P3 dan TEPAT SEBELUM -migrate; kedua
-- keluaran harus SAMA (beda = ada penulis yang masih hidup - ulangi P1-P3). Keluaran ditambahkan ke ririsk_acuan.txt.
-- Nilai OPERATORID TIDAK dicetak (nama orang) - hanya sidiknya.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL ririsk_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah dan ID tertinggi (pembanding WO 08-10-2026: ringkasan 117, rincian 16.398) + sequence
SELECT COUNT(*) AS N_RINGKASAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RIRISK_LIFE_SUMMARY;
SELECT COUNT(*) AS N_RINCIAN, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RIRISK_LIFE;
SELECT SEQUENCE_NAME, LAST_NUMBER FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME IN ('M_RIRISK_LIFE_SUMMARY_SEQ', 'M_RIRISK_LIFE_SEQ');
PROMPT 2. Sidik ringkasan lewat view (cacah tidak-NULL + jumlah ORA_HASH per kolom dan per baris)
SELECT COUNT(USEDBY) N_USEDBY, COUNT(MODIFIEDDATE) N_MODIFIEDDATE, COUNT(OPERATORID) N_OPERATORID,
       SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(MODIFIEDDATE)) H_MODIFIEDDATE, SUM(ORA_HASH(OPERATORID)) H_OPERATORID,
       SUM(ORA_HASH(ID || '|' || USEDBY || '|' || MODIFIEDDATE || '|' || OPERATORID)) H_BARIS
  FROM POOLDATA.RIRISK_LIFE_SUMMARY;
PROMPT 3. Sidik rincian lewat view (teks apa adanya; RISK lewat konversi BER-FORMAT ber-NLS eksplisit K2 - independen dari
PROMPT    ekspresi TRANSLATE 940 - lalu TM9, = bentuk TM9 kolom NUMBER sesudah 940)
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(AGE) N_AGE, COUNT(YEAR) N_YEAR, COUNT(MONTH) N_MONTH,
       COUNT(RISK) N_RISK, COUNT(CONTRACT) N_CONTRACT,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || YEAR || '|' || MONTH || '|' || CONTRACT)) H_BARIS_TEKS,
       SUM(ORA_HASH(ID || '|' || TO_CHAR(TO_NUMBER(REPLACE(TRIM(RISK), ',', '.'), '999999999999999999999999999999D9999999999999999999', 'NLS_NUMERIC_CHARACTERS=''.,'''), 'TM9', 'NLS_NUMERIC_CHARACTERS=''.,'''))) H_RISK
  FROM POOLDATA.RIRISK_LIFE;
PROMPT 4. Profil RISK (pembanding: 11.063 berkoma, 89 bertitik, sisanya bulat, nol NULL) dan nilai yang BUKAN angka (harus 0)
SELECT SUM(CASE WHEN INSTR(RISK, ',') > 0 THEN 1 ELSE 0 END) AS BERKOMA,
       SUM(CASE WHEN INSTR(RISK, '.') > 0 THEN 1 ELSE 0 END) AS BERTITIK,
       SUM(CASE WHEN RISK IS NULL THEN 1 ELSE 0 END) AS KOSONG,
       SUM(CASE WHEN NOT REGEXP_LIKE(TRIM(RISK), '^[0-9]+([.,][0-9]+)?$') THEN 1 ELSE 0 END) AS BUKAN_ANGKA
  FROM POOLDATA.RIRISK_LIFE;
PROMPT 5. ID rincian NULL / ganda (PK_RIRISK_LIFE 940 menolaknya - harus 0 / nol baris)
SELECT COUNT(*) AS ID_NULL FROM POOLDATA.M_RIRISK_LIFE WHERE ID IS NULL;
SELECT ID, COUNT(*) FROM POOLDATA.M_RIRISK_LIFE GROUP BY ID HAVING COUNT(*) > 1;
PROMPT 6. Yatim (rincian tanpa ringkasan; pembanding 2) dan ringkasan tanpa rincian (pembanding 2) - TIDAK dihapus
SELECT COUNT(*) AS YATIM FROM POOLDATA.RIRISK_LIFE r
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RIRISK_LIFE_SUMMARY s WHERE s.ID = r.IDUSEDBY);
SELECT COUNT(*) AS TANPA_RINCIAN FROM POOLDATA.M_RIRISK_LIFE_SUMMARY s
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.RIRISK_LIFE r WHERE r.IDUSEDBY = s.ID);
PROMPT 7. Nilai yang melewati lebar kolom tujuan (harus NOL baris; bila ada: BERHENTI)
SELECT 'RINGKASAN' AS T, ID FROM POOLDATA.RIRISK_LIFE_SUMMARY
 WHERE LENGTHB(USEDBY) > 200 OR LENGTHB(MODIFIEDDATE) > 50 OR LENGTHB(OPERATORID) > 200
UNION ALL
SELECT 'RINCIAN', ID FROM POOLDATA.RIRISK_LIFE
 WHERE LENGTHB(IDUSEDBY) > 100 OR LENGTHB(USEDBY) > 1000 OR LENGTHB(AGE) > 10 OR LENGTHB(YEAR) > 10
    OR LENGTHB(MONTH) > 10 OR LENGTHB(CONTRACT) > 10;
PROMPT 8. Definisi asli: kolom (NULLABLE JSONDATA - dipakai jalur mundur), constraint, dan kolom setiap indeks M_RIRISK_LIFE (INDEX4)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE') ORDER BY TABLE_NAME, CONSTRAINT_NAME;
SELECT INDEX_NAME, COLUMN_NAME, COLUMN_POSITION FROM SYS.ALL_IND_COLUMNS
 WHERE TABLE_OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RIRISK_LIFE' ORDER BY INDEX_NAME, COLUMN_POSITION;
PROMPT 9. Status prosedur Pega dan grant tabel
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PEGA_M_RIRISK_LIFE', 'PEGA_M_RIRISK_LIFE_SUMMARY');
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS
 WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME IN ('M_RIRISK_LIFE_SUMMARY', 'M_RIRISK_LIFE', 'RIRISK_LIFE_SUMMARY', 'RIRISK_LIFE');
SPOOL OFF
