-- 100 - relasi lima tabel warisan Master Contract Retro Life: PK, FK ke induk
-- langsung dengan kaskade hapus, dan FK penjaga salinan.
--
-- Keputusan work owner 01-10-2026: "untuk modul Treaty Contract Retro Life aku
-- izinkan kamu ALTER TABLE yang digunakan, perbaiki logic relasi datanya".
-- Mencabut K1 (nol DDL) untuk CONSTRAINT dan INDEKS saja. TETAP: nol tabel baru,
-- nol kolom dibuang atau ditambah - prosedur Pega INSERT*_LIFE dan PEGA_M_*_LIFE
-- masih membaca dan menulis setiap kolom.
--
-- Data DEV diperiksa 01-10-2026 (baca-saja): nol ID kosong atau ganda, nol
-- kolom penghubung kosong, nol anak tanpa induk (sesudah business yatim dihapus
-- work owner), nol salinan yang berbeda dari induk, nol kontrak ganda per
-- tahun + jenis. Lima business warisan ber-TREATYYEAR kosong
-- (SaveTreatyBusinessAll_Life_SQL Pega tidak menulisnya) diisi di langkah 1.
--
--   PK        ID di kelima tabel.
--   NOT NULL  kolom penghubung ke induk langsung.
--   FK        ke induk langsung, ON DELETE CASCADE: hapus induk lewat jalur mana
--             pun (aplikasi, SQL, Pega) ikut menghapus anaknya.
--   FK        penjaga salinan, DEFERRABLE INITIALLY DEFERRED: kolom salinan
--             (TREATYYEARID, REINSTYPEID, TREATYCONTRACTID, TREATYYEAR) di setiap
--             anak WAJIB sama dengan induknya saat COMMIT; deferred supaya induk
--             lalu anak dapat diubah dalam satu transaksi (K4).
--   INDEX     setiap kolom penghubung.
--
-- Satu bentuk blok berpelindung katalog (penjaga inti): tiap blok menanyakan
-- kolom yang disebut perintahnya. Skema uji membangun skema dari nol TANPA
-- tabel warisan ini (skemauji membuat tiruannya sesudah migrasi), jadi semua
-- blok dilewati di sana dan dijalankan di DEV. Bila langkah tengah gagal di DEV,
-- jalankan 100_down lebih dulu, lalu ulangi.
--
-- Nol COMMIT di teks (ADR-U-0029).

-- 1. Data: TREATYYEAR business warisan yang kosong diisi dari tahun induknya.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'UPDATE {skema}.TREATYBUSINESS_LIFE b SET b.TREATYYEAR = (SELECT y.TREATYYEAR FROM {skema}.TREATYYEAR_LIFE y WHERE y.ID = b.TREATYYEARID) WHERE b.TREATYYEAR IS NULL AND EXISTS (SELECT 1 FROM {skema}.TREATYYEAR_LIFE y WHERE y.ID = b.TREATYYEARID)';
  END IF;
END;
/
-- 2. PK.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYYEAR_LIFE' AND COLUMN_NAME = 'ID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYYEAR_LIFE ADD CONSTRAINT PK_TREATYYEAR_LIFE PRIMARY KEY (ID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'ID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE ADD CONSTRAINT PK_TREATYCONTRACT_LIFE PRIMARY KEY (ID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'ID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE ADD CONSTRAINT PK_TREATYREINSURER_LIFE PRIMARY KEY (ID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'ID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE ADD CONSTRAINT PK_TREATYSECREINS_LIFE PRIMARY KEY (ID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'ID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE ADD CONSTRAINT PK_TREATYBUSINESS_LIFE PRIMARY KEY (ID)';
  END IF;
END;
/
-- 3. Kolom penghubung ke induk langsung wajib terisi.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'IDTREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE MODIFY (IDTREATYYEAR NOT NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE MODIFY (TREATYCONTRACTID NOT NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYREINSURERID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE MODIFY (TREATYREINSURERID NOT NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE MODIFY (TREATYCONTRACTID NOT NULL)';
  END IF;
END;
/
-- 4. Kunci unik sasaran FK penjaga salinan.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYYEAR_LIFE' AND COLUMN_NAME = 'TREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYYEAR_LIFE ADD CONSTRAINT UQ_TYL_SALINAN UNIQUE (ID, TREATYYEAR)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'REINSTYPEID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE ADD CONSTRAINT UQ_TCL_SALINAN UNIQUE (ID, IDTREATYYEAR, REINSTYPEID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYYEARID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE ADD CONSTRAINT UQ_TRL_SALINAN UNIQUE (ID, TREATYCONTRACTID, TREATYYEARID)';
  END IF;
END;
/
-- 5. FK ke induk langsung, kaskade hapus.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'IDTREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE ADD CONSTRAINT FK_TCL_TAHUN FOREIGN KEY (IDTREATYYEAR) REFERENCES {skema}.TREATYYEAR_LIFE (ID) ON DELETE CASCADE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE ADD CONSTRAINT FK_TRL_KONTRAK FOREIGN KEY (TREATYCONTRACTID) REFERENCES {skema}.TREATYCONTRACT_LIFE (ID) ON DELETE CASCADE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYREINSURERID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE ADD CONSTRAINT FK_TSRL_REINSURER FOREIGN KEY (TREATYREINSURERID) REFERENCES {skema}.TREATYREINSURER_LIFE (ID) ON DELETE CASCADE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE ADD CONSTRAINT FK_TBL_KONTRAK FOREIGN KEY (TREATYCONTRACTID) REFERENCES {skema}.TREATYCONTRACT_LIFE (ID) ON DELETE CASCADE';
  END IF;
END;
/
-- 6. FK penjaga salinan, diperiksa saat COMMIT.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'REINSTYPEID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE ADD CONSTRAINT FK_TRL_SALINAN FOREIGN KEY (TREATYCONTRACTID, TREATYYEARID, REINSTYPEID) REFERENCES {skema}.TREATYCONTRACT_LIFE (ID, IDTREATYYEAR, REINSTYPEID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYYEARID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE ADD CONSTRAINT FK_TSRL_SALINAN FOREIGN KEY (TREATYREINSURERID, TREATYCONTRACTID, TREATYYEARID) REFERENCES {skema}.TREATYREINSURER_LIFE (ID, TREATYCONTRACTID, TREATYYEARID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'REINSTYPEID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE ADD CONSTRAINT FK_TBL_SALINAN FOREIGN KEY (TREATYCONTRACTID, TREATYYEARID, REINSTYPEID) REFERENCES {skema}.TREATYCONTRACT_LIFE (ID, IDTREATYYEAR, REINSTYPEID) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE ADD CONSTRAINT FK_TBL_TAHUN_SALINAN FOREIGN KEY (TREATYYEARID, TREATYYEAR) REFERENCES {skema}.TREATYYEAR_LIFE (ID, TREATYYEAR) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED';
  END IF;
END;
/
-- 7. Indeks kolom penghubung.
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'IDTREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_TCL_TAHUN ON {skema}.TREATYCONTRACT_LIFE (IDTREATYYEAR)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_TRL_KONTRAK ON {skema}.TREATYREINSURER_LIFE (TREATYCONTRACTID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYREINSURERID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_TSRL_REINSURER ON {skema}.TREATYSECURITYREINSURER_LIFE (TREATYREINSURERID)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX {skema}.IX_TBL_KONTRAK ON {skema}.TREATYBUSINESS_LIFE (TREATYCONTRACTID)';
  END IF;
END;
/
