-- LANGKAH-WO-RIRATELIFE-DETAIL-FLAT.md (a)2 dan (b)0 - BACA-SAJA. Angka acuan M_RATE_LIFE SEBELUM 929/930, dibaca
-- lewat view RATE_LIFE (8 kolom). Dijalankan DUA kali: sesaat SEBELUM cadangan (a)3 dan TEPAT SEBELUM (b); kedua
-- keluaran harus SAMA (bila beda: ada yang menulis - ulangi (a)1-(a)3). Keluaran disimpan ke berkas teks juga.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL detail_flat_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah, ID tertinggi, sequence
SELECT COUNT(*) AS N, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RATE_LIFE;
SELECT LAST_NUMBER FROM SYS.ALL_SEQUENCES WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME = 'SEQ_M_RATE_LIFE';
PROMPT 2. Sidik isi per kolom (cacah tidak-NULL + jumlah ORA_HASH) dan per baris
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(TYPE) N_TYPE, COUNT(GENDER) N_GENDER,
       COUNT(CONTRACT) N_CONTRACT, COUNT(AGE) N_AGE, COUNT(RATE) N_RATE FROM POOLDATA.RATE_LIFE;
SELECT SUM(ORA_HASH(IDUSEDBY)) H_IDUSEDBY, SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(TYPE)) H_TYPE,
       SUM(ORA_HASH(GENDER)) H_GENDER FROM POOLDATA.RATE_LIFE;
SELECT SUM(ORA_HASH(CONTRACT)) H_CONTRACT, SUM(ORA_HASH(AGE)) H_AGE, SUM(ORA_HASH(RATE)) H_RATE,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || TYPE || '|' || GENDER || '|' || CONTRACT
                   || '|' || AGE || '|' || RATE)) H_BARIS
  FROM POOLDATA.RATE_LIFE;
PROMPT 3. Yatim (IDUSEDBY tanpa ringkasan) dan status prosedur Pega
SELECT COUNT(*) AS YATIM FROM POOLDATA.RATE_LIFE r
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RATE_LIFE_SUMMARY s WHERE s.ID = r.IDUSEDBY);
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'PEGA_M_RATE_LIFE';
PROMPT 4. Nilai yang melewati lebar 929 (harus NOL baris; bila ada: BERHENTI)
SELECT ID FROM POOLDATA.RATE_LIFE
 WHERE LENGTHB(IDUSEDBY) > 10 OR LENGTHB(USEDBY) > 500 OR LENGTHB(TYPE) > 100 OR LENGTHB(GENDER) > 10
    OR LENGTHB(CONTRACT) > 10 OR LENGTHB(AGE) > 10 OR LENGTHB(RATE) > 50;
PROMPT 5. Definisi asli JSONDATA (NULLABLE N = NOT NULL; dipakai jalur mundur)
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE' ORDER BY COLUMN_ID;
SPOOL OFF
