-- LANGKAH-WO-RIRATELIFE-DETAIL-FLAT.md (a)3 - BACA-SAJA. Dua cadangan CSV SEBELUM 929/930, di folder kerja SQL*Plus:
--   M_RATE_LIFE_JSONDATA.csv - ID + JSONDATA (satu-satunya salinan FLAG dan bentuk JSON asli; sumber pemulihan)
--   M_RATE_LIFE_SEBELUM.csv  - 8 kolom view RATE_LIFE (acuan perbandingan (c)3b)
-- Dijalankan sebagai BERKAS (@...) supaya TERMOUT OFF berlaku (98 ribu baris tidak dicetak ke layar).
-- SQL*Plus 12.2+ atau SQLcl (MARKUP CSV).
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LONG 2000000 LONGCHUNKSIZE 32767 LINESIZE 32767 TRIMSPOOL ON
SPOOL M_RATE_LIFE_JSONDATA.csv
SELECT ID, JSONDATA FROM POOLDATA.M_RATE_LIFE ORDER BY ID;
SPOOL OFF
SPOOL M_RATE_LIFE_SEBELUM.csv
SELECT ID, IDUSEDBY, USEDBY, TYPE, GENDER, CONTRACT, AGE, RATE FROM POOLDATA.RATE_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT cadangan selesai: M_RATE_LIFE_JSONDATA.csv, M_RATE_LIFE_SEBELUM.csv
