-- LANGKAH-WO-RIRATELIFE-DETAIL-FLAT.md bab Pemulihan - BACA-SAJA. Penentu keadaan sesudah 929/930 gagal di tengah;
-- bandingkan hasilnya dengan tabel keputusan di dokumen. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 250 PAGESIZE 100
PROMPT 1. Keadaan objek dan catatan migrasi
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE'
      AND COLUMN_NAME IN ('IDUSEDBY', 'USEDBY', 'TYPE', 'GENDER', 'CONTRACT', 'AGE', 'RATE'))            AS KOLOM_BARU,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE'
      AND COLUMN_NAME = 'JSONDATA')                                                                      AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE') AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'RATE_LIFE')           AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_INDEXES WHERE OWNER = 'POOLDATA' AND INDEX_NAME = 'IX_M_RATE_LIFE_IDUSEDBY') AS ADA_INDEKS,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '929_m_rate_life_kolom')                        AS T929,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '930_m_rate_life_satu_tabel')                   AS T930
FROM DUAL;
PROMPT 2. Isi kolom baru (ORA-00904 di sini = KOLOM_BARU 0, wajar)
SELECT COUNT(*) AS N, COUNT(IDUSEDBY) AS N_IDUSEDBY, COUNT(RATE) AS N_RATE FROM POOLDATA.M_RATE_LIFE;
