-- LANGKAH-WO-RIRATELIFE-DETAIL-FLAT.md (a)1 - versi DBA, BACA-SAJA, bila pemilik POOLDATA tidak punya hak V$.
-- Dijalankan DBA (hak SELECT_CATALOG_ROLE / SELECT ANY DICTIONARY). Hasil yang diharapkan: NOL baris.
SET LINESIZE 200 PAGESIZE 100
COLUMN OWNER FORMAT A12
COLUMN NAME FORMAT A22
SELECT SESSION_ID, OWNER, NAME, MODE_HELD, MODE_REQUESTED
  FROM DBA_DML_LOCKS
 WHERE OWNER = 'POOLDATA' AND NAME IN ('M_RATE_LIFE', 'M_RATE_LIFE_SUMMARY');
