-- LANGKAH-WO-RIRATELIFE-DETAIL-FLAT.md (c) - BACA-SAJA, SESUDAH 929/930. Angka harus sama dengan detail_flat_acuan.txt
-- (a)2; lalu CSV M_RATE_LIFE_SESUDAH.csv untuk MINUS dua arah (c)3b. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL detail_flat_verifikasi.txt
PROMPT 1. Tepat 8 kolom: ID, IDUSEDBY, USEDBY, TYPE, GENDER, CONTRACT, AGE, RATE (nol JSONDATA)
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE' ORDER BY COLUMN_ID;
SELECT COUNT(*) AS SETENGAH_TERBUANG FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_RATE_LIFE';
PROMPT 2. Cacah, ID tertinggi, yatim (= acuan)
SELECT COUNT(*) AS N, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.M_RATE_LIFE;
SELECT COUNT(*) AS YATIM FROM POOLDATA.M_RATE_LIFE r
 WHERE NOT EXISTS (SELECT 1 FROM POOLDATA.M_RATE_LIFE_SUMMARY s WHERE s.ID = r.IDUSEDBY);
PROMPT 3a. Sidik isi (= acuan (a)2)
SELECT COUNT(IDUSEDBY) N_IDUSEDBY, COUNT(USEDBY) N_USEDBY, COUNT(TYPE) N_TYPE, COUNT(GENDER) N_GENDER,
       COUNT(CONTRACT) N_CONTRACT, COUNT(AGE) N_AGE, COUNT(RATE) N_RATE FROM POOLDATA.M_RATE_LIFE;
SELECT SUM(ORA_HASH(IDUSEDBY)) H_IDUSEDBY, SUM(ORA_HASH(USEDBY)) H_USEDBY, SUM(ORA_HASH(TYPE)) H_TYPE,
       SUM(ORA_HASH(GENDER)) H_GENDER FROM POOLDATA.M_RATE_LIFE;
SELECT SUM(ORA_HASH(CONTRACT)) H_CONTRACT, SUM(ORA_HASH(AGE)) H_AGE, SUM(ORA_HASH(RATE)) H_RATE,
       SUM(ORA_HASH(ID || '|' || IDUSEDBY || '|' || USEDBY || '|' || TYPE || '|' || GENDER || '|' || CONTRACT
                   || '|' || AGE || '|' || RATE)) H_BARIS
  FROM POOLDATA.M_RATE_LIFE;
PROMPT 4. View RATE_LIFE dan constraint IS JSON hilang (nol baris); indeks ada (satu baris)
SELECT OBJECT_NAME, OBJECT_TYPE FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'RATE_LIFE';
SELECT CONSTRAINT_NAME FROM SYS.ALL_CONSTRAINTS WHERE OWNER = 'POOLDATA' AND CONSTRAINT_NAME = 'ENSURE_M_RATE_LIFE_JSON';
SELECT INDEX_NAME, COLUMN_NAME FROM SYS.ALL_IND_COLUMNS
 WHERE INDEX_OWNER = 'POOLDATA' AND INDEX_NAME = 'IX_M_RATE_LIFE_IDUSEDBY';
PROMPT 5. T_MIGRASI (dua baris)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI
 WHERE NAMA IN ('929_m_rate_life_kolom', '930_m_rate_life_satu_tabel') ORDER BY NAMA;
PROMPT 6. Status PEGA_M_RATE_LIFE (INVALID diharapkan, diterima WO; jangan dikompilasi ulang)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS WHERE OWNER = 'POOLDATA' AND OBJECT_NAME = 'PEGA_M_RATE_LIFE';
SPOOL OFF
PROMPT 3b. CSV sesudah (bentuk sama dengan M_RATE_LIFE_SEBELUM.csv)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL M_RATE_LIFE_SESUDAH.csv
SELECT ID, IDUSEDBY, USEDBY, TYPE, GENDER, CONTRACT, AGE, RATE FROM POOLDATA.M_RATE_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: detail_flat_verifikasi.txt, M_RATE_LIFE_SESUDAH.csv
