// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatyinadjustment/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatyinadjustment "nusantarare/modul/treatyinadjustment/backend"

func init() { daftarkan(treatyinadjustment.Pendaftaran()) }
