// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/komiteclaimlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import komiteclaimlife "nusantarare/modul/komiteclaimlife/backend"

func init() { daftarkan(komiteclaimlife.Pendaftaran()) }
