// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/treatycontractout/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import treatycontractout "nusantarare/modul/treatycontractout/backend"

func init() { daftarkan(treatycontractout.Pendaftaran()) }
