// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/masterproductnamelife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import masterproductnamelife "nusantarare/modul/masterproductnamelife/backend"

func init() { daftarkan(masterproductnamelife.Pendaftaran()) }
