// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/premiumlistlife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import premiumlistlife "nusantarare/modul/premiumlistlife/backend"

func init() { daftarkan(premiumlistlife.Pendaftaran()) }
