// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/mastercontractretrolife/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import mastercontractretrolife "nusantarare/modul/mastercontractretrolife/backend"

func init() { daftarkan(mastercontractretrolife.Pendaftaran()) }
