// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/nbfacin/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import nbfacin "nusantarare/modul/nbfacin/backend"

func init() { daftarkan(nbfacin.Pendaftaran()) }
