// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/marketingofficer/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import marketingofficer "nusantarare/modul/marketingofficer/backend"

func init() { daftarkan(marketingofficer.Pendaftaran()) }
