// Label modul Claim Fac In. Label MEDAN, TOMBOL, JUDUL GRID, dan KOLOM datang dari server (VERBATIM section XML, pohon
// tata). Berkas ini hanya memuat judul pop-up (pyWindowName tombol pembuka / pyLabel harness dan flow action), judul
// kolom grid pop-up (VERBATIM section harness), dan teks perangkat halaman awal pola Claim Non Prop yang tidak punya
// label di XML (ditandai). Pola `modul/claimnonprop/frontend/labels.ts` (disalin, bukan impor).

/** Nama menu - `M_NAV_MENU.LABEL` baris modul ini (migrasi inti 900, DIMIGRASI lewat slot 978). */
export const MENU_CFI = { kelompok: 'Claim Fac In' } as const

export const CFI = {
  judul: 'Claim Fac In',
  /** Tab dan switch halaman awal - pola Claim Non Prop (`[tidak ada di korpus]`). */
  tabProses: 'Process',
  tabResolve: 'Resolve',
  inbox: 'Inbox',
  wbTeknik: 'Technical',
  teknikTanpaHak: 'Requires workbasket ReasKlaimTeknik',
  /** Start -> Assignment1 Input Register (`Register_Flow`); harness New tidak diekspor. */
  tambahKlaim: 'Add Claim',
  cari: 'Search case ID, claim no, policy no, insured name',
  memuat: 'Loading…',
  kosong: 'No case.',
  kembali: 'Back to list',
  kolomID: 'Case ID',
  kolomTahap: 'Assignment',
  kolomNoClaim: 'Claim No',
  kolomPolis: 'Policy No',
  kolomTertanggung: 'Insured Name',
  kolomDOL: 'Date of Loss',
  kolomPembuat: 'Create Operator',
  kolomTanggal: 'Create Date/Time',
  hanyaLihat: 'Read only - you do not hold this assignment.',
  pilih: 'Choose',
  tutup: 'Close',
  cariPopup: 'Search',
  menampilkan: 'Showing',
  dari: 'of',
  // judul pop-up = pyWindowName tombol pembuka, atau pyLabel harness / flow action
  popPolis: 'Choose Polis',
  popProtectDOL: 'ProtectDOL',
  popPLA: 'Pla_Dtl_Harness',
  popDLA: 'Print DLA',
  popCedant: 'ViewCedantpanels',
  popKomite: 'Komite Klaim',
  popTutup: 'PreventRejectClaim',
  popTolak: 'Reject Claim',
  popSebab: 'Cause Of Loss',
  popKatastrofe: 'CatastropheList',
  popOutstanding: 'Outstanding Claim',
  popRetro: 'View Retro List',
  // CatastrofeList_Sec
  addNew: 'Add',
  note: 'Note',
  userInput: 'User Input',
  save: 'Save',
  cancel: 'Cancel',
  // CauseofLoss_Section
  judulSebab: 'List Cause of Loss',
  kolomSebab: 'Cause of Loss',
  // ViewPolis (grid hasil SearchPolis_act)
  polisKolom: [
    'Policy Number',
    'Name of Insured',
    'Source Of Business',
    'Ceding Co Name',
    'QQ Name',
    'Begin Date',
    'End Date',
    'Endorsment Status',
    'Business',
  ],
  // Outstanding_SC (kolom keempat = `labelNama` per lini dari server)
  osNoClaim: 'No Claim',
  osPolis: 'Policy No',
  osAksep: 'Accepted No',
  osCoverage: 'Coverage Name',
  osCurrency: 'Currency',
  osTSI: 'TSI RNM',
  osNilai: 'Estimation / Accepted Value',
  osKurs: 'Kurs Value',
  osKonversi: 'Convert Value',
  osTotal: 'Total Outstanding',
  // RetroList_SC
  retroKolom: ['Reinsurer Name', 'Share (%)', 'R/I Comm'],
  /** Tab "Lampiran" - pola Claim Prop / Claim Non Prop (VERBATIM screenshot layar Pega, work owner 09-10-2026). */
  lampiran: 'Lampiran',
  lampiranTambah: 'Add attachment',
  lampiranMuatUlang: 'Refresh',
  lampiranMenampilkan: 'Showing',
  lampiranSemua: 'Show All',
  lampiranKategori: 'Category',
  lampiranCacah: 'Count Attach',
  lampiranUnggah: 'Upload File',
  lampiranLihat: 'View File',
  lampiranPilih: 'Select file(s)',
  lampiranSeret: 'Drag and drop files here or',
  lampiranFile: 'File',
  lampiranBuang: 'Remove',
  lampiranKirim: 'Attach',
  lampiranMengirim: 'Attaching…',
  lampiranKosong: 'No attachment.',
  lampiranNama: 'File Name',
  lampiranTanggal: 'Create Date',
  lampiranOleh: 'Attached By',
  lampiranView: 'View',
  lampiranViewOffice: 'View Office Online',
  lampiranHapus: 'Delete',
  lampiranAksi: 'Action',
  lampiranUnduhPilih: 'Download Selected',
  lampiranHapusPilih: 'Delete Selected',
  lampiranPindah: 'Change Category',
  lampiranPindahKe: 'Move to',
} as const
