// Teks layar master generik (inti). Judul master datang dari `GET P/meta`; label kolom = kamus kunci JSON di bawah,
// cadangannya nama kolom tabel. Rujukan (kolom mana merujuk master mana) datang dari meta, bukan dari sini.

export const TEKS_MASTER = {
  sub: 'Data rujukan yang dipakai modul lain. Data tidak dihapus - nonaktifkan bila tidak dipakai lagi.',
  cari: 'Cari ID / nama',
  semuaStatus: 'Semua status',
  aktif: 'Aktif',
  nonaktif: 'Nonaktif',
  kolomStatus: 'Status',
  kolomAksi: 'Aksi',
  tambah: 'Tambah',
  ubah: 'Ubah',
  aktifkan: 'Aktifkan',
  nonaktifkan: 'Nonaktifkan',
  simpan: 'Simpan',
  menyimpan: 'Menyimpan…',
  memuat: 'Memuat data…',
  kosong: 'Belum ada data.',
  tidakCocok: 'Tidak ada data yang cocok.',
  sebelumnya: 'Sebelumnya',
  berikutnya: 'Berikutnya',
  pertama: 'Pertama',
  terakhir: 'Terakhir',
  navigasiHalaman: 'Navigasi halaman',
  /** "Menampilkan 21–40 dari 135 data" (20 data per halaman). */
  menampilkan: (halaman: number, ukuran: number, total: number) =>
    `Menampilkan ${(halaman - 1) * ukuran + 1}–${Math.min(halaman * ukuran, total)} dari ${total} data`,
  judulTambah: (judul: string) => `Tambah ${judul}`,
  judulUbah: (judul: string) => `Ubah ${judul}`,
  idOtomatis: 'Dibuat otomatis saat disimpan',
  turunan: 'Diisi otomatis',
  wajib: 'Wajib diisi.',
  terlaluPanjang: (lebar: number) => `Paling panjang ${lebar} karakter.`,
  tersimpan: (id: string) => `Data ${id} tersimpan.`,
  statusBerubah: (id: string, aktif: boolean) => `Data ${id} ${aktif ? 'diaktifkan' : 'dinonaktifkan'}.`,
  konfirmasiStatus: (id: string, aktif: boolean) =>
    aktif ? `Aktifkan kembali data ${id}?` : `Nonaktifkan data ${id}? Data nonaktif tidak muncul di pilihan modul lain.`,
  judulKonfirmasi: (aktif: boolean) => (aktif ? 'Aktifkan data' : 'Nonaktifkan data'),
} as const

/** Label kolom per kunci JSON (sama di semua master). */
export const LABEL_KOLOM_MASTER: Readonly<Record<string, string>> = {
  id: 'ID',
  oldId: 'Old ID',
  note: 'Note',
  nationInitial: 'Nation Initial',
  nationId: 'Nation',
  nationName: 'Nation Name',
  provinceId: 'Province',
  province: 'Province Name',
  provinceName: 'Province Name',
  branchId: 'Branch',
  jabodetabekStatus: 'Jabodetabek Status',
  cityId: 'City',
  districtName: 'District Name',
  code: 'Code',
  description: 'Description',
  groupOf: 'Group Of',
  groupOfName: 'Group Of Name',
  accumulationType: 'Accumulation Type',
  keyword: 'Keyword',
  type: 'Type',
  accumulation: 'Accumulated Type',
  accumulationName: 'Accumulation Name',
  scopeArea: 'Scope Area',
  cZone: 'CZone',
  cZoneId: 'CZone ID',
  zipCode: 'Zip Code',
  syariahStatus: 'Syariah Status',
  objectItemType: 'Object Item Type',
  pctAdjustable1: 'Pct Adjustable 1',
  pctAdjustable2: 'Pct Adjustable 2',
  objectItemTypeIna: 'Object Item Type (INA)',
  group: 'Group',
  // Jejak ubah (MD-7) - turunan, baca-saja.
  createOp: 'Dibuat oleh',
  tglCreate: 'Tanggal dibuat',
  updateOp: 'Diubah oleh',
  tglUpdate: 'Tanggal diubah',
  negara: 'Negara (awalan ID)',
}

/** Label satu kolom: kamus di atas, cadangannya nama kolom tabel. */
export const labelKolomMaster = (kunci: string, kolom: string) => LABEL_KOLOM_MASTER[kunci] ?? kolom
