-- 100 mundur - buang constraint dan indeks relasi lima tabel _LIFE.
--
-- Urutan: FK penjaga salinan, FK induk, kunci unik, PK, indeks; kolom penghubung
-- kembali boleh kosong. Isian TREATYYEAR langkah 1 TIDAK dibalik: nilai kosong
-- warisan tidak membawa informasi.
--
-- Satu bentuk blok berpelindung katalog; setiap objek dibuang hanya bila ada.
-- Nol COMMIT di teks (ADR-U-0029).

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND CONSTRAINT_NAME = 'FK_TBL_TAHUN_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE DROP CONSTRAINT FK_TBL_TAHUN_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND CONSTRAINT_NAME = 'FK_TBL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE DROP CONSTRAINT FK_TBL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND CONSTRAINT_NAME = 'FK_TSRL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE DROP CONSTRAINT FK_TSRL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND CONSTRAINT_NAME = 'FK_TRL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE DROP CONSTRAINT FK_TRL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND CONSTRAINT_NAME = 'FK_TBL_KONTRAK';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE DROP CONSTRAINT FK_TBL_KONTRAK';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND CONSTRAINT_NAME = 'FK_TSRL_REINSURER';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE DROP CONSTRAINT FK_TSRL_REINSURER';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND CONSTRAINT_NAME = 'FK_TRL_KONTRAK';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE DROP CONSTRAINT FK_TRL_KONTRAK';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND CONSTRAINT_NAME = 'FK_TCL_TAHUN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE DROP CONSTRAINT FK_TCL_TAHUN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND CONSTRAINT_NAME = 'UQ_TRL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE DROP CONSTRAINT UQ_TRL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND CONSTRAINT_NAME = 'UQ_TCL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE DROP CONSTRAINT UQ_TCL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYYEAR_LIFE' AND CONSTRAINT_NAME = 'UQ_TYL_SALINAN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYYEAR_LIFE DROP CONSTRAINT UQ_TYL_SALINAN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND CONSTRAINT_NAME = 'PK_TREATYBUSINESS_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE DROP CONSTRAINT PK_TREATYBUSINESS_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND CONSTRAINT_NAME = 'PK_TREATYSECREINS_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE DROP CONSTRAINT PK_TREATYSECREINS_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND CONSTRAINT_NAME = 'PK_TREATYREINSURER_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE DROP CONSTRAINT PK_TREATYREINSURER_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND CONSTRAINT_NAME = 'PK_TREATYCONTRACT_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE DROP CONSTRAINT PK_TREATYCONTRACT_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYYEAR_LIFE' AND CONSTRAINT_NAME = 'PK_TREATYYEAR_LIFE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYYEAR_LIFE DROP CONSTRAINT PK_TREATYYEAR_LIFE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND INDEX_NAME = 'IX_TBL_KONTRAK';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_TBL_KONTRAK';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND INDEX_NAME = 'IX_TSRL_REINSURER';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_TSRL_REINSURER';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND INDEX_NAME = 'IX_TRL_KONTRAK';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_TRL_KONTRAK';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND INDEX_NAME = 'IX_TCL_TAHUN';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_TCL_TAHUN';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYBUSINESS_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYBUSINESS_LIFE MODIFY (TREATYCONTRACTID NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYSECURITYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYREINSURERID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYSECURITYREINSURER_LIFE MODIFY (TREATYREINSURERID NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYREINSURER_LIFE' AND COLUMN_NAME = 'TREATYCONTRACTID';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYREINSURER_LIFE MODIFY (TREATYCONTRACTID NULL)';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'TREATYCONTRACT_LIFE' AND COLUMN_NAME = 'IDTREATYYEAR';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.TREATYCONTRACT_LIFE MODIFY (IDTREATYYEAR NULL)';
  END IF;
END;
/
