-- Mundur 680 - dua penanda usul dibuang beserta isinya; untuk skema uji.
--
-- NOL COMMIT (ADR-U-0029).
ALTER TABLE {skema}.T_GENERAL_KOMITE DROP CONSTRAINT CK_GENERAL_KOMITE_USUL_CADANG
/
ALTER TABLE {skema}.T_GENERAL_KOMITE DROP CONSTRAINT CK_GENERAL_KOMITE_USUL_TUTUP
/
ALTER TABLE {skema}.T_GENERAL_KOMITE DROP (KOMITE_USUL_TUTUP, KOMITE_USUL_CADANG)
/
