-- Jalur mundur 560 - buang kolom khas FACIN dari T_GENERAL_CLAIM.
ALTER TABLE {skema}.T_GENERAL_CLAIM DROP (
  PRODKE, QQ_NAME, CEDING_CO_NAME, SOB_NAME, COUNTRY, COUNTRY_ID, CURRENCY_VALUE_IDR, GROSS_ESTIMATE, CLAIM_ESTIMATE, EX_GRATIA, IS_ERROR, IS_REGISTER, IS_ESTIMATION, IS_ADJUSTMENT, IS_PIC_TRANSFER, IS_TREATY_OUT, PY_NOTE, START_DATE_REGISTER, END_DATE_REGISTER
)
/
