-- Jalur mundur 563.
DROP INDEX {skema}.IX_CLAIM_EST_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_ESTIMATION DROP CONSTRAINT FK_CLAIM_EST_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_ESTIMATION DROP (
  OBJECT_ITEM_ID, GROSS_ESTIMATION_MBU, DEDUCTIBLE, NET_ESTIMATION_VALUE, IS_MORE_THAN_TSI, CREATED_BY
)
/
