-- Jalur mundur 564.
DROP INDEX {skema}.IX_CLAIM_SPRD_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_SPREADING DROP CONSTRAINT FK_CLAIM_SPRD_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_SPREADING DROP (
  OBJECT_ITEM_ID, JENIS, TSI_SPREADED, PREMIUM_SPREADED
)
/
