-- 564 - T_CLAIM_SPREADING (Claim Prop 525) dipakai lini FAC: SpreadingList polis item (JENIS "POLIS") dan
-- SpreadingClaim item (JENIS "KLAIM"); JENIS kosong pada baris Prop / Non Prop. OBJECT_ITEM_ID (OQ-CFI-01).
-- NOL COMMIT (ADR-U-0029), nol MODIFY / DROP kolom yang sudah ada. -migrate dijalankan work owner.
ALTER TABLE {skema}.T_CLAIM_SPREADING ADD (
  OBJECT_ITEM_ID   VARCHAR2(32),
  JENIS            VARCHAR2(16),
  TSI_SPREADED     NUMBER(38,10),
  PREMIUM_SPREADED NUMBER(38,10)
)
/
ALTER TABLE {skema}.T_CLAIM_SPREADING ADD CONSTRAINT FK_CLAIM_SPRD_OBJ_ITEM FOREIGN KEY (OBJECT_ITEM_ID)
  REFERENCES {skema}.T_CLAIM_OBJECT_ITEM (ID) ON DELETE CASCADE
/
CREATE INDEX {skema}.IX_CLAIM_SPRD_OBJ_ITEM ON {skema}.T_CLAIM_SPREADING (OBJECT_ITEM_ID)
/
