-- Jalur mundur 565.
DROP INDEX {skema}.IX_CLAIM_BQS_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_BREAK_QS DROP CONSTRAINT FK_CLAIM_BQS_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_BREAK_QS DROP (
  OBJECT_ITEM_ID
)
/
