-- Jalur mundur 566.
DROP INDEX {skema}.IX_CLAIM_ADJ_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_ADJUSTMENT DROP CONSTRAINT FK_CLAIM_ADJ_OBJ_ITEM
/
ALTER TABLE {skema}.T_CLAIM_ADJUSTMENT DROP (
  OBJECT_ITEM_ID, NET_FOR_COLLECTION, CURRENCY_ESTIMASI, ESTIMATION_VALUE, CURRENCY_CHOICE_ID, SURVEY_EXPENSES, VAT_PCT, VAT_VALUE, PROFESSIONAL_FEE, EX_GRATIA, TOTAL_SHARE_PCT, TOTAL_SPREAD_ADJUSTMENT, TOTAL_SPREAD_BREAK_QS, CEDANT_CHOICE
)
/
