-- 566 - T_CLAIM_ADJUSTMENT (Claim Prop 528) dipakai lini FAC: ObjectItemList(i).Adjustment (panel InputAdjustment).
-- OBJECT_ITEM_ID (OQ-CFI-01); kolom khas Fac In nullable; CEDANT_CHOICE = pilihan Cedant Panel (SetCedant_act:
-- "*" Choose All / kode CedingCo).
-- NOL COMMIT (ADR-U-0029), nol MODIFY / DROP kolom yang sudah ada. -migrate dijalankan work owner.
ALTER TABLE {skema}.T_CLAIM_ADJUSTMENT ADD (
  OBJECT_ITEM_ID          VARCHAR2(32),
  NET_FOR_COLLECTION      VARCHAR2(16),
  CURRENCY_ESTIMASI       VARCHAR2(64),
  ESTIMATION_VALUE        NUMBER(38,10),
  CURRENCY_CHOICE_ID      VARCHAR2(64),
  SURVEY_EXPENSES         NUMBER(38,10),
  VAT_PCT                 NUMBER(38,10),
  VAT_VALUE               NUMBER(38,10),
  PROFESSIONAL_FEE        NUMBER(38,10),
  EX_GRATIA               VARCHAR2(16),
  TOTAL_SHARE_PCT         NUMBER(38,10),
  TOTAL_SPREAD_ADJUSTMENT NUMBER(38,10),
  TOTAL_SPREAD_BREAK_QS   NUMBER(38,10),
  CEDANT_CHOICE           VARCHAR2(64)
)
/
ALTER TABLE {skema}.T_CLAIM_ADJUSTMENT ADD CONSTRAINT FK_CLAIM_ADJ_OBJ_ITEM FOREIGN KEY (OBJECT_ITEM_ID)
  REFERENCES {skema}.T_CLAIM_OBJECT_ITEM (ID) ON DELETE CASCADE
/
CREATE INDEX {skema}.IX_CLAIM_ADJ_OBJ_ITEM ON {skema}.T_CLAIM_ADJUSTMENT (OBJECT_ITEM_ID)
/
