-- Jalur mundur 567.
DROP INDEX {skema}.IX_CLAIM_FAC_RETRO_ADJ
/
ALTER TABLE {skema}.T_CLAIM_FAC_RETRO DROP CONSTRAINT FK_CLAIM_FAC_RETRO_ADJ
/
ALTER TABLE {skema}.T_CLAIM_FAC_RETRO DROP (
  ADJUSTMENT_ID
)
/
