// Command bangkit menulis daftar modul Go dari isi folder `modul/` -
// struktur tim satu folder per modul (30-09-2026).
//
// Dijalankan lewat `go generate ./inti/backend/daftar` dari folder APP_RNM
// (direktifnya di `inti/backend/daftar/pembangkit.go`). Untuk setiap folder
// `modul/<nama>/backend/modul.go` ia menulis SATU berkas
// `inti/backend/daftar/modul_<nama>_gen.go` yang mendaftarkan
// `<nama>.Pendaftaran()`, dan membuang berkas bangkitan yang foldernya sudah
// tidak ada. Folder kerangka (hanya `MODUL.md` dan `docs/`) tidak terdaftar.
//
// ⛔ Kenapa SATU BERKAS PER MODUL, bukan satu daftar: dua cabang yang
// masing-masing memulai satu modul menyisipkan baris di tempat yang sama di
// daftar tunggal yang terurut - git menyatakannya konflik. Berkas terpisah
// hanya bertambah, tidak pernah bertabrakan.
//
// Berkas bangkitan di-commit; `main_test.go` menjaga "hasil bangkit = isi
// folder" dan menyebut perintah ini bila lupa dijalankan.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// awalanBerkas dan akhiranBerkas membentuk nama berkas bangkitan.
const (
	awalanBerkas  = "modul_"
	akhiranBerkas = "_gen.go"
)

// perintah adalah cara menjalankan pembangkit ini, disebut di setiap galat.
const perintah = "go generate ./inti/backend/daftar (dari folder APP_RNM)"

func main() {
	// `go generate` menjalankan perintah di folder berkas direktifnya:
	// inti/backend/daftar - tiga tingkat di bawah APP_RNM.
	akar := filepath.Join("..", "..", "..")
	berkas, err := bangkit(akar)
	if err != nil {
		log.Fatalf("bangkit: %v", err)
	}
	if err := tulis(".", berkas); err != nil {
		log.Fatalf("bangkit: %v", err)
	}
}

// bangkit menyusun isi setiap berkas bangkitan dari folder `modul/` di bawah
// `akar` (APP_RNM), berkunci nama berkas.
func bangkit(akar string) (map[string][]byte, error) {
	cocok, err := filepath.Glob(filepath.Join(akar, "modul", "*", "backend", "modul.go"))
	if err != nil {
		return nil, err
	}
	hasil := map[string][]byte{}
	for _, c := range cocok {
		nama := filepath.Base(filepath.Dir(filepath.Dir(c)))
		if err := periksaModulGo(c, nama); err != nil {
			return nil, err
		}
		isi, err := format.Source([]byte(fmt.Sprintf(templat, nama, nama, nama, nama)))
		if err != nil {
			return nil, fmt.Errorf("menyusun berkas modul %s: %w", nama, err)
		}
		hasil[awalanBerkas+nama+akhiranBerkas] = isi
	}
	return hasil, nil
}

// periksaModulGo memastikan `modul/<nama>/backend/modul.go` berbentuk
// pendaftaran: paket `backend`, `const Nama = "<nama>"` (nama folder), dan
// `func Pendaftaran() inti.Pendaftaran` tanpa parameter.
func periksaModulGo(jalur, nama string) error {
	letak := "modul/" + nama + "/backend/modul.go"
	f, err := parser.ParseFile(token.NewFileSet(), jalur, nil, parser.SkipObjectResolution)
	if err != nil {
		return fmt.Errorf("%s: %w", letak, err)
	}
	if f.Name.Name != "backend" {
		return fmt.Errorf("%s ber-`package %s`; setiap modul.go wajib `package backend` "+
			"(berkas bangkitan mengimpornya dengan alias nama modul)", letak, f.Name.Name)
	}
	namaConst, adaNama, adaDaftar := "", false, false
	for _, d := range f.Decls {
		switch d := d.(type) {
		case *ast.GenDecl:
			if d.Tok != token.CONST {
				continue
			}
			for _, s := range d.Specs {
				v := s.(*ast.ValueSpec)
				for i, n := range v.Names {
					if n.Name != "Nama" || i >= len(v.Values) {
						continue
					}
					if lit, ok := v.Values[i].(*ast.BasicLit); ok && lit.Kind == token.STRING {
						namaConst, adaNama = lit.Value, true
					}
				}
			}
		case *ast.FuncDecl:
			if d.Name.Name == "Pendaftaran" && d.Recv == nil && d.Type.Params.NumFields() == 0 &&
				d.Type.Results.NumFields() == 1 {
				adaDaftar = true
			}
		}
	}
	switch {
	case !adaNama:
		return fmt.Errorf("%s tanpa `const Nama = %q`", letak, nama)
	case namaConst != fmt.Sprintf("%q", nama):
		return fmt.Errorf("%s: const Nama = %s, mau %q - nama modul = nama foldernya", letak, namaConst, nama)
	case !adaDaftar:
		return fmt.Errorf("%s tanpa `func Pendaftaran() inti.Pendaftaran` (tanpa parameter)", letak)
	}
	return nil
}

// templat - satu berkas bangkitan. %s: nama modul.
const templat = `// Code generated by go generate (inti/backend/daftar/bangkit); DO NOT EDIT.
//
// Sumber: modul/%s/backend/modul.go. Satu berkas per modul: lihat
// inti/backend/daftar/bangkit/main.go.

package daftar

import %s "nusantarare/modul/%s/backend"

func init() { daftarkan(%s.Pendaftaran()) }
`

// periksa membandingkan berkas bangkitan di folder `dir` dengan hasil
// `bangkit(akar)` - "hasil bangkit = isi folder". Galatnya menyebut setiap
// berkas yang hilang, berlebih, atau berbeda, dan perintah yang memperbaikinya.
func periksa(akar, dir string) error {
	mau, err := bangkit(akar)
	if err != nil {
		return err
	}
	ada, err := filepath.Glob(filepath.Join(dir, awalanBerkas+"*"+akhiranBerkas))
	if err != nil {
		return err
	}
	var beda []string
	dilihat := map[string]bool{}
	for _, j := range ada {
		n := filepath.Base(j)
		dilihat[n] = true
		isi, err := os.ReadFile(j)
		if err != nil {
			return err
		}
		switch m, perlu := mau[n]; {
		case !perlu:
			beda = append(beda, n+" berlebih (foldernya tidak punya backend/modul.go)")
		case string(isi) != string(m):
			beda = append(beda, n+" berbeda isi")
		}
	}
	for n := range mau {
		if !dilihat[n] {
			beda = append(beda, n+" hilang")
		}
	}
	if len(beda) == 0 {
		return nil
	}
	sort.Strings(beda)
	return fmt.Errorf("daftar modul basi - jalankan %s:\n  %s", perintah, strings.Join(beda, "\n  "))
}

// tulis menyamakan folder `dir` dengan `berkas`: menulis yang berbeda dan
// membuang berkas bangkitan yang tidak ada lagi di `berkas`.
func tulis(dir string, berkas map[string][]byte) error {
	lama, err := filepath.Glob(filepath.Join(dir, awalanBerkas+"*"+akhiranBerkas))
	if err != nil {
		return err
	}
	for _, l := range lama {
		if _, ada := berkas[filepath.Base(l)]; !ada {
			if err := os.Remove(l); err != nil {
				return err
			}
		}
	}
	var nama []string
	for n := range berkas {
		nama = append(nama, n)
	}
	sort.Strings(nama)
	for _, n := range nama {
		p := filepath.Join(dir, n)
		if sekarang, err := os.ReadFile(p); err == nil && string(sekarang) == string(berkas[n]) {
			continue
		}
		if err := os.WriteFile(p, berkas[n], 0o644); err != nil {
			return err
		}
	}
	return nil
}
