-- LANGKAH-WO-PLANLIFE.md (c) - BACA-SAJA, SESUDAH 946-949. Angka harus sama dengan plan_acuan.txt; lalu CSV sesudah
-- untuk MINUS dua arah. Dijalankan sebagai BERKAS (@...) dari folder cadangan.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL plan_verifikasi.txt
PROMPT 1. Kolom akhir PRODUCT_TYPE_LIFE (urutan view lama): ID VARCHAR2(6) NOT NULL, COVERNAME 200, BUSINESS 200, BUSINESSID 10, BENEFIT 200, BENEFITID 10; nol JSONDATA
SELECT COLUMN_ID, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'PRODUCT_TYPE_LIFE' ORDER BY COLUMN_ID;
SELECT TABLE_NAME FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'PRODUCT_TYPE_LIFE';
PROMPT 2. Objek: PRODUCT_TYPE_LIFE = TABLE; M_PRODUCT_TYPE_LIFE tidak ada; sequence tetap; prosedur Pega INVALID (K3)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE_SEQ',
       'PEGA_M_PRODUCT_TYPE_LIFE') ORDER BY OBJECT_NAME;
SELECT COUNT(*) AS N_VIEW FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'PRODUCT_TYPE_LIFE';
PROMPT 3. Cacah (pembanding 32), ID unik, dan sidik = acuan (a) P2 kueri 2
SELECT COUNT(*) AS N, COUNT(DISTINCT ID) AS N_ID_UNIK, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI FROM POOLDATA.PRODUCT_TYPE_LIFE;
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(COVERNAME) AS N_COVERNAME, COUNT(BUSINESS) AS N_BUSINESS,
       COUNT(BUSINESSID) AS N_BUSINESSID, COUNT(BENEFIT) AS N_BENEFIT, COUNT(BENEFITID) AS N_BENEFITID,
       SUM(ORA_HASH(ID || '|' || COVERNAME || '|' || BUSINESS || '|' || BUSINESSID || '|' || BENEFIT || '|' || BENEFITID)) AS H_BARIS
  FROM POOLDATA.PRODUCT_TYPE_LIFE;
PROMPT 4. Constraint: PK_PRODUCT_TYPE_LIFE (P, ENABLED) ada; ENSURE_M_PRODUCT_TYPE_LIFE hilang
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, STATUS FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'PRODUCT_TYPE_LIFE' ORDER BY CONSTRAINT_NAME;
PROMPT 5. T_MIGRASI (empat baris 946-949) dan baris menu (planlife, Plan, MASTER TREATY, 13, 1)
SELECT NAMA, DIJALANKAN_PADA FROM POOLDATA.T_MIGRASI WHERE NAMA IN ('946_product_type_life_ganti_nama',
  '947_product_type_life_kolom', '948_product_type_life_satu_tabel', '949_m_nav_menu_planlife') ORDER BY NAMA;
SELECT KODE, LABEL, GROUPMENU, MODUL, URUTAN, DIMIGRASI, STATUS_AKTIF FROM POOLDATA.M_NAV_MENU
 WHERE KODE IN ('benefitlife', 'planlife') ORDER BY URUTAN;
PROMPT 6. Pembaca Product Name Life (kueri sqlCariPlan modul masterproductnamelife) tetap jalan - 32 baris
SELECT COUNT(*) AS N_PLAN_MPNL FROM (SELECT ID, COVERNAME, BUSINESS, BENEFIT FROM POOLDATA.PRODUCT_TYPE_LIFE);
SPOOL OFF
PROMPT 7. CSV sesudah (bentuk sama dengan PRODUCT_TYPE_LIFE_SEBELUM.csv)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON
SPOOL PRODUCT_TYPE_LIFE_SESUDAH.csv
SELECT ID, COVERNAME, BUSINESS, BUSINESSID, BENEFIT, BENEFITID FROM POOLDATA.PRODUCT_TYPE_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT verifikasi selesai: plan_verifikasi.txt, PRODUCT_TYPE_LIFE_SESUDAH.csv
