-- LANGKAH-WO-PLANLIFE.md (a) P3 - BACA-SAJA. CADANGAN WAJIB SEBELUM -migrate 946-949: ID + JSONDATA UTUH tabel
-- M_PRODUCT_TYPE_LIFE dan isi view PRODUCT_TYPE_LIFE, ke folder kerja SQL*Plus yang dibuat lebih dulu:
-- D:\NUSARE DEV\NUSARE\cadangan-planlife-<tanggal>\ (mis. cadangan-planlife-20261008). Tidak ada cadangan = TIDAK BOLEH
-- -migrate. Dijalankan sebagai BERKAS (@...) supaya TERMOUT OFF berlaku. SQL*Plus 12.2+ atau SQLcl (MARKUP CSV).
-- ⛔ JSONDATA memuat kunci px* (identitas operator): simpan di tempat cadangan DBA, jangan disalin ke dokumen / tiket.
--   M_PRODUCT_TYPE_LIFE_LENGKAP.csv - ID tabel + JSONDATA (satu-satunya salinan px*, pyRuleHarness, bentuk JSON asli)
--   PRODUCT_TYPE_LIFE_SEBELUM.csv   - 6 kolom view (ID, COVERNAME, BUSINESS, BUSINESSID, BENEFIT, BENEFITID) - acuan (c)
SET MARKUP CSV ON QUOTE ON
SET FEEDBACK OFF TERMOUT OFF PAGESIZE 0 LONG 2000000 LONGCHUNKSIZE 32767 LINESIZE 32767 TRIMSPOOL ON
SPOOL M_PRODUCT_TYPE_LIFE_LENGKAP.csv
SELECT ID, JSONDATA FROM POOLDATA.M_PRODUCT_TYPE_LIFE ORDER BY ID;
SPOOL OFF
SPOOL PRODUCT_TYPE_LIFE_SEBELUM.csv
SELECT ID, COVERNAME, BUSINESS, BUSINESSID, BENEFIT, BENEFITID FROM POOLDATA.PRODUCT_TYPE_LIFE ORDER BY ID;
SPOOL OFF
SET TERMOUT ON FEEDBACK ON MARKUP CSV OFF
PROMPT cadangan selesai: M_PRODUCT_TYPE_LIFE_LENGKAP.csv, PRODUCT_TYPE_LIFE_SEBELUM.csv - periksa keduanya terbuka dan berisi 32 baris
SELECT COUNT(*) AS N_TABEL FROM POOLDATA.M_PRODUCT_TYPE_LIFE;
SELECT COUNT(*) AS N_VIEW FROM POOLDATA.PRODUCT_TYPE_LIFE;
