-- LANGKAH-WO-PLANLIFE.md (a) P2 acuan dan (c)0 - BACA-SAJA. Angka acuan SEBELUM 946-949, dibaca lewat VIEW lama
-- PRODUCT_TYPE_LIFE (sumber kebenaran = JSONDATA). Dijalankan DUA kali: sesaat SEBELUM cadangan P3 dan TEPAT SEBELUM
-- -migrate; kedua keluaran harus SAMA (beda = ada penulis yang masih hidup - ulangi P1-P3). Keluaran ditambahkan ke
-- plan_acuan.txt. Kunci px* TIDAK pernah dicetak.
SET LINESIZE 300 PAGESIZE 100 NUMWIDTH 22
SPOOL plan_acuan.txt APPEND
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS DIBACA_PADA FROM DUAL;
PROMPT 1. Cacah (pembanding WO 08-10-2026: 32) dan ID tertinggi + sequence (last_number 44)
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(DISTINCT ID) AS N_ID_UNIK, MAX(LPAD(ID, 10, '0')) AS ID_TERTINGGI
  FROM POOLDATA.M_PRODUCT_TYPE_LIFE;
SELECT SEQUENCE_NAME, LAST_NUMBER, INCREMENT_BY, CACHE_SIZE FROM SYS.ALL_SEQUENCES
 WHERE SEQUENCE_OWNER = 'POOLDATA' AND SEQUENCE_NAME = 'M_PRODUCT_TYPE_LIFE_SEQ';
PROMPT 2. Sidik isi lewat view: cacah tidak-NULL per kolom + jumlah ORA_HASH per baris
SELECT COUNT(*) AS N, COUNT(ID) AS N_ID, COUNT(COVERNAME) AS N_COVERNAME, COUNT(BUSINESS) AS N_BUSINESS,
       COUNT(BUSINESSID) AS N_BUSINESSID, COUNT(BENEFIT) AS N_BENEFIT, COUNT(BENEFITID) AS N_BENEFITID,
       SUM(ORA_HASH(ID || '|' || COVERNAME || '|' || BUSINESS || '|' || BUSINESSID || '|' || BENEFIT || '|' || BENEFITID)) AS H_BARIS
  FROM POOLDATA.PRODUCT_TYPE_LIFE;
PROMPT 3. Nilai yang melewati lebar kolom tujuan (harus NOL baris; bila ada: BERHENTI)
SELECT ID FROM POOLDATA.PRODUCT_TYPE_LIFE
 WHERE LENGTHB(ID) > 6 OR LENGTHB(COVERNAME) > 200 OR LENGTHB(BUSINESS) > 200 OR LENGTHB(BUSINESSID) > 10
    OR LENGTHB(BENEFIT) > 200 OR LENGTHB(BENEFITID) > 10;
PROMPT 4. Definisi asli: kolom (NULLABLE ID / JSONDATA - dipakai jalur mundur) dan constraint (IS JSON, tanpa PK)
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE FROM SYS.ALL_TAB_COLUMNS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('M_PRODUCT_TYPE_LIFE', 'PRODUCT_TYPE_LIFE') ORDER BY TABLE_NAME, COLUMN_ID;
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE FROM SYS.ALL_CONSTRAINTS
 WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_PRODUCT_TYPE_LIFE' ORDER BY CONSTRAINT_NAME;
SELECT INDEX_NAME, COLUMN_NAME FROM SYS.ALL_IND_COLUMNS
 WHERE TABLE_OWNER = 'POOLDATA' AND TABLE_NAME = 'M_PRODUCT_TYPE_LIFE' ORDER BY INDEX_NAME, COLUMN_POSITION;
PROMPT 5. Objek, dependensi, grant (pembanding: VIEW + TABLE + SEQUENCE + PROCEDURE; dependensi hanya view + prosedur Pega; nol grant)
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS FROM SYS.ALL_OBJECTS
 WHERE OWNER = 'POOLDATA' AND OBJECT_NAME IN ('PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE_SEQ',
       'PEGA_M_PRODUCT_TYPE_LIFE') ORDER BY OBJECT_NAME;
SELECT OWNER, NAME, TYPE FROM SYS.ALL_DEPENDENCIES
 WHERE REFERENCED_OWNER = 'POOLDATA' AND REFERENCED_NAME IN ('M_PRODUCT_TYPE_LIFE', 'PRODUCT_TYPE_LIFE') ORDER BY OWNER, NAME;
SELECT GRANTEE, TABLE_NAME, PRIVILEGE FROM SYS.ALL_TAB_PRIVS
 WHERE TABLE_SCHEMA = 'POOLDATA' AND TABLE_NAME IN ('M_PRODUCT_TYPE_LIFE', 'PRODUCT_TYPE_LIFE');
SPOOL OFF
