-- LANGKAH-WO-PLANLIFE.md bab Pemulihan - BACA-SAJA. Penentu keadaan sesudah 946-949 gagal di tengah; bandingkan dengan
-- tabel keputusan K0-K4 di dokumen. Dijalankan sebagai BERKAS (@...).
SET LINESIZE 250 PAGESIZE 100
PROMPT 1. Objek, kolom, PK, catatan T_MIGRASI, dan menu
SELECT
  (SELECT COUNT(*) FROM SYS.ALL_VIEWS WHERE OWNER = 'POOLDATA' AND VIEW_NAME = 'PRODUCT_TYPE_LIFE')               AS ADA_VIEW,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'M_PRODUCT_TYPE_LIFE')           AS ADA_SUMBER,
  (SELECT COUNT(*) FROM SYS.ALL_TABLES WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'PRODUCT_TYPE_LIFE')             AS ADA_TARGET,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS c JOIN SYS.ALL_TABLES t ON t.OWNER = c.OWNER AND t.TABLE_NAME = c.TABLE_NAME
    WHERE c.OWNER = 'POOLDATA' AND c.TABLE_NAME IN ('PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE')
      AND c.COLUMN_NAME IN ('COVERNAME', 'BUSINESS', 'BUSINESSID', 'BENEFIT', 'BENEFITID'))                    AS KOLOM_BARU,
  (SELECT COUNT(*) FROM SYS.ALL_TAB_COLUMNS WHERE OWNER = 'POOLDATA' AND TABLE_NAME IN ('PRODUCT_TYPE_LIFE', 'M_PRODUCT_TYPE_LIFE')
      AND COLUMN_NAME = 'JSONDATA')                                                                             AS ADA_JSONDATA,
  (SELECT COUNT(*) FROM SYS.ALL_CONSTRAINTS WHERE OWNER = 'POOLDATA' AND CONSTRAINT_NAME = 'PK_PRODUCT_TYPE_LIFE')  AS ADA_PK,
  (SELECT COUNT(*) FROM SYS.ALL_PARTIAL_DROP_TABS WHERE OWNER = 'POOLDATA' AND TABLE_NAME = 'PRODUCT_TYPE_LIFE')  AS SETENGAH_TERBUANG,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '946_product_type_life_ganti_nama')                     AS T946,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '947_product_type_life_kolom')                          AS T947,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '948_product_type_life_satu_tabel')                     AS T948,
  (SELECT COUNT(*) FROM POOLDATA.T_MIGRASI WHERE NAMA = '949_m_nav_menu_planlife')                              AS T949,
  (SELECT COUNT(*) FROM POOLDATA.M_NAV_MENU WHERE KODE = 'planlife')                                            AS ADA_MENU
FROM DUAL;
PROMPT 2. Isi kolom (ORA-00904 / ORA-00942 = kolom / tabel belum ada pada nama itu, wajar)
SELECT COUNT(*) AS N, COUNT(COVERNAME) AS N_COVERNAME, COUNT(BENEFITID) AS N_BENEFITID FROM POOLDATA.PRODUCT_TYPE_LIFE;
