-- Jalur mundur 059 - kebalikan urutan maju, seluruhnya berpelindung katalog.
--
-- Index dan FK dibuang dulu, lalu lima kolom baru, lalu STATUS_WORK kembali
-- bernama STATUS - isinya ikut kembali. Di jalur mundur RENAME sah: penjaga
-- bentuk membaca jalur maju (`pelanggaranBlokPLSQL`), dan RENAME satu
-- pernyataan tanpa salin.
--
-- ⚠️ Pembuat, waktu, dan COVER_KEY yang sudah tertulis HILANG bersama
-- kolomnya. Jalur mundur ini untuk skema uji; di skema berisi data nyata ia
-- membuang jejak pembuat setiap kasus polis yang lahir sesudah 059.
--
-- ⛔ NOL `COMMIT` (ADR-U-0029).
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_INDEXES
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND INDEX_NAME = 'IX_WORK_POLIS_COVER_KEY';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX {skema}.IX_WORK_POLIS_COVER_KEY';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_CONSTRAINTS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND CONSTRAINT_NAME = 'FK_WORK_POLIS_COVER_KEY';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP CONSTRAINT FK_WORK_POLIS_COVER_KEY';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'TGL_UPDATE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP COLUMN TGL_UPDATE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'TGL_CREATE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP COLUMN TGL_CREATE';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'CREATE_OP_NAME';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP COLUMN CREATE_OP_NAME';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'CREATE_OP';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP COLUMN CREATE_OP';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'COVER_KEY';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS DROP COLUMN COVER_KEY';
  END IF;
END;
/
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM SYS.ALL_TAB_COLUMNS
   WHERE OWNER = UPPER('{skema}') AND TABLE_NAME = 'T_WORK_POLIS' AND COLUMN_NAME = 'STATUS_WORK';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE {skema}.T_WORK_POLIS RENAME COLUMN STATUS_WORK TO STATUS';
  END IF;
END;
/
