-- Jalur mundur 060 - sisa sel layar Input Offer.
ALTER TABLE {skema}.T_PREMIUM_LIST DROP (
  QQ_NAME, JENIS_USAHA, KETENTUAN_UNDERWRITING, TANGGAL_KONFIRMASI_BALIK,
  TANGGAL_REALISASI, TANGGAL_BIND, STATUS_FINAL
)
/
