-- Jalur mundur 189 - sub-tab Occupation.
DROP SEQUENCE {skema}.SEQ_T_TABLEOFLIMIT
/
DROP TABLE {skema}.T_TABLEOFLIMIT CASCADE CONSTRAINTS
/
DROP SEQUENCE {skema}.SEQ_T_OCCUPATIONLIST
/
DROP TABLE {skema}.T_OCCUPATIONLIST CASCADE CONSTRAINTS
/
