-- 196 - keputusan work owner butir 103 (04-10-2026): VIEW warisan yang dibaca nbfacin diganti TABEL flat BERNAMA SAMA,
-- isinya disalin dari view itu. Tahap ini: empat view atas JSON M_* - PROVINCE, ACCUMULATEDTYPE, CZONE, ACCUMULATION
-- (DDL `D:\migrasi\RNM\DDL\<NAMA>.txt`). CITY / DISTRICT / COVERAGE_FACIN / BRANDDETAIL / VJ_M_TYPE_PROPERTY_PLAN belum (A179).
--
-- Per view: (1) tabel _SALIN berkolom sama, (2) salin isi view, (3) DROP VIEW, (4) CREATE TABLE bernama view, (5) salin
-- balik, (6) DROP tabel _SALIN. Tabel akhir dibuat dengan CREATE TABLE eksplisit (bukan CTAS / RENAME) supaya penjaga
-- kolom membacanya. Urutan PROVINCE dulu: view CITY me-LEFT JOIN PROVINCE (view FORCE, tetap sah atas tabel bernama sama).
--
-- Tipe: setiap kolom keempat view = JSON dot-notation (`a.JSONDATA.<kunci>`), yang dikembalikan Oracle sebagai
-- VARCHAR2(4000) - sifat Oracle, BUKAN tertulis di korpus `[dugaan]` (A180): periksa dulu di DEV
-- `SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH FROM ALL_TAB_COLUMNS WHERE TABLE_NAME IN ('PROVINCE',
-- 'ACCUMULATEDTYPE', 'CZONE', 'ACCUMULATION')` sebelum menjalankan.
-- ⚠️ Menghapus objek (DROP VIEW) di skema sasaran; sesudahnya tabel = SALINAN saat migrasi - perubahan M_* (JSON) tidak
-- lagi terbawa. Ditulis, TIDAK dijalankan agent. Nol COMMIT (ADR-U-0029).
CREATE TABLE {skema}.PROVINCE_SALIN (
  ID         VARCHAR2(4000),
  NATIONID   VARCHAR2(4000),
  NOTE       VARCHAR2(4000),
  NATIONNAME VARCHAR2(4000)
)
/
INSERT INTO {skema}.PROVINCE_SALIN (ID, NATIONID, NOTE, NATIONNAME) SELECT ID, NATIONID, NOTE, NATIONNAME FROM {skema}.PROVINCE
/
DROP VIEW {skema}.PROVINCE
/
CREATE TABLE {skema}.PROVINCE (
  ID         VARCHAR2(4000),
  NATIONID   VARCHAR2(4000),
  NOTE       VARCHAR2(4000),
  NATIONNAME VARCHAR2(4000)
)
/
INSERT INTO {skema}.PROVINCE (ID, NATIONID, NOTE, NATIONNAME) SELECT ID, NATIONID, NOTE, NATIONNAME FROM {skema}.PROVINCE_SALIN
/
DROP TABLE {skema}.PROVINCE_SALIN
/
CREATE TABLE {skema}.ACCUMULATEDTYPE_SALIN (
  ID               VARCHAR2(4000),
  ACCUMULATIONTYPE VARCHAR2(4000),
  KEYWORD          VARCHAR2(4000),
  NOTE             VARCHAR2(4000),
  TYPE             VARCHAR2(4000)
)
/
INSERT INTO {skema}.ACCUMULATEDTYPE_SALIN (ID, ACCUMULATIONTYPE, KEYWORD, NOTE, TYPE) SELECT ID, ACCUMULATIONTYPE, KEYWORD, NOTE, TYPE FROM {skema}.ACCUMULATEDTYPE
/
DROP VIEW {skema}.ACCUMULATEDTYPE
/
CREATE TABLE {skema}.ACCUMULATEDTYPE (
  ID               VARCHAR2(4000),
  ACCUMULATIONTYPE VARCHAR2(4000),
  KEYWORD          VARCHAR2(4000),
  NOTE             VARCHAR2(4000),
  TYPE             VARCHAR2(4000)
)
/
INSERT INTO {skema}.ACCUMULATEDTYPE (ID, ACCUMULATIONTYPE, KEYWORD, NOTE, TYPE) SELECT ID, ACCUMULATIONTYPE, KEYWORD, NOTE, TYPE FROM {skema}.ACCUMULATEDTYPE_SALIN
/
DROP TABLE {skema}.ACCUMULATEDTYPE_SALIN
/
CREATE TABLE {skema}.CZONE_SALIN (
  ID          VARCHAR2(4000),
  CODE        VARCHAR2(4000),
  DESCRIPTION VARCHAR2(4000),
  GROUPOF     VARCHAR2(4000),
  GROUPOFNAME VARCHAR2(4000),
  TGLUPDATE   VARCHAR2(4000),
  USERID      VARCHAR2(4000)
)
/
INSERT INTO {skema}.CZONE_SALIN (ID, CODE, DESCRIPTION, GROUPOF, GROUPOFNAME, TGLUPDATE, USERID) SELECT ID, CODE, DESCRIPTION, GROUPOF, GROUPOFNAME, TGLUPDATE, USERID FROM {skema}.CZONE
/
DROP VIEW {skema}.CZONE
/
CREATE TABLE {skema}.CZONE (
  ID          VARCHAR2(4000),
  CODE        VARCHAR2(4000),
  DESCRIPTION VARCHAR2(4000),
  GROUPOF     VARCHAR2(4000),
  GROUPOFNAME VARCHAR2(4000),
  TGLUPDATE   VARCHAR2(4000),
  USERID      VARCHAR2(4000)
)
/
INSERT INTO {skema}.CZONE (ID, CODE, DESCRIPTION, GROUPOF, GROUPOFNAME, TGLUPDATE, USERID) SELECT ID, CODE, DESCRIPTION, GROUPOF, GROUPOFNAME, TGLUPDATE, USERID FROM {skema}.CZONE_SALIN
/
DROP TABLE {skema}.CZONE_SALIN
/
CREATE TABLE {skema}.ACCUMULATION_SALIN (
  ID               VARCHAR2(4000),
  ACCUMULATION     VARCHAR2(4000),
  ACCUMULATIONNAME VARCHAR2(4000),
  NOTE             VARCHAR2(4000),
  KEYWORD          VARCHAR2(4000),
  SCOPEAREA        VARCHAR2(4000),
  CZONE            VARCHAR2(4000),
  CZONEID          VARCHAR2(4000),
  PROVINCE         VARCHAR2(4000),
  PROVINCEID       VARCHAR2(4000),
  ZIPCODE          VARCHAR2(4000),
  ACCUMULATIONTYPE VARCHAR2(4000),
  SYARIAHSTATUS    VARCHAR2(4000)
)
/
INSERT INTO {skema}.ACCUMULATION_SALIN (ID, ACCUMULATION, ACCUMULATIONNAME, NOTE, KEYWORD, SCOPEAREA, CZONE, CZONEID, PROVINCE, PROVINCEID, ZIPCODE, ACCUMULATIONTYPE, SYARIAHSTATUS) SELECT ID, ACCUMULATION, ACCUMULATIONNAME, NOTE, KEYWORD, SCOPEAREA, CZONE, CZONEID, PROVINCE, PROVINCEID, ZIPCODE, ACCUMULATIONTYPE, SYARIAHSTATUS FROM {skema}.ACCUMULATION
/
DROP VIEW {skema}.ACCUMULATION
/
CREATE TABLE {skema}.ACCUMULATION (
  ID               VARCHAR2(4000),
  ACCUMULATION     VARCHAR2(4000),
  ACCUMULATIONNAME VARCHAR2(4000),
  NOTE             VARCHAR2(4000),
  KEYWORD          VARCHAR2(4000),
  SCOPEAREA        VARCHAR2(4000),
  CZONE            VARCHAR2(4000),
  CZONEID          VARCHAR2(4000),
  PROVINCE         VARCHAR2(4000),
  PROVINCEID       VARCHAR2(4000),
  ZIPCODE          VARCHAR2(4000),
  ACCUMULATIONTYPE VARCHAR2(4000),
  SYARIAHSTATUS    VARCHAR2(4000)
)
/
INSERT INTO {skema}.ACCUMULATION (ID, ACCUMULATION, ACCUMULATIONNAME, NOTE, KEYWORD, SCOPEAREA, CZONE, CZONEID, PROVINCE, PROVINCEID, ZIPCODE, ACCUMULATIONTYPE, SYARIAHSTATUS) SELECT ID, ACCUMULATION, ACCUMULATIONNAME, NOTE, KEYWORD, SCOPEAREA, CZONE, CZONEID, PROVINCE, PROVINCEID, ZIPCODE, ACCUMULATIONTYPE, SYARIAHSTATUS FROM {skema}.ACCUMULATION_SALIN
/
DROP TABLE {skema}.ACCUMULATION_SALIN
/
