// Label modul Company Detail - bahasa Inggris. Caption layar Pega SFAGIS Company Detail mengikuti screenshot work owner
// 03-10-2026 (layarnya tidak ada di korpus XML): Company Detail, NPWP, Parent organization, COUNTRY, Title,
// Organization Name, Business Field, Note; PIC: Name, Position, Gender, Email, Date of birth, Phone number; Address:
// Type, Address, Phone and Fax; Create. Client Status, Organization Established Date, Number of Employees, dan Owner
// DIHAPUS (keputusan work owner 04-10-2026). Pesan galat backend datang dari jawabannya sendiri.

/** Nama menu - `M_NAV_MENU.LABEL` baris modul ini (migrasi inti 907, keputusan work owner 04-10-2026). */
export const MENU_CD = { kelompok: 'Company Detail' } as const

export const CD = {
  judul: 'Company Detail',
  create: 'Create',
  cari: 'Search organization name, ORG ID, or NPWP',
  tombolCari: 'Search',
  memuat: 'Loading organizations…',
  memuatDetail: 'Loading organization…',
  memuatPilihan: 'Loading options…',
  kosong: 'No organization yet.',
  tidakCocok: 'No organization matches the search.',
  jumlah: (n: number) => `${n.toLocaleString('en-US')} organizations`,
  halaman: (h: number, total: number) => `Page ${h} of ${total}`,
  sebelumnya: '‹ Previous',
  berikutnya: 'Next ›',

  kolomId: 'ORG ID',
  kolomAksi: 'Action',
  lihat: 'View',
  ubah: 'Edit',

  judulBaru: 'Create organization',
  judulUbah: (idView: string) => `Edit organization ${idView}`,
  kembali: '← Organizations',
  judulLihat: (idView: string) => `Organization ${idView}`,
  kosongNilai: '—',
  companyDetail: 'Company Detail',
  idOtomatis: 'Generated when created',
  npwp: 'NPWP',
  parent: 'Parent organization',
  hapusParent: 'Clear',
  country: 'COUNTRY',
  title: 'Title',
  organizationName: 'Organization Name',
  businessField: 'Business Field',
  note: 'Note',
  pilih: '— select —',
  nilaiLama: (nilai: string) => `${nilai} (old value)`,

  pic: 'PIC',
  name: 'Name',
  position: 'Position',
  gender: 'Gender',
  email: 'Email',
  dateOfBirth: 'Date of birth',
  phoneNumber: 'Phone number',
  tambahPIC: 'Add PIC',
  kosongPIC: 'No PIC yet.',

  address: 'Address',
  type: 'Type',
  phoneAndFax: 'Phone and Fax',
  kodeArea: 'Area code',
  lainnya: 'Others',
  isiKodeArea: 'Code',
  nomor: 'Number',
  tambahAlamat: 'Add address',
  tambahNomor: 'Add number',
  kosongAlamat: 'No address yet.',
  kosongNomor: 'No phone or fax.',
  hapus: 'Remove',

  galatTitleDiNama: (title: string) => `Organization Name must not contain the title "${title}" - choose it in Title.`,
  judulCek: 'Check before create',
  memeriksa: 'Checking…',
  kalimatSerupa: (nama: string) => `"${nama}" is the same as or similar to these registered organizations:`,
  jenisSama: 'Same',
  jenisMirip: 'Similar',
  kolomKemiripan: 'Match',
  lanjutSimpan: 'Continue save',
  tidak: 'No',
  // Copy Old (perintah work owner 04-10-2026, seperti Product Name; hanya superadmin = pemegang Kelola User).
  copyOld: 'Copy Old',
  copyOldKeterangan:
    'Organizations in the old Pega documents whose data is not in the new tables yet. Tick the ones to copy, then press Process Copy.',
  prosesCopy: 'Process Copy',
  menyalin: 'Copying…',
  menyalinKemajuan: (selesai: number, total: number) => `Copying ${selesai} / ${total}…`,
  pilihSemua: 'Select all',
  pilihBaris: 'Select',
  dipilih: 'selected',
  kolomCatatan: 'To copy',
  copyOldKosong: 'All old organizations are already in the new tables.',
  catatanBaru: 'new organization',
  catatanPIC: (n: number) => `${n} PIC`,
  catatanNomor: (n: number) => `${n} phone/fax`,
  catatanIsi: (kolom: string[]) => `fill ${kolom.join(', ')}`,
  statusDisalin: 'Copied',
  statusSudahAda: 'Already in the new tables',
  statusDitolak: 'Cannot be copied',
  statusGagal: 'Failed',
  tutup: 'Close',
  simpan: 'Save',
  menyimpan: 'Saving…',
  batal: 'Cancel',
  tersimpan: (idView: string) => `Organization ${idView} saved.`,
  jejakDibuat: (oleh: string, waktu: string) => `Created by ${oleh} at ${waktu}`,
  jejakDiubah: (oleh: string, waktu: string) => `Last updated by ${oleh} at ${waktu}`,

  // Pemeriksaan awal - aturan sebenarnya di backend.
  galatNama: 'Organization Name is required',
  galatCountry: 'COUNTRY is required',
  galatBusinessField: 'Business Field is required',
  galatPICNama: (ke: number) => `PIC row ${ke}: Name is required`,
  galatPICPosisi: (ke: number) =>
    `PIC row ${ke}: Position is empty - fill the Job Position of this user in Kelola User`,
  galatAlamatType: (ke: number) => `Address row ${ke}: Type is required`,
  galatAlamat: (ke: number) => `Address row ${ke}: Address is required`,
  galatAlamatGanda: (ke: number, sebelum: number) => `Address row ${ke} repeats the address of row ${sebelum}`,
  galatNomor: (ke: number, no: number) => `Address row ${ke}, Phone and Fax ${no}: the number is required`,
  galatJenisNomor: (ke: number, no: number) => `Address row ${ke}, Phone and Fax ${no}: the type is required`,
} as const
