"""Bangkitkan tabel aturan pemeriksaan medis Go dari korpus Pega - tiket E20.

Membaca tiga activity `Endorsment Fac In/Activity/` (READ-ONLY):
`CalculateScorLife_Act` (skor lab), `CalculatePhysicalExam` (BMI, lingkar
perut), `SetParamLab_Act` (nilai rujukan lab). Menulis
`backend/services/medis/aturan_gen.go`: pohon langkah apa adanya - deskripsi,
prakondisi per baris (ekspresi, WhenTrue, WhenFalse), halaman `Page-Remove`,
dan penugasan Property-Set (nama, ekspresi). Ekspresi disalin VERBATIM dari
`<PropertiesValue>` / `<pyStepsPreCondParamsWhen>`, tidak ditafsirkan.

⛔ Ambang klinis tidak pernah disalin tangan (E20): satu-satunya jalan masuk
mereka ke kode adalah berkas bangkitan ini, dan berkas itu tidak boleh
disunting tangan.

⛔ PRIVASI: pyStepsRepeatDef dan isi pyStepsPreCondParams selain `...When`
tidak dibaca (E-Q15).

Akar korpus: `[terverifikasi]` di mesin ini `D:/XML/RNM_BRD` TIDAK ada
(`ls -d /d/XML/RNM_BRD` → tidak ditemukan) dan korpus siklus Fac In ada di
`D:/migrasi/RNM/` (`ls /d/migrasi/RNM` → `Endorsment Fac In`, `NB FacIn`,
`RNW Fac In`, `DDL`, …). CLAUDE.md §2 menyebut `D:/XML/RNM_BRD/`;
`[pertanyaan terbuka]` apakah itu salinan yang sama di mesin lain.

⛔ Keluaran yang memuat pola nomor polis (`RNM-…`, tak peka huruf) DITOLAK -
pembangkit berhenti, berkas tidak ditulis (CLAUDE.md §4.10).

Pemakaian (dari APP_RNM/modul/endorsmentfacin):
  PYTHONIOENCODING=utf-8 py docs/alat/bangkit_medis.py "D:/migrasi/RNM/Endorsment Fac In" \
      backend/services/medis/aturan_gen.go
"""
import json
import os
import re
import sys
import xml.etree.ElementTree as ET

SUMBER = [
    ("Activity/CalculateScorLife_Act.xml", "aturanSkor"),
    ("Activity/CalculatePhysicalExam.xml", "aturanFisik"),
    ("Activity/SetParamLab_Act.xml", "aturanParamLab"),
]

TAB = "\t"


def teks(el, jalur):
    c = el.find(jalur)
    return (c.text or "").strip() if c is not None and c.text else ""


def go(s):
    return json.dumps(s, ensure_ascii=False)


def langkah(rows, awalan, ind, keluar, cacah):
    for i, row in enumerate(rows, 1):
        nomor = f"{awalan}{i}"
        cacah["langkah"] += 1
        pad = TAB * ind
        metode = teks(row, "pyStepsActivityName")
        keluar.append(pad + "{")
        keluar.append(pad + TAB + f"nomor: {go(nomor)}, metode: {go(metode)}, deskripsi: {go(teks(row, 'pyStepsDescription'))},")
        keluar.append(pad + TAB + f"berprakondisi: {go(teks(row, 'pyStepsPreCondition') == 'true')},")
        # Label `//` (`pyStepsBlockName`) = di-remark, tidak dipakai lagi -
        # keputusan work owner 01-10-2026 butir 43 (nbfacin KEPUTUSAN-30-09-2026.md).
        if teks(row, "pyStepsBlockName") == "//":
            cacah["remark"] += 1
            keluar.append(pad + TAB + "diRemark: true,")
        if metode == "Page-Remove":
            halaman = [teks(p, "Page") for p in row.findall("pyParamArray/rowdata") if teks(p, "Page")]
            keluar.append(pad + TAB + f"halamanDihapus: {go(halaman[0] if halaman else '')},")
        baris = []
        for p in row.findall("pyStepsPreCondParams/rowdata"):
            w = teks(p, "pyStepsPreCondParamsWhen")
            if w:
                baris.append((w, teks(p, "pyStepsPreCondParamsWhenTrue"), teks(p, "pyStepsPreCondParamsWhenFalse")))
        if baris:
            keluar.append(pad + TAB + "prakondisi: []barisPrakondisi{")
            for w, t, f in baris:
                keluar.append(pad + TAB * 2 + f"{{ekspresi: {go(w)}, bilaBenar: {go(t)}, bilaSalah: {go(f)}}},")
            keluar.append(pad + TAB + "},")
        sets = []
        if metode != "Page-Remove":
            for p in row.findall("pyParamArray/rowdata"):
                n = p.find("PropertiesName")
                if n is not None:
                    sets.append(((n.text or "").strip(), teks(p, "PropertiesValue")))
        if sets:
            keluar.append(pad + TAB + "penugasan: []penugasan{")
            for n, v in sets:
                cacah["penugasan"] += 1
                keluar.append(pad + TAB * 2 + f"{{nama: {go(n)}, ekspresi: {go(v)}}},")
            keluar.append(pad + TAB + "},")
        anak = row.find("pySteps")
        if anak is not None and anak.findall("rowdata"):
            keluar.append(pad + TAB + "anak: []langkah{")
            langkah(anak.findall("rowdata"), nomor + ".", ind + 2, keluar, cacah)
            keluar.append(pad + TAB + "},")
        keluar.append(pad + "},")


def main():
    folder, tujuan = sys.argv[1], sys.argv[2]
    hasil = [
        "// Code generated by docs/alat/bangkit_medis.py; DO NOT EDIT.",
        "",
        "package medis",
        "",
        "// ⛔ Ambang klinis dan nilai rujukan di bawah adalah aturan medis dan bisnis,",
        "// diport APA ADANYA (K-046). Jangan disunting tangan: bangkitkan ulang dari korpus.",
        "",
    ]
    ringkas = []
    for sumber, nama in SUMBER:
        akar = ET.parse(os.path.join(folder, sumber)).getroot()
        cacah = {"langkah": 0, "penugasan": 0, "remark": 0}
        keluar = []
        langkah(akar.findall("pySteps/rowdata"), "", 2, keluar, cacah)
        hasil += [
            f"// {nama} - asal `Endorsment Fac In/{sumber}` (`{teks(akar, 'pxInsName')}`).",
            f"// [terverifikasi] {cacah['langkah']} langkah, {cacah['penugasan']} penugasan Property-Set.",
            f"// Cara kedua (grep): grep -c '<pxObjClass>Embed-ActivitySteps</pxObjClass>' dan",
            f"// grep -c '<PropertiesName' atas berkas yang sama - dijaga medis_test.go.",
            f"var {nama} = aktivitas{{",
            TAB + f"asal: {go(sumber)}, cacahLangkah: {cacah['langkah']}, cacahPenugasan: {cacah['penugasan']}, cacahRemark: {cacah['remark']},",
            TAB + "langkah: []langkah{",
        ] + keluar + [TAB + "},", "}", ""]
        ringkas.append(f"{nama}: {cacah['langkah']} langkah, {cacah['penugasan']} penugasan, {cacah['remark']} di-remark")
    keluaran = "\n".join(hasil)
    if re.search(r"RNM-[A-Z0-9]", keluaran, re.IGNORECASE):
        sys.exit("bangkit_medis: keluaran memuat pola nomor polis - berhenti, tidak ditulis")
    with open(tujuan, "w", encoding="utf-8", newline="\n") as f:
        f.write(keluaran)
    print(tujuan + ": " + "; ".join(ringkas))


if __name__ == "__main__":
    main()
