"""Saring keluaran generator registry predikat EDM sebelum masuk repo.

Alur (dari APP_RNM, korpus READ-ONLY):

    go run ./modul/nbfacin/backend/services/rules/bangkit -akar "D:\\migrasi\\RNM" \
        -folder "Endorsment Fac In\\When" -paket predikat -keluar <scratch>/registry.go
    py modul/endorsmentfacin/docs/alat/saring_registry.py <scratch>/registry.go \
        modul/endorsmentfacin/backend/services/predikat/registry_gen.go

Yang disaring: predikat yang membandingkan dengan LITERAL nomor polis atau ID
kasus (data pelanggan, CLAUDE.md §10), dan predikat yang membandingkan MEDAN
IDENTITAS (nomor polis, nama marketing = nama orang, telepon/login operator;
CLAUDE.md §4.10) dengan literal tidak-kosong, apa pun bentuk nilainya. Generator
nbfacin sejak 01-10-2026 menolak medan identitas sendiri; saringan ini lapis
kedua milik modul EDM, bukan pengganti. Seluruh predikatnya diganti menjadi
`panik` - nilainya tidak disalin; diport lewat konfigurasi (pola
`DaftarPolis`, E03), sama seperti generator memperlakukan login operator.

`--uji` menjalankan uji instrumen atas masukan sintetis yang jawabannya sudah
diketahui.
"""

import re
import sys

# Nomor polis (RNM-…, juga ejaan lain RN?-) dan ID kasus (NB-/EDM-/RNW-angka).
POLA_RAHASIA = re.compile(r"\bRN[A-Z]-[A-Z0-9]|\b(?:NB|EDM|RNW)-[0-9]", re.IGNORECASE)
POLA_AWAL = re.compile(r'^\t"([A-Z0-9_]+)": \{$')
# Segmen akhir sisi kiri yang literal tidak-kosongnya tidak boleh disalin.
MEDAN_IDENTITAS = {"OldPolicyNo", "PolicyNo", "MarketingName", "pyTelephone", "pyUserIdentifier"}
POLA_BANDING = re.compile(r'kiri: "([^"]*)",.*kanan: operand\{\w+, "([^"]*)"\}')
ALASAN = ("baris %s belum diport (membandingkan %s dengan literal identitas - nomor polis, ID kasus, "
          "nama, atau peran operator; nilainya tidak disalin, diport lewat konfigurasi/model peran)")


def identitas(baris):
    m = POLA_BANDING.search(baris)
    return bool(m) and m.group(1).split(".")[-1] in MEDAN_IDENTITAS and m.group(2) != ""


def saring(teks):
    baris = teks.split("\n")
    keluar, i, disaring = [], 0, []
    while i < len(baris):
        m = POLA_AWAL.match(baris[i])
        if not m:
            keluar.append(baris[i])
            i += 1
            continue
        j = i
        while baris[j] != "\t},":
            j += 1
        blok = baris[i:j + 1]
        kena = [b for b in blok if "kanan: operand{" in b and (POLA_RAHASIA.search(b) or identitas(b))]
        if not kena:
            keluar.extend(blok)
        else:
            label = re.search(r'"([A-Za-z0-9]+)": \{jenis', kena[0]).group(1)
            kiri = re.search(r'kiri: "([^"]*)"', kena[0]).group(1)
            asal = [b for b in blok if b.strip().startswith("asal:") or b.strip().startswith("logika:")]
            keluar.extend([blok[0]] + asal + ['\t\tpanik:  "%s",' % (ALASAN % (label, kiri)), "\t},"])
            disaring.append(m.group(1))
        i = j + 1
    hasil = "\n".join(keluar)
    hasil = hasil.replace("// Code generated by ./bangkit DO NOT EDIT.",
                          "// Code generated by ./bangkit DO NOT EDIT.\n// Disaring docs/alat/saring_registry.py: "
                          + (", ".join(disaring) or "tanpa entri") + ".", 1)
    if POLA_RAHASIA.search(hasil):
        raise SystemExit("saring: pola nomor polis/ID kasus masih ada sesudah saring")
    return hasil, disaring


def uji():
    contoh = "\n".join([
        "// Code generated by ./bangkit DO NOT EDIT.",
        "var registry = map[string]predikat{",
        '\t"ISAMAN": {',
        '\t\tasal:   []string{"x.xml (A!ISAMAN)"},',
        '\t\tlogika: "A",',
        '\t\tkondisi: map[string]kondisi{',
        '\t\t\t"A": {jenis: banding, kiri: ".X", tidakSama: false, kanan: operand{teksLiteral, "Fire"}},',
        "\t\t},",
        "\t},",
        '\t"ISRAHASIA": {',
        '\t\tasal:   []string{"y.xml (A!ISRAHASIA)"},',
        '\t\tlogika: "A OR B",',
        '\t\tkondisi: map[string]kondisi{',
        '\t\t\t"A": {jenis: banding, kiri: ".P", tidakSama: false, kanan: operand{teksLiteral, "Fire"}},',
        '\t\t\t"B": {jenis: banding, kiri: ".P", tidakSama: false, kanan: operand{teksLiteral, "' + "rn" + 'm-X1.00"}},',  # dirakit: berkas ini bebas pola
        "\t\t},",
        "\t},",
        '\t"ISNAMA": {',
        '\t\tasal:   []string{"n.xml (A!ISNAMA)"},',
        '\t\tlogika: "A OR B",',
        '\t\tkondisi: map[string]kondisi{',
        '\t\t\t"A": {jenis: banding, kiri: ".Q.MarketingName", tidakSama: false, kanan: operand{teksLiteral, ""}},',
        '\t\t\t"B": {jenis: banding, kiri: ".Q.MarketingName", tidakSama: false, kanan: operand{teksLiteral, "Uji Sintetis"}},',
        "\t\t},",
        "\t},",
        '\t"ISKOSONG": {',
        '\t\tasal:   []string{"k.xml (A!ISKOSONG)"},',
        '\t\tlogika: "A",',
        '\t\tkondisi: map[string]kondisi{',
        '\t\t\t"A": {jenis: banding, kiri: ".Q.PolicyNo", tidakSama: false, kanan: operand{teksLiteral, ""}},',
        "\t\t},",
        "\t},",
        '\t"ISKASUS": {',
        '\t\tasal:   []string{"z.xml (A!ISKASUS)"},',
        '\t\tlogika: "A",',
        '\t\tkondisi: map[string]kondisi{',
        '\t\t\t"A": {jenis: banding, kiri: "pyWorkPage.pyID", tidakSama: false, kanan: operand{teksLiteral, "EDM-1"}},',
        "\t\t},",
        "\t},",
        "}",
    ])
    hasil, disaring = saring(contoh)
    cek = [
        ("tiga entri disaring", disaring == ["ISRAHASIA", "ISNAMA", "ISKASUS"]),
        ("nama sintetis tidak tersalin", "Uji Sintetis" not in hasil),
        ("label nama = baris B (literal kosong A dilewati)", "baris B belum diport (membandingkan .Q.MarketingName" in hasil),
        ("cek isian kosong medan identitas tetap diport", '"ISKOSONG": {' in hasil and 'kiri: ".Q.PolicyNo"' in hasil),
        ("entri aman utuh", '"Fire"}},' in hasil and '"ISAMAN": {' in hasil),
        ("label baris pertama yang kena", "baris B belum diport (membandingkan .P" in hasil),
        ("nilai tidak tersalin", "X1.00" not in hasil and "EDM-1" not in hasil),
        ("asal & logika dipertahankan", "y.xml (A!ISRAHASIA)" in hasil and 'logika: "A OR B"' in hasil),
        ("tak peka huruf", "rnm-" not in hasil),
    ]
    for nama, ok in cek:
        print(("ok   " if ok else "GAGAL"), nama)
    sys.exit(0 if all(ok for _, ok in cek) else 1)


if __name__ == "__main__":
    if sys.argv[1:] == ["--uji"]:
        uji()
    src, dst = sys.argv[1], sys.argv[2]
    with open(src, encoding="utf-8") as f:
        hasil, disaring = saring(f.read())
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(hasil)
    print("saring: %d predikat disaring: %s" % (len(disaring), ", ".join(disaring)))
